import type { AIPanelCopy } from "./types";

export const KO_PANEL_COPY: AIPanelCopy = {
  runCost: {
    label: "{used} / {budget} 토큰",
    title: "이번 실행에서 사용한 모델 토큰 수 (실행당 예산 대비).",
  },
  runDetails: {
    label: "실행 상세",
    callCount: "도구 호출 {count}회",
    total: "총 {duration}",
    ok: "성공",
    failed: "실패",
    sqlLabel: "실행된 SQL",
  },
  responseActions: {
    regenerate: "다시 생성",
    regenerating: "다시 생성 중…",
    regenerateFailed: "다시 생성 실패 — 이전 답변을 유지합니다",
    helpful: "도움 됨",
    notHelpful: "도움 안 됨",
    feedbackTitle: "무엇이 잘못됐나요?",
    feedbackPlaceholder: "선택 사항: 에이전트가 다르게 해야 할 점을 알려주세요…",
    feedbackSubmit: "피드백 보내기",
    feedbackSaved: "피드백을 저장했습니다",
    feedbackFailed: "피드백을 저장하지 못했습니다",
    feedbackReasons: {
      wrongSql: "SQL이 틀림",
      misunderstood: "요청을 잘못 이해함",
      tooSlow: "너무 느림",
      other: "기타",
    },
    editPrompt: "수정 후 다시 실행",
    editPromptSave: "다시 실행",
    editPromptCancel: "취소",
    queuedCount: "{count}개 대기 중",
    queuedClear: "모두 버리기",
  },
  rules: {
    title: "가드레일 규칙",
    subtitle:
      "<workspace>/rules의 Markdown 규칙과 내장 팩이 에이전트가 실행하는 모든 문을 검사합니다.",
    close: "닫기",
    newRule: "새 규칙",
    globalRules: "전역 규칙",
    refresh: "목록 새로고침",
    loading: "불러오는 중…",
    empty: "활성화된 규칙이 없습니다.",
    armedCount: "{count}개 활성",
    errorsTitle: "불러오지 못한 파일",
    nameLabel: "규칙 이름",
    nameHint: "소문자, 숫자, '-', '_' (1-64자). <이름>.md 파일이 됩니다.",
    contentLabel: "규칙 파일 (.md)",
    contentHint: "프론트매터 + 본문. 쓰기 전에 유효성을 검사합니다.",
    cancel: "취소",
    create: "규칙 만들기",
    creating: "만드는 중…",
    savedAt: "규칙 저장 위치: {path}",
    originBuiltin: "내장",
    originGlobal: "전역",
    originWorkspace: "워크스페이스",
    actionWarn: "경고",
    actionRequireApproval: "승인 필요",
    actionBlock: "차단",
  },
};
