import type { AIPanelCopy } from "./types";

export const TR_PANEL_COPY: AIPanelCopy = {
  runCost: {
    label: "{used} / {budget} token",
    title: "Bu çalıştırmada kullanılan model tokeni (çalıştırma başına bütçeye göre).",
  },
  runDetails: {
    label: "Çalıştırma detayları",
    callCount: "{count} araç çağrısı",
    total: "Toplam {duration}",
    ok: "ok",
    failed: "hata",
    sqlLabel: "Çalıştırılan SQL",
  },
  responseActions: {
    regenerate: "Yeniden üret",
    regenerating: "Yeniden üretiliyor…",
    regenerateFailed: "Yeniden üretme başarısız — önceki yanıt korundu",
    helpful: "Yararlı",
    notHelpful: "Yararlı değil",
    feedbackTitle: "Ne yanlıştı?",
    feedbackPlaceholder: "İsteğe bağlı: ajanın neyi farklı yapması gerektiğini yazın…",
    feedbackSubmit: "Geri bildirim gönder",
    feedbackSaved: "Geri bildirim kaydedildi",
    feedbackFailed: "Geri bildirim kaydedilemedi",
    feedbackReasons: {
      wrongSql: "Yanlış SQL",
      misunderstood: "İstek yanlış anlaşıldı",
      tooSlow: "Çok yavaş",
      other: "Diğer",
    },
    editPrompt: "Düzenle ve yeniden çalıştır",
    editPromptSave: "Yeniden çalıştır",
    editPromptCancel: "İptal",
    queuedCount: "{count} sırada",
    queuedClear: "Tümünü at",
  },
  sqlValidationWarning:
    "Önerilen SQL sandbox doğrulamasını geçemedi ({error}); çalıştırmadan önce gözden geçirin veya düzeltin.",
  tokenBudgetReached: "Token bütçesine ulaşıldı — yanıt kesilmiş olabilir.",
  rules: {
    title: "Koruma kuralları",
    subtitle:
      "<workspace>/rules içindeki Markdown kuralları ve yerleşik paket, ajanın çalıştırdığı her ifadeyi denetler.",
    close: "Kapat",
    newRule: "Yeni kural",
    globalRules: "Genel kurallar",
    refresh: "Listeyi yenile",
    loading: "Yükleniyor…",
    empty: "Etkin kural yok.",
    armedCount: "{count} etkin",
    errorsTitle: "Yüklenemeyen dosyalar",
    nameLabel: "Kural adı",
    nameHint: "Küçük harf, rakam, '-' ve '_' (1-64). <ad>.md dosyası olur.",
    contentLabel: "Kural dosyası (.md)",
    contentHint: "Frontmatter + gövde. Dosya yazılmadan önce doğrulanır.",
    cancel: "İptal",
    create: "Kural oluştur",
    creating: "Oluşturuluyor…",
    savedAt: "Kural kaydedildi: {path}",
    originBuiltin: "yerleşik",
    originGlobal: "genel",
    originWorkspace: "çalışma alanı",
    actionWarn: "uyarı",
    actionRequireApproval: "onay gerekli",
    actionBlock: "engelle",
  },
};
