import type { AIWorkspaceCopy } from "./types";

export const EN_COPY: AIWorkspaceCopy = {
    bubbleMeta: {
      thinking: "Thinking",
      sandboxRun: "Sandbox run",
      needsReview: "Needs review",
      blockedInsert: "Blocked insert",
      reviewBeforeRun: "Review before run",
      ready: "Ready",
    },
    bubbleActions: {
      dragBubble: "Drag bubble",
      dragPointer: "Drag this arrow toward the place you want the AI to explain. Double click to reset.",
      dismissBubble: "Dismiss bubble",
      detail: "Detail",
      copy: "Copy",
      insert: "Insert",
      approveRun: "Approve Run",
      retry: "Retry",
    },
    modal: {
      kicker: "Bubble Detail",
      originalRequest: "Original Request",
      noRequest: "No request was captured for this bubble.",
      executionSummary: "Execution Summary",
      assistantExplanation: "Assistant Explanation",
      loadingExplanation: "The assistant is reading the context you pointed at and building an explanation.",
      sql: "SQL",
      agenticNote: "Agentic execution stays locked until you explicitly approve it.",
      rewriteTitle: "Rewrite This Bubble",
      rewriteHint: "Add the change you want, then ask the AI to write a new version.",
      rewritePlaceholder: "Example: make it safer for PostgreSQL, add comments, split DDL and DML, or explain the joins more clearly.",
      rewriting: "Rewriting...",
      rewriteBubble: "Rewrite Bubble",
      running: "Running...",
      approveAgenticRun: "Approve Agentic Run",
      reasoningLabel: "Model reasoning",
      reasoningShow: "Show reasoning",
      reasoningHide: "Hide reasoning",
      agentStepsLabel: "Agent steps",
      agentActionPlan: "Understanding the request",
      agentActionThink: "Thinking",
      agentActionAskUser: "Asking you",
      agentActionRememberTerm: "Learning",
      agentActionPreviewWrite: "Previewing changes",
      agentActionListTables: "Listing tables",
      agentActionDescribeTable: "Inspecting schema",
      agentActionRunSql: "Reading data",
      agentActionFinish: "Composing answer",
      agentStatusRunning: "Running",
      agentStatusDone: "Done",
      agentStatusError: "Issue",
    },
    composer: {
      alertDismiss: "Dismiss",
      inspectOnTitle: "Inspect mode is on. Select something and press Enter.",
      inspectOffTitle: "Open the AI assistant rail. Use Inspect to capture context from the workspace.",
      resizeHandleTitle: "Drag to resize the AI panel. Double-click to reset.",
      inspectHint: "Select text, then press Enter.",
      capturedLabel: "Captured",
      selectionReady: "Selection ready",
      kicker: "Workspace AI",
      title: "Assistant",
      noDatabaseSelected: "No database selected",
      noProvider: "No provider",
      tableOne: "table",
      tableOther: "tables",
      schemaShared: "Schema shared",
      promptOnly: "Prompt only",
      modePrompt: "Prompt",
      modeEdit: "Edit",
      modeAgent: "Agent",
      modePromptHint: "Ask directly with no schema context. Good for general help, writing, and quick questions.",
      modeEditHint: "Read the current DB schema and suggest reviewable SQL or changes before anything runs.",
      modeAgentHint: "Act like a general agent. It can answer directly, and when schema sharing is enabled it can inspect the current DB and prepare SQL for your approval.",
      agentAutonomyLabel: "Run access",
      agentAutonomyReview: "Always review",
      agentAutonomyReviewHint: "Ask me before running any SQL.",
      agentAutonomySmart: "Smart",
      agentAutonomySmartHint: "Auto-run safe read queries, ask before writes.",
      agentAutonomyFull: "Full access",
      agentAutonomyFullHint: "Auto-run safe reads; writes and schema changes still ask.",
      thinkingToggleLabel: "Thinking",
      thinkingToggleHint: "Show or hide the agent's live reasoning",
      thinkingOn: "On",
      thinkingOff: "Off",
      modeNeedsSchemaHint: "This mode needs schema sharing enabled in AI Provider Settings.",
      openSettings: "Open settings",
      switchToPrompt: "Use prompt mode",
      historyTitle: "Conversation history",
      historyHint: "Reopen a previous thread and continue where you left off.",
      historyEmpty: "Ask AI to start the first conversation in this workspace.",
      historyDeleteTitle: "Delete thread",
      historyDeleteConfirm: "Delete this conversation thread?",
      placeholder: "Ask a question, brainstorm, write content, explain code, or request SQL for this database.",
      note: "Enter to send. Use Inspect when you want grounded help from the workspace.",
      generating: "Generating...",
      cancelling: "Stopping...",
      cancelGeneration: "Stop",
      generateBubble: "Ask AI",
      promptIdeas: [
        {
          title: "Create table",
          prompt: "Create a users table with id, name, email, role, and created_at.",
        },
        {
          title: "Alter schema",
          prompt: "Add a last_login_at column to the users table and backfill it with CURRENT_TIMESTAMP.",
        },
        {
          title: "Write query",
          prompt: "Write a query that shows the top 10 users by order count in the last 30 days.",
        },
        {
          title: "Optimize query",
          prompt: "Optimize this SQL: SELECT * FROM orders WHERE DATE(created_at) = CURDATE()",
        },
        {
          title: "Fix error",
          prompt: "Fix this SQL error: SELECT * FRMO users",
        },
      ],
    },
    bubbleStates: {
      loadingInspectTitle: "Reading your selected context",
      loadingComposeTitle: "AI is shaping a new bubble",
      loadingInspectSubtitle: "Context scan is in progress",
      loadingInspectPreview: "Looking at the selected text, preparing an explanation, and drafting a safer suggestion if it fits.",
      loadingComposePreview: "Reviewing your schema, grounding the request, and composing SQL...",
      readyInspectTitle: "Context explanation ready",
      readySqlTitle: "SQL bubble ready",
      readyNoteTitle: "Assistant note ready",
      readyInspectSqlSubtitle: "Explained the selection and proposed a runnable fix",
      readyInspectNoteSubtitle: "Explained the selection and suggested next steps",
      readySqlSafeSubtitle: "Looks safe to insert",
      readySqlReviewSubtitle: "Review before running",
      readyOptimizeTitle: "Optimized SQL ready",
      readyOptimizeSubtitle: "SQL has been rewritten for better performance",
      readyFixErrorTitle: "SQL fix ready",
      readyFixErrorSubtitle: "The SQL error has been corrected",
      readyNoteSubtitle: "Explanation only, no runnable SQL yet",
      errorTitle: "Bubble could not be generated",
      errorSubtitle: "AI request failed",
      cancelledTitle: "Request stopped",
      cancelledSubtitle: "No provider request is still running",
      partialTitle: "Partial progress preserved",
      partialSubtitle: "The agent stopped before composing the final answer",
      selectSomethingError: "Select some code or UI text first, then press Enter while the AI orb is in inspect mode.",
      runSuccessTitle: "SQL ran in the sandbox",
      runSuccessSandboxSubtitle: "Protected execution boundary",
      runSuccessDirectSubtitle: "Executed directly",
      runFailedTitle: "Run failed",
      runFailedSubtitle: "Sandbox execution stopped",
      openedInWorkspaceTitle: "Opened in workspace",
      openedInWorkspaceSubtitle: "Sent to a workspace tab",
      openedInWorkspacePreview: "I opened this in a workspace tab so you can explore the result there. This conversation stays here for follow-up questions.",
    },
  };
