import type { AIWorkspaceCopy } from "./types";

export const KO_COPY: AIWorkspaceCopy = {
    bubbleMeta: {
      thinking: "생각 중",
      sandboxRun: "샌드박스 실행",
      needsReview: "검토 필요",
      blockedInsert: "삽입 차단됨",
      reviewBeforeRun: "실행 전 검토",
      ready: "준비됨",
    },
    bubbleActions: {
      dragBubble: "버블 드래그",
      dragPointer: "이 화살표를 AI가 설명할 위치로 드래그하세요. 초기화하려면 더블 클릭하세요.",
      dismissBubble: "버블 닫기",
      detail: "상세",
      copy: "복사",
      insert: "삽입",
      approveRun: "실행 승인",
      retry: "다시 시도",
    },
    modal: {
      kicker: "버블 상세",
      originalRequest: "원본 요청",
      noRequest: "이 버블에 대해 기록된 요청이 없습니다.",
      executionSummary: "실행 요약",
      assistantExplanation: "AI 설명",
      loadingExplanation: "AI가 가리킨 컨텍스트를 읽고 설명을 작성 중입니다.",
      sql: "SQL",
      agenticNote: "Agentic 실행은 명시적으로 승인할 때까지 잠겨 있습니다.",
      rewriteTitle: "이 버블 다시 쓰기",
      rewriteHint: "원하는 변경 사항을 입력한 다음 AI에게 새 버전을 작성하도록 요청하세요.",
      rewritePlaceholder: "예: PostgreSQL에 더 안전하게 만들기, 주석 추가, DDL과 DML 분리, 또는 조인 설명 명확하게 하기.",
      rewriting: "다시 쓰는 중...",
      rewriteBubble: "버블 다시 쓰기",
      running: "실행 중...",
      approveAgenticRun: "Agentic 실행 승인",
      reasoningLabel: "모델 추론",
      reasoningShow: "추론 보기",
      reasoningHide: "추론 숨기기",
      agentStepsLabel: "에이전트 단계",
      agentActionPlan: "?? ??",
      agentActionThink: "생각 중",
      agentActionAskUser: "질문 중",
      agentActionRememberTerm: "학습 중",
      agentActionPreviewWrite: "변경 미리보기",
      agentActionListTables: "테이블 목록",
      agentActionDescribeTable: "스키마 확인",
      agentActionRunSql: "데이터 읽기",
      agentActionFinish: "답변 작성",
      agentStatusRunning: "실행 중",
      agentStatusDone: "완료",
      agentStatusError: "확인 필요",
    },
    composer: {
      alertDismiss: "닫기",
      inspectOnTitle: "inspect 모드가 켜져 있습니다. 무언가를 선택하고 Enter를 누르세요.",
      inspectOffTitle: "AI 어시스턴트 레일을 열세요. Inspect를 사용하여 워크스페이스에서 컨텍스트를 캡처하세요.",
      resizeHandleTitle: "드래그하여 AI 패널 너비를 조절하세요. 더블 클릭하면 초기화됩니다.",
      inspectHint: "텍스트를 선택한 다음 Enter를 누르세요.",
      capturedLabel: "캡처됨",
      selectionReady: "선택 준비 완료",
      kicker: "워크스페이스 AI",
      title: "어시스턴트",
      noDatabaseSelected: "데이터베이스 선택 안 됨",
      noProvider: "프로바이더 없음",
      tableOne: "개 테이블",
      tableOther: "개 테이블",
      schemaShared: "스키마 공유됨",
      promptOnly: "프롬프트만",
      modePrompt: "프롬프트",
      modeEdit: "편집",
      modeAgent: "에이전트",
      modePromptHint: "프롬프트만으로 질문하세요. 스키마 컨텍스트가 전송되지 않습니다.",
      modeEditHint: "현재 DB 스키마를 읽고 SQL 또는 변경 사항을 제안하여 먼저 검토하세요.",
      modeAgentHint: "현재 DB 스키마를 읽고 실행 가능한 SQL을 준비하되 여전히 승인이 필요합니다.",
      agentAutonomyLabel: "실행 권한",
      agentAutonomyReview: "항상 검토",
      agentAutonomyReviewHint: "SQL을 실행하기 전에 항상 물어보세요.",
      agentAutonomySmart: "스마트",
      agentAutonomySmartHint: "안전한 읽기 쿼리는 자동 실행하고 쓰기 전에 물어봅니다.",
      agentAutonomyFull: "전체 권한",
      agentAutonomyFullHint: "안전한 읽기 쿼리는 자동 실행하고, 쓰기 및 스키마 변경은 계속 확인합니다.",
      thinkingToggleLabel: "??",
      thinkingToggleHint: "????? ??? ?? ??/??",
      thinkingOn: "??",
      thinkingOff: "??",
      modeNeedsSchemaHint: "이 모드에는 AI 프로바이더 설정에서 스키마 공유를 활성화해야 합니다.",
      openSettings: "설정 열기",
      switchToPrompt: "프롬프트 모드로 전환",
      historyTitle: "대화 기록",
      historyHint: "이전 스레드를 다시 열고 중단된 위치부터 계속하세요.",
      historyEmpty: "AI에게 이 워크스페이스에서 첫 대화를 시작하도록 요청하세요.",
      placeholder: "이 데이터베이스에 대해 질문하거나, SQL을 요청하거나, 원하는 변경 사항을 설명하세요.",
      note: "Enter로 보내기. 컨텍스트를 캡처하려면 Inspect를 사용하세요.",
      generating: "생성 중...",
      cancelling: "중지 중...",
      cancelGeneration: "중지",
      generateBubble: "AI에게 질문",
      promptIdeas: [
        { title: "테이블 생성", prompt: "id, name, email, role, created_at를 포함하는 users 테이블을 생성하세요." },
        { title: "스키마 변경", prompt: "users 테이블에 last_login_at 열을 추가하고 CURRENT_TIMESTAMP로 채워넣으세요." },
        { title: "쿼리 작성", prompt: "최근 30일 동안 주문 수 기준으로 상위 10명의 사용자를 표시하는 쿼리를 작성하세요." },
        { title: "쿼리 최적화", prompt: "이 SQL을 최적화하세요: SELECT * FROM orders WHERE DATE(created_at) = CURDATE()" },
        { title: "오류 수정", prompt: "이 SQL 오류를 수정하세요: SELECT * FRMO users" },
      ],
    },
    bubbleStates: {
      loadingInspectTitle: "선택한 컨텍스트 읽는 중",
      loadingComposeTitle: "AI가 새 버블을 작성하는 중",
      loadingInspectSubtitle: "컨텍스트 스캔 중",
      loadingInspectPreview: "선택한 텍스트를 확인하고 설명을 준비하며 적절하면 더 안전한 제안을 작성합니다.",
      loadingComposePreview: "스키마 검토, 컨텍스트 통합 및 SQL 작성 중...",
      readyInspectTitle: "컨텍스트 설명 준비 완료",
      readySqlTitle: "SQL 버블 준비 완료",
      readyNoteTitle: "AI 노트 준비 완료",
      readyInspectSqlSubtitle: " 선택 항목을 설명하고 실행 가능한 수정 제안",
      readyInspectNoteSubtitle: "선택 항목을 설명하고 다음 단계 제안",
      readySqlSafeSubtitle: "삽입해도 안전한 것 같음",
      readySqlReviewSubtitle: "실행 전 검토 필요",
      readyOptimizeTitle: "SQL 최적화됨",
      readyOptimizeSubtitle: "성능 향상을 위해 SQL이 다시 작성됨",
      readyFixErrorTitle: "SQL 수정됨",
      readyFixErrorSubtitle: "SQL 오류가 수정됨",
      readyNoteSubtitle: "설명만 있고 실행 가능한 SQL은 아직 없음",
      errorTitle: "버블을 생성할 수 없음",
      errorSubtitle: "AI 요청 실패",
      cancelledTitle: "요청 중지됨",
      cancelledSubtitle: "실행 중인 프로바이더 요청이 없습니다",
      partialTitle: "부분 진행 상황 보존됨",
      partialSubtitle: "에이전트가 최종 답변을 작성하기 전에 중지되었습니다",
      selectSomethingError: "먼저 코드 또는 UI 텍스트를 선택한 다음 AI 오브가 inspect 모드에 있을 때 Enter를 누르세요.",
      runSuccessTitle: "SQL이 샌드박스에서 실행됨",
      runSuccessSandboxSubtitle: "보호된 실행 경계",
      runSuccessDirectSubtitle: "직접 실행됨",
      runFailedTitle: "실행 실패",
      runFailedSubtitle: "샌드박스 실행 중지됨",
      openedInWorkspaceTitle: "워크스페이스에서 열림",
      openedInWorkspaceSubtitle: "워크스페이스 탭으로 전송됨",
      openedInWorkspacePreview: "이것을 워크스페이스 탭에서 열어 결과를 거기서 확인할 수 있습니다. 이 대화는 후속 질문을 위해 여기에 유지됩니다.",
    },
  };
