import type { AIWorkspaceCopy } from "./types";

export const TR_COPY: AIWorkspaceCopy = {
    bubbleMeta: {
      thinking: "Düşünüyor",
      sandboxRun: "Sandbox çalışması",
      needsReview: "İnceleme gerekli",
      blockedInsert: "Ekleme engellendi",
      reviewBeforeRun: "Çalıştırmadan önce incele",
      ready: "Hazır",
    },
    bubbleActions: {
      dragBubble: "Balonu sürükle",
      dragPointer: "Bu oku AI'nın açıklama yapmasını istediğiniz yere sürükleyin. Sıfırlamak için çift tıklayın.",
      dismissBubble: "Balonu kapat",
      detail: "Detay",
      copy: "Kopyala",
      insert: "Ekle",
      approveRun: "Çalıştırmayı onayla",
      retry: "Yeniden dene",
    },
    modal: {
      kicker: "Balon Detayı",
      originalRequest: "Orijinal İstek",
      noRequest: "Bu balon için kaydedilmiş bir istek yok.",
      executionSummary: "Çalıştırma Özeti",
      assistantExplanation: "AI Açıklaması",
      loadingExplanation: "AI, işaret ettiğiniz bağlamı okuyup açıklama hazırlıyor.",
      sql: "SQL",
      agenticNote: "Agentic çalıştırma, açıkça onaylayana kadar kilitli kalır.",
      rewriteTitle: "Bu Balonu Yeniden Yaz",
      rewriteHint: "İstediğiniz değişikliği yazın, ardından AI'dan yeni bir versiyon yazmasını isteyin.",
      rewritePlaceholder: "Örnek: PostgreSQL için daha güvenli yap, yorum ekle, DDL ve DML'yi ayır veya join'leri daha açık açıkla.",
      rewriting: "Yeniden yazılıyor...",
      rewriteBubble: "Balonu Yeniden Yaz",
      running: "Çalışıyor...",
      approveAgenticRun: "Agentic Çalıştırmayı Onayla",
      reasoningLabel: "Model muhakemesi",
      reasoningShow: "Muhakemeyi göster",
      reasoningHide: "Muhakemeyi gizle",
      agentStepsLabel: "Agent adımları",
      agentActionPlan: "İsteği anlıyor",
      agentActionThink: "Düşünüyor",
      agentActionAskUser: "Sana soruyorum",
      agentActionRememberTerm: "Öğreniyor",
      agentActionCreateCheckpoint: "Kontrol noktası oluşturuluyor",
      agentActionRestoreCheckpoint: "Checkpoint geri yükleniyor",
      agentActionPreviewWrite: "Değişiklik önizleme",
      agentActionListTables: "Tablolar listeleniyor",
      agentActionDescribeTable: "Şema inceleniyor",
      agentActionRunSql: "Veri okunuyor",
      agentActionFinish: "Yanıt hazırlanıyor",
      agentStatusRunning: "Çalışıyor",
      agentStatusDone: "Bitti",
      agentStatusError: "Sorun",
    },
    composer: {
      alertDismiss: "Kapat",
      inspectOnTitle: "İnceleme modu açık. Bir şey seçin ve Enter'a basın.",
      inspectOffTitle: "AI asistan panelini açın. Bağlamı almak için İnceleme'yi kullanın.",
      resizeHandleTitle: "AI panelini yeniden boyutlandırmak için sürükleyin. Sıfırlamak için çift tıklayın.",
      inspectHint: "Metin seçin, ardından Enter'a basın.",
      capturedLabel: "Yakalandı",
      selectionReady: "Seçim hazır",
      kicker: "Çalışma Alanı AI",
      title: "Asistan",
      noDatabaseSelected: "Veritabanı seçilmedi",
      slashCommandsTitle: "Komutlar",
      slashCommandsHint: "Filtrelemek için yazın · Çalıştırmak için Enter · Kapatmak için Esc",
      slashNoMatch: "Eşleşen komut yok",
      slashBackupDescription: "Mevcut veritabanı için geri yükleme kontrol noktası oluşturun.",
      slashCompactDescription: "Mevcut konuşmayı isteğe bağlı talimatlarla sıkıştırın.",
      slashRollbackDescription: "Veritabanını önceki bir /backup kontrol noktasına geri yükleyin.",
      checkpointTitle: "Veritabanını geri al",
      checkpointEmpty: "Henüz kontrol noktası yok — önce /backup çalıştırın.",
      checkpointHint: "Geri yüklenecek kontrol noktasını seçin. Mevcut verinin üzerine yazılacak.",
      checkpointRestoreAction: "Geri yükle",
      checkpointCancel: "İptal",
      checkpointDelete: "Kontrol noktasını sil",
      checkpointDeleteConfirm: "Silmeyi onaylamak için tekrar tıklayın",
    checkpointSearchPlaceholder: 'Checkpoint ara…',
    checkpointRename: 'Checkpoint yeniden adlandır',
    checkpointRenameTitle: 'Bu checkpoint için yeni bir ad girin.',
    // Etiket, veritabanı veya motorla filtreleyin.
      checkpointBack: "Geri",
      checkpointConfirmTitle: "Bu kontrol noktası geri yüklensin mi?",
      checkpointPreviewBody: "Mevcut veritabanına {statements} ifade çalıştırılacak ({schema} şema, {data} veri, {destructive} yıkıcı).",
      noProvider: "Sağlayıcı yok",
      tableOne: "tablo",
      tableOther: "tablo",
      schemaShared: "Şema paylaşıldı",
      promptOnly: "Yalnızca prompt",
      modePrompt: "Prompt",
      modeEdit: "Düzenle",
      modeAgent: "Agent",
      modePromptHint: "Hızlı soru, şema yok.",
      modeEditHint: "Şemadan SQL önerisi.",
      modeAgentHint: "Onayla, otomatik çalışır.",
      agentAutonomyLabel: "Çalıştırma izni",
      safeModeToggle: "Safe Mode",
        agentAutonomyReview: "Her zaman incele",
      agentAutonomyReviewHint: "Herhangi bir SQL çalıştırmadan önce bana sor.",
      agentAutonomySmart: "Akıllı",
      agentAutonomySmartHint: "Güvenli okuma sorgularını otomatik çalıştır, yazmadan önce sor.",
      agentAutonomyFull: "Tam erişim",
      agentAutonomyFullHint: "Güvenli okumaları otomatik çalıştırır; yazma ve şema değişiklikleri yine onay ister.",
      thinkingToggleLabel: "Düşünme",
      thinkingToggleHint: "Ajanın canlı muhakemesini göster veya gizle",
      thinkingOn: "Açık",
      thinkingOff: "Kapalı",
      autoProviderSwitchLabel: "Otomatik sağlayıcı geçişi",
      newChatTitle: "Yeni sohbet",
      reloadChatTitle: "Sohbeti kayıtlı geçmişten yeniden yükle",
      modeNeedsSchemaHint: "Bu mod, AI Sağlayıcı Ayarlarında şema paylaşımının etkinleştirilmesini gerektirir.",
      openSettings: "Ayarları aç",
      hiddenModelsToggle: "Gizli modeller",
      switchToPrompt: "Prompt moduna geç",
      historyTitle: "Konuşma geçmişi",
      historyEmpty: "AI'ya bu çalışma alanında ilk konuşmayı başlatmasını sorun.",
      historyRenameTitle: "Konuşmayı yeniden adlandır",
      placeholder: "Bu veritabanı hakkında sorun, SQL isteyin veya istediğiniz değişikliği açıklayın.",
      note: "Göndermek için Enter. Bağlamı almak için İnceleme'yi kullanın.",
      generating: "Oluşturuluyor...",
      cancelling: "Durduruluyor...",
      cancelGeneration: "Durdur",
      generateBubble: "AI'ya Sor",
      sqlConfirmWriteTitle: "Yazma SQL'i çalıştırılsın mı?",
      sqlConfirmWriteBody: "AI ajanı verileri değiştiren bir ifade çalıştırmak istiyor. Onaylamadan önce gözden geçirin.",
      sqlConfirmHighRiskTitle: "Yüksek riskli SQL çalıştırılsın mı?",
      sqlConfirmHighRiskBody: "Bu çalıştırma geri alınamaz şema değişiklikleri uygulayabilir. Her ifadeyi dikkatle inceleyin.",
      sqlConfirmPreviewLabel: "Çalıştırılacak SQL",
      sqlConfirmRunLabel: "SQL'i çalıştır",
      sqlConfirmCancelLabel: "İptal",
      sqlConfirmBatchLabel: "Bu çalıştırmada {count} ifade var.",
      autonomyFullConfirmTitle: "Tam erişim etkinleştirilsin mi?",
      autonomyFullConfirmBody: "Ajan hazırladığı tüm SQL'leri sormadan otomatik çalıştırır. Yazma ve şema işlemleri yine de çalıştırmadan önce onay ister.",
      autonomyFullConfirmAllow: "Tam erişimi etkinleştir",
      promptIdeas: [
        { title: "Tablo oluştur", prompt: "id, name, email, role ve created_at içeren bir users tablosu oluştur." },
        { title: "Şemayı değiştir", prompt: "users tablosuna last_login_at sütunu ekle ve CURRENT_TIMESTAMP ile doldur." },
        { title: "Sorgu yaz", prompt: "Son 30 günde sipariş sayısına göre en çok sipariş veren 10 kullanıcıyı gösteren bir sorgu yaz." },
        { title: "Sorguyu optimize et", prompt: "Bu SQL'i optimize et: SELECT * FROM orders WHERE DATE(created_at) = CURDATE()" },
        { title: "Hatayı düzelt", prompt: "Bu SQL hatasını düzelt: SELECT * FRMO users" },
      ],
    },
    bubbleStates: {
      loadingInspectTitle: "Seçili bağlam okunuyor",
      loadingComposeTitle: "AI yeni bir balon oluşturuyor",
      loadingInspectSubtitle: "Bağlam taranıyor",
      loadingInspectPreview: "Seçtiğiniz metne bakılıyor, açıklama hazırlanıyor ve uygunsa daha güvenli bir öneri yapılıyor.",
      loadingComposePreview: "Şema inceleniyor, bağlam birleştiriliyor ve SQL hazırlanıyor...",
      readyInspectTitle: "Bağlam açıklaması hazır",
      readySqlTitle: "SQL balonu hazır",
      readyNoteTitle: "AI notu hazır",
      readyInspectSqlSubtitle: "Seçimi açıkladı ve çalıştırılabilir bir düzeltme önerdi",
      readyInspectNoteSubtitle: "Seçimi açıkladı ve sonraki adımları önerdi",
      readySqlSafeSubtitle: "Güvenle eklenebilir görünüyor",
      readySqlReviewSubtitle: "Çalıştırmadan önce inceleyin",
      readyOptimizeTitle: "SQL optimize edildi",
      readyOptimizeSubtitle: "SQL daha iyi performans için yeniden yazıldı",
      readyFixErrorTitle: "SQL düzeltildi",
      readyFixErrorSubtitle: "SQL hatası düzeltildi",
      readyNoteSubtitle: "Yalnızca açıklama, henüz çalıştırılabilir SQL yok",
      errorTitle: "Balon oluşturulamadı",
      errorSubtitle: "AI isteği başarısız",
      cancelledTitle: "İstek durduruldu",
      cancelledSubtitle: "Çalışan bir sağlayıcı isteği kalmadı",
      partialTitle: "Kısmi ilerleme korundu",
      partialSubtitle: "Agent son yanıtı oluşturmadan önce durdu",
      selectSomethingError: "Önce bir kod veya UI metni seçin, ardından AI balonu inceleme modundayken Enter'a basın.",
      runSuccessTitle: "SQL sandbox'ta çalıştı",
      runSuccessSandboxSubtitle: "Korunan çalıştırma sınırı",
      runSuccessDirectSubtitle: "Doğrudan çalıştırıldı",
      runFailedTitle: "Çalıştırma başarısız",
      runFailedSubtitle: "Sandbox çalıştırmayı durdurdu",
      openedInWorkspaceTitle: "Çalışma alanında açıldı",
      openedInWorkspaceSubtitle: "Bir çalışma alanı sekmesine gönderildi",
      openedInWorkspacePreview: "Bunu bir çalışma alanı sekmesinde açtım, sonucu orada inceleyebilirsin. Bu sohbet, takip soruları için burada kalıyor.",
    },
    attachments: {
      attachButton: "Dosya veya resim ekle",
      imageUnsupported: "Etkin model resimleri okuyamıyor. Yalnızca metin dosyaları eklendi.",
      removeAttachment: "Eki kaldır",
      managerOpen: "Ekleri yönet",
      managerTitle: "Ekler",
      managerClose: "Kapat",
      managerFilterAll: "Tümü",
      managerFilterImages: "Resimler",
      managerFilterFiles: "Dosyalar",
      managerFiltersLabel: "Filtreler",
      managerStorageLabel: "Depolama",
      managerEmpty: "Henüz ek yok. Eklemek için dosyaları AI giriş alanına sürükleyin.",
      managerDeleteSelected: "Seçilenleri sil",
      managerDeleteAll: "Tümünü sil",
      managerDeleteAllConfirm: "Depolanan tüm ekler silinsin mi? Bu işlem geri alınamaz.",
      managerTotalSize: "Toplam boyut",
      managerUsageHint: "Ekler yerel olarak depolanır ve disk alanı kaplar. Yer açmak için eski ekleri silin.",
    },
    imageViewer: {
      close: "Görüntüleyiciyi kapat",
      download: "Görseli indir",
      resetZoom: "Yakınlaştırmayı sıfırla (%100)",
    },
    workspace: {
      switcherTitle: "Sohbet çalışma alanı",
      switcherHint: "Bağlam açık veritabanını takip eder; sabitlemek için pin kullanın.",
      rebindAction: "Veritabanı seç",
      rebindLockedTitle: "Bir ajan çalışıyor — veritabanını değiştirmeden önce bitmesini bekleyin veya iptal edin.",
      dbAuto: "Otomatik",
      dbCurrentHint: "Gezginde açık",
      autoMode: "Otomatik",
      newWorkspace: "+ Yeni çalışma alanı",
      defaultName: "Çalışma alanı",
      renameAction: "Yeniden adlandır",
      deleteAction: "Sil",
      chatActionTitle: "Sohbetleri yönet",
      chatActionCreate: "Yeni sohbet oluştur",
      chatActionAdd: "Mevcut sohbetleri ekle",
      chatActionBack: "Geri",
      addChatsTitle: "Çalışma alanına sohbet ekle",
      addChatsConfirm: "Çalışma alanına ekle",
      importSearchPlaceholder: "Ada veya anahtar kelimeye göre ara…",
      importEmpty: "Eklenecek başka sohbet yok.",
      compactAction: "/compact — bu sohbeti çalışma alanı bağlamına özetle",
      compactRunning: "Bağlam sıkıştırılıyor…",
      compactDoneTitle: "Bağlam sıkıştırıldı",
      compactDoneSubtitle: "Bu çalışma alanının bağlamına özetlendi",
      compactNeedsWorkspace: "/compact bağlamı kaydedebilsin diye önce bir sohbet çalışma alanı oluştur.",
      compactEmpty: "Sıkıştırılacak bir şey yok — önce bir şeyler sor.",
      contextBadge: "Bağlam",
    },
  };
