import type { AIWorkspaceCopy } from "./types";

export const VI_COPY: AIWorkspaceCopy = {
    bubbleMeta: {
      thinking: "Đang suy nghĩ",
      sandboxRun: "Chạy sandbox",
      needsReview: "Cần xem lại",
      blockedInsert: "Chặn chèn",
      reviewBeforeRun: "Xem lại trước khi chạy",
      ready: "Sẵn sàng",
    },
    bubbleActions: {
      dragBubble: "Kéo bong bóng",
      dragPointer: "Kéo mũi tên này tới chỗ bạn muốn AI giải thích. Double click để đặt lại.",
      dismissBubble: "Ẩn bong bóng",
      detail: "Chi tiết",
      copy: "Sao chép",
      insert: "Chèn",
      approveRun: "Duyệt chạy",
      retry: "Thử lại",
    },
    modal: {
      kicker: "Chi tiết bong bóng",
      originalRequest: "Yêu cầu gốc",
      noRequest: "Không có yêu cầu nào được lưu cho bong bóng này.",
      executionSummary: "Tóm tắt thực thi",
      assistantExplanation: "Giải thích của AI",
      loadingExplanation: "AI đang đọc ngữ cảnh bạn đã trỏ tới và chuẩn bị phần giải thích.",
      sql: "SQL",
      agenticNote: "Thực thi agentic vẫn bị khóa cho tới khi bạn duyệt rõ ràng.",
      rewriteTitle: "Viết lại bong bóng này",
      rewriteHint: "Nhập thay đổi bạn muốn, rồi yêu cầu AI viết lại phiên bản mới.",
      rewritePlaceholder: "Ví dụ: làm nó an toàn hơn cho PostgreSQL, thêm comment, tách DDL và DML, hoặc giải thích join rõ hơn.",
      rewriting: "Đang viết lại...",
      rewriteBubble: "Viết lại bong bóng",
      running: "Đang chạy...",
      approveAgenticRun: "Duyệt chạy agentic",
      reasoningLabel: "Suy luận của mô hình",
      reasoningShow: "Hiện suy luận",
      reasoningHide: "Ẩn suy luận",
      agentStepsLabel: "Các bước của agent",
      agentActionPlan: "Hiểu yêu cầu",
      agentActionThink: "Đang suy nghĩ",
      agentActionAskUser: "Đang hỏi bạn",
      agentActionRememberTerm: "Đang ghi nhớ",
      agentActionCreateCheckpoint: "Tạo điểm khôi phục",
      agentActionRestoreCheckpoint: "Đang khôi phục checkpoint",
      agentActionPreviewWrite: "Xem trước thay đổi",
      agentActionListTables: "Liệt kê bảng",
      agentActionDescribeTable: "Xem cấu trúc",
      agentActionRunSql: "Đọc dữ liệu",
      agentActionFinish: "Tổng hợp câu trả lời",
      agentStatusRunning: "Đang chạy",
      agentStatusDone: "Xong",
      agentStatusError: "Cần xem lại",
    },
    composer: {
      alertDismiss: "Đóng",
      inspectOnTitle: "Đang bật chế độ inspect. Bôi đen nội dung rồi nhấn Enter.",
      inspectOffTitle: "Mở khung AI. Dùng Inspect để lấy ngữ cảnh từ workspace.",
      resizeHandleTitle: "Kéo để đổi độ rộng khung AI. Nhấp đúp để đặt lại.",
      inspectHint: "Bôi đen nội dung rồi nhấn Enter.",
      capturedLabel: "Đã bắt",
      selectionReady: "Đã chọn xong",
      kicker: "AI Workspace",
      title: "Trợ lý AI",
      noDatabaseSelected: "Chưa chọn cơ sở dữ liệu",
      slashCommandsTitle: "Lệnh",
      slashCommandsHint: "Gõ để lọc · Enter để chạy · Esc để đóng",
      slashNoMatch: "Không có lệnh khớp",
      slashBackupDescription: "Tạo điểm khôi phục cho database hiện tại.",
      slashCompactDescription: "Nén hội thoại hiện tại kèm tuỳ chọn bổ sung.",
      slashRollbackDescription: "Khôi phục database về một điểm /backup trước đó.",
      checkpointTitle: "Rollback database",
      checkpointEmpty: "Chưa có điểm khôi phục nào — chạy /backup để tạo.",
      checkpointHint: "Chọn một điểm khôi phục. Dữ liệu hiện tại sẽ bị ghi đè.",
      checkpointRestoreAction: "Khôi phục",
      checkpointCancel: "Huỷ",
      checkpointDelete: "Xóa điểm khôi phục",
      checkpointDeleteConfirm: "Bấm lần nữa để xác nhận xóa",
    checkpointSearchPlaceholder: 'Tìm checkpoint…',
    checkpointRename: 'Đổi tên checkpoint',
    checkpointRenameTitle: 'Nhập tên mới cho checkpoint này.',
    // Lọc theo tên, database hoặc engine.
      checkpointBack: "Quay lại",
      checkpointConfirmTitle: "Khôi phục điểm này?",
      checkpointPreviewBody: "Sẽ chạy {statements} câu lệnh ({schema} schema, {data} dữ liệu, {destructive} phá huỷ) vào database hiện tại.",
      noProvider: "Chưa có provider",
      tableOne: "bảng",
      tableOther: "bảng",
      schemaShared: "Có chia sẻ schema",
      promptOnly: "Chỉ prompt",
      modePrompt: "Chỉ prompt",
      modeEdit: "Chỉnh sửa",
      modeAgent: "Agent",
      modePromptHint: "Hỏi nhanh, không schema.",
      modeEditHint: "Gợi ý SQL từ schema.",
      modeAgentHint: "Tự chạy khi bạn duyệt.",
      agentAutonomyLabel: "Quyền chạy",
      safeModeToggle: "Safe Mode",
        agentAutonomyReview: "Luôn duyệt",
      agentAutonomyReviewHint: "Hỏi trước khi chạy bất kỳ câu SQL nào.",
      agentAutonomySmart: "Thông minh",
      agentAutonomySmartHint: "Tự chạy câu đọc an toàn, hỏi trước khi ghi.",
      agentAutonomyFull: "Toàn quyền",
      agentAutonomyFullHint: "Tự chạy truy vấn đọc an toàn; thao tác ghi và đổi schema vẫn cần xác nhận.",
      thinkingToggleLabel: "Suy luận",
      thinkingToggleHint: "Hiện hoặc ẩn suy luận trực tiếp của agent",
      thinkingOn: "Bật",
      thinkingOff: "Tắt",
      autoProviderSwitchLabel: "Tự chuyển provider",
      newChatTitle: "Cuộc trò chuyện mới",
      reloadChatTitle: "Tải lại đoạn chat từ lịch sử đã lưu",
      modeNeedsSchemaHint: "Chế độ này cần bật chia sẻ schema trong AI Provider Settings.",
      openSettings: "Mở settings",
      hiddenModelsToggle: "Model bị ẩn",
      switchToPrompt: "Dùng chỉ prompt",
      historyTitle: "Lịch sử chat",
      historyEmpty: "Hãy hỏi AI để bắt đầu cuộc trò chuyện đầu tiên trong workspace này.",
      historyRenameTitle: "Đổi tên đoạn chat",
      placeholder: "Hỏi về DB này, yêu cầu SQL, hoặc mô tả thay đổi bạn muốn.",
      note: "Enter để gửi. Inspect để lấy ngữ cảnh.",
      generating: "Đang tạo...",
      cancelling: "Đang dừng...",
      cancelGeneration: "Dừng",
      generateBubble: "Hỏi AI",
      sqlConfirmWriteTitle: "Chạy SQL ghi dữ liệu?",
      sqlConfirmWriteBody: "AI agent muốn chạy câu lệnh làm thay đổi dữ liệu. Kiểm tra kỹ trước khi duyệt.",
      sqlConfirmHighRiskTitle: "Chạy SQL rủi ro cao?",
      sqlConfirmHighRiskBody: "Lượt chạy này có thể thay đổi cấu trúc DB và không thể hoàn tác. Xem kỹ từng câu lệnh.",
      sqlConfirmPreviewLabel: "SQL sẽ chạy",
      sqlConfirmRunLabel: "Chạy SQL",
      sqlConfirmCancelLabel: "Huỷ",
      sqlConfirmBatchLabel: "{count} câu lệnh trong lượt chạy này.",
      autonomyFullConfirmTitle: "Bật toàn quyền?",
      autonomyFullConfirmBody: "Agent sẽ tự chạy mọi câu SQL nó chuẩn bị mà không hỏi trước. Thao tác ghi và đổi schema vẫn sẽ hỏi xác nhận trước khi thực thi.",
      autonomyFullConfirmAllow: "Bật toàn quyền",
      promptIdeas: [
        {
          title: "Tạo bảng",
          prompt: "Tạo bảng users gồm id, name, email, role và created_at.",
        },
        {
          title: "Sửa schema",
          prompt: "Thêm cột last_login_at vào bảng users và backfill bằng CURRENT_TIMESTAMP.",
        },
        {
          title: "Viết query",
          prompt: "Viết query hiển thị top 10 users theo số lượng đơn hàng trong 30 ngày gần đây.",
        },
        {
          title: "Tối ưu query",
          prompt: "Tối ưu câu SQL này: SELECT * FROM orders WHERE DATE(created_at) = CURDATE()",
        },
        {
          title: "Sửa lỗi",
          prompt: "Sửa lỗi SQL này: SELECT * FRMO users",
        },
      ],
    },
    bubbleStates: {
      loadingInspectTitle: "Đang đọc ngữ cảnh đã chọn",
      loadingComposeTitle: "AI đang tạo một bong bóng mới",
      loadingInspectSubtitle: "Đang quét ngữ cảnh",
      loadingInspectPreview: "Đang xem phần bạn đã chọn, chuẩn bị lời giải thích và gợi ý an toàn hơn nếu phù hợp.",
      loadingComposePreview: "Đang xem schema, bám ngữ cảnh và soạn SQL...",
      readyInspectTitle: "Đã có phần giải thích ngữ cảnh",
      readySqlTitle: "Bong bóng SQL đã sẵn sàng",
      readyNoteTitle: "Ghi chú AI đã sẵn sàng",
      readyInspectSqlSubtitle: "Đã giải thích phần được chọn và đề xuất hướng chạy được",
      readyInspectNoteSubtitle: "Đã giải thích phần được chọn và gợi ý bước tiếp theo",
      readySqlSafeSubtitle: "Có vẻ an toàn để chèn",
      readySqlReviewSubtitle: "Xem lại trước khi chạy",
      readyOptimizeTitle: "SQL đã tối ưu",
      readyOptimizeSubtitle: "SQL đã được viết lại để chạy nhanh hơn",
      readyFixErrorTitle: "SQL đã sửa",
      readyFixErrorSubtitle: "Lỗi SQL đã được khắc phục",
      readyNoteSubtitle: "Chỉ có giải thích, chưa có SQL chạy được",
      errorTitle: "Không thể tạo bong bóng",
      errorSubtitle: "Yêu cầu AI thất bại",
      cancelledTitle: "Đã dừng yêu cầu",
      cancelledSubtitle: "Không còn request provider nào đang chạy",
      partialTitle: "Đã giữ lại tiến trình một phần",
      partialSubtitle: "Agent đã dừng trước khi tổng hợp câu trả lời cuối",
      selectSomethingError: "Hãy chọn một đoạn code hoặc chữ trên UI trước, rồi nhấn Enter khi orb AI đang ở chế độ inspect.",
      runSuccessTitle: "SQL đã chạy trong sandbox",
      runSuccessSandboxSubtitle: "Biên thực thi được bảo vệ",
      runSuccessDirectSubtitle: "Đã thực thi trực tiếp",
      runFailedTitle: "Chạy thất bại",
      runFailedSubtitle: "Sandbox đã dừng thực thi",
      askUserCustomAnswer: "Trả lời của bạn…",
      openedInWorkspaceTitle: "Đã mở trong workspace",
      openedInWorkspaceSubtitle: "Đã gửi sang tab workspace",
      openedInWorkspacePreview: "Mình đã mở cái này trong một tab workspace để bạn xem kết quả ở đó. Đoạn chat này vẫn ở đây để bạn hỏi tiếp.",
    },
    attachments: {
      attachButton: "Đính kèm tệp hoặc ảnh",
      imageUnsupported: "Model hiện tại không đọc được ảnh. Chỉ tệp văn bản được đính kèm.",
      removeAttachment: "Gỡ đính kèm",
      managerOpen: "Quản lý tệp đính kèm",
      managerTitle: "Tệp đính kèm",
      managerClose: "Đóng",
      managerFilterAll: "Tất cả",
      managerFilterImages: "Ảnh",
      managerFilterFiles: "Tệp",
      managerFiltersLabel: "Bộ lọc",
      managerStorageLabel: "Lưu trữ",
      managerEmpty: "Chưa có tệp đính kèm. Thả tệp vào ô nhập AI để đính kèm.",
      managerDeleteSelected: "Xoá mục đã chọn",
      managerDeleteAll: "Xoá tất cả",
      managerDeleteAllConfirm: "Xoá toàn bộ tệp đính kèm đã lưu? Hành động này không thể hoàn tác.",
      managerTotalSize: "Dung lượng",
      managerUsageHint: "Tệp đính kèm được lưu cục bộ và chiếm dung lượng đĩa. Xoá các mục cũ để giải phóng chỗ.",
    },
    imageViewer: {
      close: "Đóng trình xem ảnh",
      download: "Tải ảnh xuống",
      resetZoom: "Đặt lại độ phóng (100%)",
    },
    workspace: {
      switcherTitle: "Không gian làm việc",
      switcherHint: "Context theo DB đang mở; pin DB để cố định",
      rebindAction: "Chọn database",
      rebindLockedTitle: "Agent đang chạy — hãy đợi chạy xong hoặc hủy trước khi đổi database.",
      dbAuto: "Tự động",
      dbCurrentHint: "Đang mở trong Explorer",
      autoMode: "Tự động",
      newWorkspace: "+ Workspace mới",
      defaultName: "Workspace",
      renameAction: "Đổi tên",
      deleteAction: "Xóa",
      chatActionTitle: "Quản lý đoạn chat",
      chatActionCreate: "Tạo đoạn chat mới",
      chatActionAdd: "Thêm đoạn chat có sẵn",
      chatActionBack: "Quay lại",
      addChatsTitle: "Thêm đoạn chat vào workspace",
      addChatsConfirm: "Thêm vào workspace",
      importSearchPlaceholder: "Tìm theo tên hoặc từ khoá…",
      importEmpty: "Chưa có đoạn chat nào khác để thêm.",
      compactAction: "/compact — tóm tắt đoạn chat này vào context của workspace",
      compactRunning: "Đang nén context…",
      compactDoneTitle: "Đã nén context",
      compactDoneSubtitle: "Đã tóm tắt vào context của workspace này",
      compactNeedsWorkspace: "Hãy tạo một workspace chat trước để /compact có nơi lưu context.",
      compactEmpty: "Chưa có gì để nén — hãy hỏi trước đã.",
      contextBadge: "Context",
    },
  };
