import type { AIWorkspaceCopy } from "./types";

export const ZH_COPY: AIWorkspaceCopy = {
    bubbleMeta: {
      thinking: "思考中",
      sandboxRun: "沙箱运行",
      needsReview: "需要检查",
      blockedInsert: "已阻止插入",
      reviewBeforeRun: "运行前检查",
      ready: "就绪",
    },
    bubbleActions: {
      dragBubble: "拖动气泡",
      dragPointer: "把这条箭头拖到你希望 AI 解释的位置。双击可重置。",
      dismissBubble: "关闭气泡",
      detail: "详情",
      copy: "复制",
      insert: "插入",
      approveRun: "批准运行",
      retry: "重试",
    },
    modal: {
      kicker: "气泡详情",
      originalRequest: "原始请求",
      noRequest: "这个气泡没有记录到请求内容。",
      executionSummary: "执行摘要",
      assistantExplanation: "AI 解释",
      loadingExplanation: "AI 正在读取你指向的上下文并生成解释。",
      sql: "SQL",
      agenticNote: "Agentic 执行会一直保持锁定，直到你明确批准。",
      rewriteTitle: "重写这个气泡",
      rewriteHint: "写下你希望修改的内容，然后让 AI 生成新版本。",
      rewritePlaceholder: "例如：让它对 PostgreSQL 更安全、加入注释、拆分 DDL 和 DML，或更清晰地解释 joins。",
      rewriting: "重写中...",
      rewriteBubble: "重写气泡",
      running: "运行中...",
      approveAgenticRun: "批准 agentic 运行",
      reasoningLabel: "模型推理",
      reasoningShow: "显示推理",
      reasoningHide: "隐藏推理",
      agentStepsLabel: "Agent 步骤",
      agentActionPlan: "????",
      agentActionThink: "思考中",
      agentActionAskUser: "询问中",
      agentActionRememberTerm: "学习中",
      agentActionPreviewWrite: "预览变更",
      agentActionListTables: "列出表",
      agentActionDescribeTable: "查看结构",
      agentActionRunSql: "读取数据",
      agentActionFinish: "整理答复",
      agentStatusRunning: "运行中",
      agentStatusDone: "完成",
      agentStatusError: "需检查",
    },
    composer: {
      alertDismiss: "关闭",
      inspectOnTitle: "Inspect 模式已开启。选中文本后按 Enter。",
      inspectOffTitle: "打开 AI 侧边助手。使用 Inspect 从工作区获取上下文。",
      resizeHandleTitle: "拖动以调整 AI 面板宽度。双击可重置。",
      inspectHint: "选中内容后按 Enter。",
      capturedLabel: "已捕获",
      selectionReady: "已选中",
      kicker: "工作区 AI",
      title: "AI 助手",
      noDatabaseSelected: "未选择数据库",
      slashCommandsTitle: "命令",
      slashCommandsHint: "输入以筛选 · Enter 运行 · Esc 关闭",
      slashNoMatch: "没有匹配的命令",
      slashBackupDescription: "将当前数据库备份为 SQL/JSON 文件。",
      slashCompactDescription: "压缩当前对话，可附加说明。",
      noProvider: "没有可用 provider",
      tableOne: "张表",
      tableOther: "张表",
      schemaShared: "共享 schema",
      promptOnly: "仅提示词",
      modePrompt: "仅提示词",
      modeEdit: "编辑",
      modeAgent: "Agent",
      modePromptHint: "仅使用你的 prompt，不发送 schema 上下文。",
      modeEditHint: "读取当前 DB schema，给出 SQL 或修改建议，先由你审核。",
      modeAgentHint: "读取当前 DB schema，准备可执行 SQL，但仍需要你明确批准。",
      agentAutonomyLabel: "执行权限",
      agentAutonomyReview: "总是审阅",
      agentAutonomyReviewHint: "运行任何 SQL 前先问我。",
      agentAutonomySmart: "智能",
      agentAutonomySmartHint: "自动运行安全的读取查询，写入前询问。",
      agentAutonomyFull: "完全权限",
      agentAutonomyFullHint: "自动运行安全的只读查询；写入和架构更改仍需确认。",
      thinkingToggleLabel: "??",
      thinkingToggleHint: "????? agent ?????",
      thinkingOn: "?",
      thinkingOff: "?",
      autoProviderSwitchLabel: "自动切换提供者",
      newChatTitle: "新对话",
      reloadChatTitle: "从保存的历史重新加载对话",
      modeNeedsSchemaHint: "这个模式需要在 AI Provider Settings 中开启 schema sharing。",
      openSettings: "打开设置",
      hiddenModelsToggle: "已隐藏的模型",
      switchToPrompt: "改用提示词模式",
      historyTitle: "对话历史",
      historyEmpty: "先向 AI 发出一个请求，工作区里的第一段对话就会出现在这里。",
      historyRenameTitle: "重命名对话",
      placeholder: "询问当前数据库、请求 SQL，或描述你想做的改动。",
      note: "按 Enter 发送。使用 Inspect 从工作区捕获上下文。",
      generating: "生成中...",
      cancelling: "正在停止...",
      cancelGeneration: "停止",
      generateBubble: "询问 AI",
      sqlConfirmWriteTitle: "执行写入 SQL？",
      sqlConfirmWriteBody: "AI 代理想要运行会更改数据的语句。批准前请先检查。",
      sqlConfirmHighRiskTitle: "执行高风险 SQL？",
      sqlConfirmHighRiskBody: "此次运行可能进行破坏性架构更改。请仔细检查每条语句。",
      sqlConfirmPreviewLabel: "将执行的 SQL",
      sqlConfirmRunLabel: "执行 SQL",
      sqlConfirmCancelLabel: "取消",
      sqlConfirmBatchLabel: "本次运行包含 {count} 条语句。",
      autonomyFullConfirmTitle: "启用完全访问？",
      autonomyFullConfirmBody: "AI 代理将自动运行它准备的所有 SQL，不再事先询问。写入和架构操作在执行前仍会请求确认。",
      autonomyFullConfirmAllow: "启用完全访问",
      promptIdeas: [
        {
          title: "创建表",
          prompt: "创建一个 users 表，包含 id、name、email、role 和 created_at。",
        },
        {
          title: "修改 schema",
          prompt: "给 users 表增加 last_login_at 列，并用 CURRENT_TIMESTAMP 回填。",
        },
        {
          title: "编写查询",
          prompt: "编写一个查询，显示过去 30 天内按订单数排名前 10 的 users。",
        },
        {
          title: "优化查询",
          prompt: "优化这条 SQL：SELECT * FROM orders WHERE DATE(created_at) = CURDATE()",
        },
        {
          title: "修复错误",
          prompt: "修复这条 SQL 错误：SELECT * FRMO users",
        },
      ],
    },
    bubbleStates: {
      loadingInspectTitle: "正在读取你选中的上下文",
      loadingComposeTitle: "AI 正在生成一个新气泡",
      loadingInspectSubtitle: "正在扫描上下文",
      loadingInspectPreview: "正在查看你选中的内容，准备解释，并在合适时给出更安全的建议。",
      loadingComposePreview: "正在查看 schema、结合上下文并生成 SQL...",
      readyInspectTitle: "上下文解释已准备好",
      readySqlTitle: "SQL 气泡已准备好",
      readyNoteTitle: "AI 说明已准备好",
      readyInspectSqlSubtitle: "已解释选中内容并给出可执行建议",
      readyInspectNoteSubtitle: "已解释选中内容并建议下一步",
      readySqlSafeSubtitle: "看起来可以安全插入",
      readySqlReviewSubtitle: "运行前请检查",
      readyOptimizeTitle: "SQL 已优化",
      readyOptimizeSubtitle: "SQL 已重写以提升性能",
      readyFixErrorTitle: "SQL 已修复",
      readyFixErrorSubtitle: "SQL 错误已被纠正",
      readyNoteSubtitle: "只有解释，没有可运行的 SQL",
      errorTitle: "无法生成气泡",
      errorSubtitle: "AI 请求失败",
      cancelledTitle: "请求已停止",
      cancelledSubtitle: "当前没有仍在运行的 provider 请求",
      partialTitle: "已保留部分进度",
      partialSubtitle: "Agent 在生成最终答复前停止了",
      selectSomethingError: "请先选中一段代码或界面文本，然后在 AI orb 处于 inspect 模式时按 Enter。",
      runSuccessTitle: "SQL 已在沙箱中运行",
      runSuccessSandboxSubtitle: "受保护的执行边界",
      runSuccessDirectSubtitle: "已直接执行",
      runFailedTitle: "运行失败",
      runFailedSubtitle: "沙箱执行已停止",
      openedInWorkspaceTitle: "已在工作区打开",
      openedInWorkspaceSubtitle: "已发送到工作区标签页",
      openedInWorkspacePreview: "我已在工作区标签页中打开它，你可以在那里查看结果。此对话会保留以便继续提问。",
    },
    attachments: {
      attachButton: "附加文件或图片",
      imageUnsupported: "当前模型无法读取图片。仅附加了文本文件。",
      removeAttachment: "移除附件",
      managerOpen: "管理附件",
      managerTitle: "附件",
      managerClose: "关闭",
      managerFilterAll: "全部",
      managerFilterImages: "图片",
      managerFilterFiles: "文件",
      managerFiltersLabel: "筛选",
      managerStorageLabel: "存储",
      managerEmpty: "暂无附件。将文件拖入 AI 输入框即可附加。",
      managerDeleteSelected: "删除所选",
      managerDeleteAll: "全部删除",
      managerDeleteAllConfirm: "删除所有已存储的附件？此操作无法撤销。",
      managerTotalSize: "总大小",
      managerUsageHint: "附件存储在本地并占用磁盘空间。删除旧附件可释放空间。",
    },
    imageViewer: {
      close: "关闭查看器",
      download: "下载图片",
      resetZoom: "重置缩放 (100%)",
    },
    workspace: {
      switcherTitle: "聊天工作区",
      switcherHint: "上下文跟随当前打开的数据库；固定以锁定。",
      rebindAction: "选择数据库",
      rebindLockedTitle: "Agent 正在运行 — 请等待其完成或取消后再切换数据库。",
      dbAuto: "自动",
      dbCurrentHint: "资源管理器中已打开",
      autoMode: "自动",
      newWorkspace: "+ 新建工作区",
      defaultName: "工作区",
      renameAction: "重命名",
      deleteAction: "删除",
      chatActionTitle: "管理聊天",
      chatActionCreate: "新建聊天",
      chatActionAdd: "添加现有聊天",
      chatActionBack: "返回",
      addChatsTitle: "向工作区添加聊天",
      addChatsConfirm: "添加到工作区",
      importSearchPlaceholder: "按名称或关键词搜索…",
      importEmpty: "暂无其他可添加的聊天。",
      compactAction: "/compact — 将此聊天压缩为工作区上下文",
      compactRunning: "正在压缩上下文…",
      compactDoneTitle: "上下文已压缩",
      compactDoneSubtitle: "已摘要保存到此工作区的上下文",
      compactNeedsWorkspace: "请先创建聊天工作区，/compact 才有地方保存上下文。",
      compactEmpty: "暂无可压缩内容 — 先提问吧。",
      contextBadge: "上下文",
    },
  };
