import type { DatabaseType } from "../../types";
import {
  buildDbEntry,
  ENGINE_EXTRA_FIELDS,
  type DbEntry,
} from "./engine-registry-shared";

export type {
  ConnectionEngineMode,
  ConnectionFieldMode,
  PasswordKind,
  LocalBootstrapStatus,
  EngineExtraFieldType,
  EngineExtraField,
  DbEntry,
} from "./engine-registry-shared";

export const DEFAULT_CONNECT_ENGINE: DatabaseType = "mysql";
export const DEFAULT_BOOTSTRAP_ENGINE: DatabaseType = "postgresql";

export const ALL_DATABASES: DbEntry[] = [
  buildDbEntry({
    key: "mysql",
    abbr: "Ms",
    label: "MySQL",
    color: "#c0392b",
    supported: true,
    connectionMode: "network",
    defaultPort: 3306,
    supportsSsl: true,
    localBootstrap: "ready",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "mariadb",
    abbr: "Mr",
    label: "MariaDB",
    color: "#6c7a89",
    supported: true,
    connectionMode: "network",
    defaultPort: 3306,
    supportsSsl: true,
    localBootstrap: "ready",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "sqlite",
    abbr: "Sl",
    label: "SQLite",
    color: "#3498db",
    supported: true,
    connectionMode: "file",
    supportsSsl: false,
    localBootstrap: "ready",
    isFile: true,
    fieldProfile: "sqliteFile",
  }),
  buildDbEntry({
    key: "duckdb",
    abbr: "Du",
    label: "DuckDB",
    color: "#2c3e50",
    supported: true,
    connectionMode: "file",
    supportsSsl: false,
    localBootstrap: "none",
    isFile: true,
    fieldProfile: "duckdbFile",
    extraFields: ENGINE_EXTRA_FIELDS.duckdb,
  }),
  buildDbEntry({
    key: "cassandra",
    abbr: "Cs",
    label: "Cassandra",
    color: "#27ae60",
    supported: true,
    connectionMode: "network",
    defaultPort: 9042,
    supportsSsl: false,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "cassandra",
    extraFields: ENGINE_EXTRA_FIELDS.cassandra,
  }),
  buildDbEntry({
    key: "cockroachdb",
    abbr: "Cr",
    label: "CockroachDB",
    color: "#3ddc84",
    supported: true,
    connectionMode: "network",
    defaultPort: 26257,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "snowflake",
    abbr: "Nf",
    label: "Snowflake",
    color: "#29b5e8",
    supported: true,
    connectionMode: "network",
    defaultPort: 443,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "",
    hostPlaceholder: "account.region.snowflakecomputing.com",
    fieldProfile: "snowflake",
    extraFields: ENGINE_EXTRA_FIELDS.snowflake,
  }),
  buildDbEntry({
    key: "postgresql",
    abbr: "Pg",
    label: "PostgreSQL",
    color: "#336791",
    supported: true,
    connectionMode: "network",
    defaultPort: 5432,
    supportsSsl: true,
    localBootstrap: "ready",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "greenplum",
    abbr: "Gp",
    label: "Greenplum",
    color: "#2ecc71",
    supported: true,
    connectionMode: "network",
    defaultPort: 5432,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "redshift",
    abbr: "Rs",
    label: "Amazon Redshift",
    color: "#16a085",
    supported: true,
    connectionMode: "network",
    defaultPort: 5439,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "",
    hostPlaceholder: "cluster.region.redshift.amazonaws.com",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "mssql",
    abbr: "Ss",
    label: "SQL Server",
    color: "#7f8c8d",
    supported: true,
    connectionMode: "network",
    defaultPort: 1433,
    supportsSsl: true,
    localBootstrap: "planned",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
    extraFields: ENGINE_EXTRA_FIELDS.mssql,
  }),
  buildDbEntry({
    key: "redis",
    abbr: "Re",
    label: "Redis",
    color: "#e74c3c",
    supported: true,
    connectionMode: "network",
    defaultPort: 6379,
    supportsSsl: false,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "optionalUserSecretNoDatabase",
    extraFields: ENGINE_EXTRA_FIELDS.redis,
  }),
  buildDbEntry({
    key: "mongodb",
    abbr: "Mg",
    label: "MongoDB",
    color: "#27ae60",
    supported: true,
    connectionMode: "network",
    defaultPort: 27017,
    supportsSsl: true,
    localBootstrap: "planned",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "optionalUserSecretWithDatabase",
    extraFields: ENGINE_EXTRA_FIELDS.mongodb,
  }),
  buildDbEntry({
    key: "vertica",
    abbr: "Ve",
    label: "Vertica",
    color: "#95a5a6",
    supported: true,
    connectionMode: "network",
    defaultPort: 5433,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "clickhouse",
    abbr: "Ch",
    label: "ClickHouse",
    color: "#5b9bd5",
    supported: true,
    connectionMode: "network",
    defaultPort: 8123,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "127.0.0.1",
    hostPlaceholder: "127.0.0.1",
    fieldProfile: "standardSql",
  }),
  buildDbEntry({
    key: "bigquery",
    abbr: "Bq",
    label: "BigQuery",
    color: "#8e44ad",
    supported: true,
    connectionMode: "network",
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "",
    hostPlaceholder: "bigquery.googleapis.com",
    fieldProfile: "tokenNoDatabase",
    extraFields: ENGINE_EXTRA_FIELDS.bigquery,
  }),
  buildDbEntry({
    key: "libsql",
    abbr: "Ls",
    label: "LibSQL",
    color: "#2ecc71",
    supported: true,
    connectionMode: "network",
    defaultPort: 8080,
    supportsSsl: false,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "",
    hostPlaceholder: "your-db.turso.io",
    fieldProfile: "tokenWithDatabase",
  }),
  buildDbEntry({
    key: "cloudflare_d1",
    abbr: "D1",
    label: "Cloudflare D1",
    color: "#f39c12",
    supported: true,
    connectionMode: "network",
    defaultPort: 443,
    supportsSsl: true,
    localBootstrap: "none",
    isFile: false,
    defaultHost: "",
    hostPlaceholder: "api.cloudflare.com",
    fieldProfile: "tokenNoDatabase",
    extraFields: ENGINE_EXTRA_FIELDS.cloudflareD1,
  }),
];

const DATABASE_MAP = new Map<DatabaseType, DbEntry>(
  ALL_DATABASES.map((engine) => [engine.key, engine]),
);

export const LOCAL_BOOTSTRAP_READY = new Set<DatabaseType>(
  ALL_DATABASES.filter((engine) => engine.localBootstrap === "ready").map((engine) => engine.key),
);

export const LOCAL_BOOTSTRAP_PLANNED = new Set<DatabaseType>(
  ALL_DATABASES.filter((engine) => engine.localBootstrap === "planned").map((engine) => engine.key),
);

export function getDatabaseEngine(dbType?: DatabaseType | string | null): DbEntry | null {
  if (!dbType) return null;
  return DATABASE_MAP.get(dbType as DatabaseType) ?? null;
}

export function getSuggestedUsernamePlaceholder(dbType?: DatabaseType | string | null) {
  const engine = getDatabaseEngine(dbType);
  return engine?.usernamePlaceholder || "db_username";
}
