/**
 * "Generate test rows" dialog — asks for a row count and an optional hint,
 * generates INSERT values client-side from the column types, and stages them
 * in the change-tracking queue so the existing review modal gates the write.
 *
 * Used from the DataGrid toolbar (columns already resolved) and from the
 * sidebar table context menu (columns fetched on open via getTableStructure).
 */

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Dices, Loader2, X } from "lucide-react";
import { useI18n } from "../../i18n";
import { emitAppToast } from "../../utils/app-toast";
import { useQueryStore } from "../../stores/queryStore";
import type { ColumnDetail } from "../../types";
import type { DatabaseType } from "../../types/database";
import {
  generateTestRows,
  isAutoGeneratedColumn,
  SEED_ROW_DEFAULT,
  SEED_ROW_MAX,
  SEED_ROW_MIN,
} from "../../utils/test-row-generator";
import { stageGeneratedRows } from "./stage-seed-rows";
import { getSeedRowsCopy } from "./seed-rows-copy";

export interface GenerateTestRowsDialogProps {
  /** Required when `columns` is omitted — the dialog fetches the structure. */
  connectionId?: string;
  /** Qualified table name — must match the DataGrid's `tableName` prop so the
   *  staged changes land in that grid's review modal. */
  tableName: string;
  database?: string;
  dbType?: DatabaseType;
  /** Pre-resolved columns (grid path). Omit to fetch via getTableStructure. */
  columns?: ColumnDetail[];
  onClose: () => void;
  /** Called after rows are staged — the sidebar uses it to open the table tab
   *  so the review modal has a grid to render in. */
  onStaged?: () => void;
}

export function GenerateTestRowsDialog({
  connectionId,
  tableName,
  database,
  dbType,
  columns: providedColumns,
  onClose,
  onStaged,
}: GenerateTestRowsDialogProps) {
  const { language } = useI18n();
  const copy = getSeedRowsCopy(language);
  const getTableStructure = useQueryStore((state) => state.getTableStructure);

  const [countInput, setCountInput] = useState(String(SEED_ROW_DEFAULT));
  const [hint, setHint] = useState("");
  const [columns, setColumns] = useState<ColumnDetail[] | null>(providedColumns ?? null);
  const [loadError, setLoadError] = useState<string | null>(null);

  // Sidebar path: no resolved columns at hand — fetch the structure once.
  useEffect(() => {
    if (providedColumns || !connectionId) return;
    let cancelled = false;
    getTableStructure(connectionId, tableName, database)
      .then((structure) => {
        if (!cancelled) setColumns(structure.columns);
      })
      .catch((error) => {
        if (!cancelled) {
          setLoadError(error instanceof Error ? error.message : String(error));
        }
      });
    return () => {
      cancelled = true;
    };
  }, [connectionId, database, getTableStructure, providedColumns, tableName]);

  useEffect(() => {
    const handler = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  const seedableCount = columns
    ? columns.filter((column) => !isAutoGeneratedColumn(column)).length
    : 0;
  const parsedCount = Number(countInput);
  const countValid =
    Number.isInteger(parsedCount) && parsedCount >= SEED_ROW_MIN && parsedCount <= SEED_ROW_MAX;

  const handleGenerate = () => {
    if (!columns || !countValid || seedableCount === 0) return;
    const rows = generateTestRows(columns, parsedCount, hint.trim() || undefined);
    const staged = stageGeneratedRows({ connectionId, tableName, database, dbType, columns, rows });
    if (staged === 0) return;
    onStaged?.();
    emitAppToast({
      title: copy.stagedToast(staged, tableName),
      tone: "success",
    });
    onClose();
  };

  return createPortal(
    <div className="qs-overlay" role="presentation" onClick={onClose}>
      <div
        className="qs-panel data-import-panel"
        role="dialog"
        aria-label={copy.title}
        onClick={(event) => event.stopPropagation()}
      >
        <div className="qs-input-row">
          <strong>
            <Dices size={14} className="inline-block mr-1" />
            {copy.title} — {tableName}
          </strong>
          <button type="button" className="qs-clear-btn" aria-label="Close" onClick={onClose}>
            <X size={14} />
          </button>
        </div>

        {columns === null && !loadError ? (
          <div className="qs-empty">
            <Loader2 size={14} className="animate-spin inline-block mr-1" />
            {copy.loading}
          </div>
        ) : loadError ? (
          <div className="qs-empty">
            {copy.loadFailed} {loadError}
          </div>
        ) : seedableCount === 0 ? (
          <div className="qs-empty">{copy.noColumns}</div>
        ) : (
          <>
            <div className="schema-diff-selects">
              <label className="datagrid-settings-label">{copy.rowCount}</label>
              <input
                type="number"
                min={SEED_ROW_MIN}
                max={SEED_ROW_MAX}
                value={countInput}
                onChange={(event) => setCountInput(event.target.value)}
                aria-label={copy.rowCount}
                autoFocus
              />
            </div>
            <div className="schema-diff-selects">
              <label className="datagrid-settings-label">{copy.hintLabel}</label>
              <input
                type="text"
                value={hint}
                onChange={(event) => setHint(event.target.value)}
                placeholder={copy.hintPlaceholder}
                aria-label={copy.hintLabel}
              />
            </div>
            <div className="schema-diff-selects">
              <button
                type="button"
                className="global-search-mode active"
                disabled={!countValid}
                onClick={handleGenerate}
              >
                <Dices size={13} /> {copy.generate}
              </button>
              <button type="button" className="global-search-mode" onClick={onClose}>
                {copy.cancel}
              </button>
            </div>
          </>
        )}
      </div>
    </div>,
    document.body,
  );
}
