/**
 * useInsertColumnPlan — shared column-resolution logic for INSERT dialog.
 *
 * Replaces the duplicated logic that appeared in 3 places in DataGrid.tsx:
 * handleDuplicateRow, handleDuplicateRowByIndex, and analyzeInsertPlan.
 *
 * Takes `structureColumns` and optionally a `sourceRow` (for duplicate-from-existing
 * scenarios). Returns the column plan: which columns need user prompts and what
 * default values to pre-fill.
 */

import { useMemo } from "react";
import type { ColumnDetail } from "../../../types/database";

export interface InsertColumnPlan {
  /** Columns the user must fill in (PK conflicts, non-nullable empty cells) */
  promptColumns: ColumnDetail[];
  /** Pre-filled values: [columnName, value][] for non-prompt columns */
  baseValues: [string, unknown][];
}

function generateFallbackUuid(): string {
  if (typeof crypto !== "undefined" && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  const hex = (n: number) => Math.random().toString(16).slice(2, n + 2);
  return `${hex(8)}-${hex(4)}-${hex(4)}-${hex(4)}-${hex(12)}`;
}

export function computeColumnPlan(
  columns: ColumnDetail[],
  sourceRow: unknown[] | null,
): InsertColumnPlan {
  const promptColumns: ColumnDetail[] = [];
  const baseValues: [string, unknown][] = [];

  for (const col of columns) {
    const colType = (col.column_type || col.data_type || "").toLowerCase();
    const extra = (col.extra || "").toLowerCase();
    const defaultVal = (col.default_value || "").trim();
    const defaultLower = defaultVal.toLowerCase();
    const hasDatabaseDefault = defaultVal.length > 0;

    const isUuidColumn =
      colType.includes("uuid") || colType.includes("uniqueidentifier");

    const isAutoGeneratedColumn =
      colType.includes("serial") ||
      colType.includes("identity") ||
      extra.includes("auto_increment") ||
      extra.includes("generated") ||
      defaultLower.includes("nextval(") ||
      defaultLower.includes("gen_random_uuid(") ||
      defaultLower.includes("uuid_generate_v4(") ||
      defaultLower.includes("identity");

    if (col.is_primary_key) {
      if (isUuidColumn && !hasDatabaseDefault && !isAutoGeneratedColumn) {
        // UUID PK without DB default → generate one
        baseValues.push([col.name, generateFallbackUuid()]);
      } else if (isAutoGeneratedColumn || hasDatabaseDefault) {
        // PK has DB-side value → skip
        continue;
      } else {
        // PK needs new value → prompt, copy from source if available
        const colIdx = columns.indexOf(col);
        const sourceValue = sourceRow ? sourceRow[colIdx] : null;
        promptColumns.push(col);
        baseValues.push([col.name, sourceValue ?? null]);
      }
      continue;
    }

    if (isAutoGeneratedColumn || hasDatabaseDefault) {
      // Column has DB-side default → skip
      continue;
    }

    if (sourceRow) {
      // Duplicate-from-existing path: pre-fill from source row
      const colIdx = columns.indexOf(col);
      const sourceValue = sourceRow[colIdx];

      if (!col.is_nullable && (sourceValue === null || sourceValue === "")) {
        // Non-nullable but source is null/empty → prompt
        promptColumns.push(col);
        baseValues.push([col.name, sourceValue ?? null]);
      } else {
        baseValues.push([col.name, sourceValue ?? null]);
      }
    } else {
      // New-row path: nulls for nullable, prompts for non-nullable
      if (!col.is_nullable) {
        promptColumns.push(col);
        baseValues.push([col.name, null]);
      } else {
        baseValues.push([col.name, null]);
      }
    }
  }

  return { promptColumns, baseValues };
}

/** Non-hook utility — used directly inside other callbacks (e.g. handleInsertRow) */
export function computeNewRowPlan(columns: ColumnDetail[]): InsertColumnPlan {
  return computeColumnPlan(columns, null);
}

/** For "duplicate from existing row" scenarios (handles handleDuplicateRow + handleDuplicateRowByIndex) */
export function useDuplicateColumnPlan(
  structureColumns: ColumnDetail[],
  sourceRow: unknown[] | null,
): InsertColumnPlan {
  return useMemo(
    () => computeColumnPlan(structureColumns, sourceRow),
    [structureColumns, sourceRow],
  );
}
