/** SQL keyword suggestions for the explorer search box: clause, join,
 *  DDL, aggregate, and window-function vocabulary filtered by the typed
 *  prefix. Kept data-only so the list is easy to extend. */
const SIDEBAR_SQL_KEYWORDS = [
  // Clauses
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "IN",
  "NOT IN",
  "BETWEEN",
  "LIKE",
  "ILIKE",
  "ORDER BY",
  "GROUP BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "SELECT",
  "FROM",
  "JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "INNER JOIN",
  "FULL OUTER JOIN",
  "CROSS JOIN",
  "ON",
  "USING",
  "INSERT INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE FROM",
  "CREATE TABLE",
  "ALTER TABLE",
  "DROP TABLE",
  "TRUNCATE",
  "CREATE INDEX",
  "DROP INDEX",
  "DISTINCT",
  "ALL",
  "AS",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "UNION",
  "UNION ALL",
  "EXCEPT",
  "INTERSECT",
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "COALESCE",
  "NULLIF",
  "NOW()",
  "CURRENT_DATE",
  "CURRENT_TIMESTAMP",
  "TRUE",
  "FALSE",
  "NULL",
  // Aggregate with ALL
  "COUNT(*)",
  "COUNT(DISTINCT",
  "SUM(",
  "AVG(",
  "MAX(",
  "MIN(",
  // Window-like
  "OVER",
  "PARTITION BY",
  "ROW_NUMBER()",
  "RANK()",
  "DENSE_RANK()",
  "LEAD(",
  "LAG(",
  "FIRST_VALUE(",
  "LAST_VALUE(",
];

export function getSidebarAutocompleteItems(search: string): string[] {
  if (!search.trim()) return [];
  const needle = search.toLowerCase();
  return SIDEBAR_SQL_KEYWORDS.filter((kw) => kw.toLowerCase().includes(needle)).slice(0, 12);
}
