/**
 * Auto database documentation generator (Group-2 Feature 9, Phase 1).
 *
 * Pure emitters: normalized structure data (tables, columns, indexes, FKs)
 * in → deterministic Markdown or standalone HTML out. The same schema always
 * produces byte-identical output apart from the explicitly passed timestamp.
 */

export interface DocColumn {
  name: string;
  data_type: string;
  is_nullable: boolean;
  is_primary_key: boolean;
  default_value?: string;
  comment?: string;
}

export interface DocIndex {
  name: string;
  columns: string[];
  is_unique: boolean;
}

export interface DocForeignKey {
  name: string;
  column: string;
  referenced_table: string;
  referenced_column: string;
  on_delete?: string;
  on_update?: string;
}

export interface DocTable {
  name: string;
  columns: DocColumn[];
  indexes: DocIndex[];
  foreignKeys: DocForeignKey[];
  rowCount?: number;
}

export interface DocDatabase {
  name: string;
  tables: DocTable[];
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapePipe(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function columnMarkdown(column: DocColumn): string {
  const parts = [
    `\`${escapePipe(column.name)}\``,
    escapePipe(column.data_type),
    column.is_nullable ? "yes" : "no",
    column.is_primary_key ? "🔑 PK" : "",
    column.default_value !== undefined && column.default_value !== "" ? `\`${escapePipe(column.default_value)}\`` : "",
    column.comment ? escapePipe(column.comment) : "",
  ];
  return `| ${parts.join(" | ")} |`;
}

/** Emit the schema book as Markdown (source of truth for the HTML variant). */
export function generateMarkdownDocs(database: DocDatabase, generatedAt?: string): string {
  const lines: string[] = [];
  const timestamp = generatedAt ?? new Date().toISOString();
  lines.push(`# ${database.name} — schema documentation`);
  lines.push("");
  lines.push(`_Generated by TableR on ${timestamp}. ${database.tables.length} table(s)._`);
  lines.push("");

  // Relationship summary up front — the fastest way to grasp the schema.
  const relationships = database.tables.flatMap((table) =>
    table.foreignKeys.map((fk) => ({
      from: `${table.name}.${fk.column}`,
      to: `${fk.referenced_table}.${fk.referenced_column}`,
      onDelete: fk.on_delete,
    })),
  );
  if (relationships.length > 0) {
    lines.push("## Relationships");
    lines.push("");
    lines.push("| From | To | On delete |");
    lines.push("| --- | --- | --- |");
    for (const relationship of relationships) {
      lines.push(`| \`${relationship.from}\` | \`${relationship.to}\` | ${relationship.onDelete ?? "—"} |`);
    }
    lines.push("");
  }

  lines.push("## Table of contents");
  lines.push("");
  for (const table of database.tables) {
    lines.push(`- [${table.name}](#${table.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")})`);
  }
  lines.push("");

  for (const table of database.tables) {
    lines.push(`## ${table.name}`);
    lines.push("");
    if (table.rowCount !== undefined) {
      lines.push(`~${table.rowCount.toLocaleString("en-US")} rows.`);
      lines.push("");
    }

    lines.push("| Column | Type | Nullable | Key | Default | Comment |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const column of table.columns) {
      lines.push(columnMarkdown(column));
    }
    lines.push("");

    if (table.indexes.length > 0) {
      lines.push("### Indexes");
      lines.push("");
      for (const index of table.indexes) {
        const unique = index.is_unique ? "UNIQUE " : "";
        lines.push(`- ${unique}\`${index.name}\` (${index.columns.map((c) => `\`${c}\``).join(", ")})`);
      }
      lines.push("");
    }

    if (table.foreignKeys.length > 0) {
      lines.push("### Foreign keys");
      lines.push("");
      for (const fk of table.foreignKeys) {
        lines.push(
          `- \`${fk.name}\`: \`${fk.column}\` → \`${fk.referenced_table}.${fk.referenced_column}\``
            + (fk.on_delete ? ` ON DELETE ${fk.on_delete}` : "")
            + (fk.on_update ? ` ON UPDATE ${fk.on_update}` : ""),
        );
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

const HTML_STYLES = [
  "body { font-family: system-ui, -apple-system, 'Segoe UI', sans-serif; margin: 2rem auto; max-width: 60rem; padding: 0 1rem; color: #1f2937; }",
  "h1 { border-bottom: 2px solid #2563eb; padding-bottom: .4rem; }",
  "h2 { border-bottom: 1px solid #d1d5db; padding-bottom: .3rem; margin-top: 2.2rem; }",
  "table { border-collapse: collapse; width: 100%; margin: .8rem 0; font-size: .92rem; }",
  "th, td { border: 1px solid #d1d5db; padding: .35rem .6rem; text-align: left; vertical-align: top; }",
  "th { background: #f3f4f6; }",
  "code { background: #f3f4f6; padding: .1rem .3rem; border-radius: 3px; font-size: .88em; }",
  ".meta { color: #6b7280; font-size: .9rem; }",
  "@media print { h2 { page-break-after: avoid; } table { page-break-inside: avoid; } }",
].join("\n    ");

function columnHtml(column: DocColumn): string {
  const key = column.is_primary_key ? "🔑 PK" : "";
  const def = column.default_value !== undefined && column.default_value !== ""
    ? `<code>${escapeHtml(column.default_value)}</code>`
    : "";
  const comment = column.comment ? escapeHtml(column.comment) : "";
  return `      <tr><td><code>${escapeHtml(column.name)}</code></td><td>${escapeHtml(column.data_type)}</td>`
    + `<td>${column.is_nullable ? "yes" : "no"}</td><td>${key}</td><td>${def}</td><td>${comment}</td></tr>`;
}

/** Emit the schema book as a standalone, printable HTML file. */
export function generateHtmlDocs(database: DocDatabase, generatedAt?: string): string {
  const timestamp = generatedAt ?? new Date().toISOString();
  const sections = database.tables.map((table) => {
    const rows = table.columns.map(columnHtml).join("\n");
    const rowCount = table.rowCount !== undefined
      ? `<p class="meta">~${table.rowCount.toLocaleString("en-US")} rows.</p>`
      : "";
    const indexes = table.indexes.length > 0
      ? `<h3>Indexes</h3><ul>${table.indexes.map((index) =>
          `<li>${index.is_unique ? "UNIQUE " : ""}<code>${escapeHtml(index.name)}</code> `
            + `(${index.columns.map((c) => `<code>${escapeHtml(c)}</code>`).join(", ")})</li>`).join("")}</ul>`
      : "";
    const fks = table.foreignKeys.length > 0
      ? `<h3>Foreign keys</h3><ul>${table.foreignKeys.map((fk) =>
          `<li><code>${escapeHtml(fk.column)}</code> → `
            + `<code>${escapeHtml(fk.referenced_table)}.${escapeHtml(fk.referenced_column)}</code>`
            + (fk.on_delete ? ` ON DELETE ${escapeHtml(fk.on_delete)}` : "")
            + (fk.on_update ? ` ON UPDATE ${escapeHtml(fk.on_update)}` : "") + "</li>").join("")}</ul>`
      : "";
    const heading = `  <section id="${escapeHtml(table.name)}">\n    <h2>${escapeHtml(table.name)}</h2>\n    ${rowCount}`;
    const tableHtml = `    <table>\n      <thead><tr><th>Column</th><th>Type</th><th>Nullable</th><th>Key</th><th>Default</th><th>Comment</th></tr></thead>`
      + `\n      <tbody>\n${rows}\n      </tbody>\n    </table>`;
    return `${heading}\n${tableHtml}\n    ${indexes}\n    ${fks}\n  </section>`;
  }).join("\n");

  const toc = database.tables
    .map((table) => `        <li><a href="#${escapeHtml(table.name)}">${escapeHtml(table.name)}</a></li>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(database.name)} — schema documentation</title>
  <style>
    ${HTML_STYLES}
  </style>
</head>
<body>
  <h1>${escapeHtml(database.name)} — schema documentation</h1>
  <p class="meta">Generated by TableR on ${escapeHtml(timestamp)}. ${database.tables.length} table(s).</p>
  <h2>Contents</h2>
  <ul>
${toc}
  </ul>
${sections}
</body>
</html>
`;
}
