import type { DatabaseType } from "../types/database";

export interface SqlFunctionSignature {
  /** e.g. "substring(text, from [, count])" — shown as completion detail. */
  readonly signature: string;
  /** One-line description shown as completion documentation. */
  readonly doc?: string;
}

export interface SqlCompletionSet {
  readonly keywords: readonly string[];
  readonly functions: readonly string[];
  readonly operators: readonly string[];
  /** Signature lookup for `functions` entries, keyed by lowercase name.
   *  Dialect entries override the common map. */
  readonly functionSignatures: Readonly<Record<string, SqlFunctionSignature>>;
}

import {
  BASE_KEYWORDS,
  COMMON_FUNCTIONS,
  DB_SPECIFIC_FUNCTIONS,
  DB_SPECIFIC_KEYWORDS,
  OPERATORS,
} from "./sql-completions-data";

/**
 * Database types supported by the completion engine.
 */
const DATABASE_TYPES: readonly DatabaseType[] = [
  "mysql",
  "mariadb",
  "sqlite",
  "duckdb",
  "cassandra",
  "cockroachdb",
  "snowflake",
  "postgresql",
  "greenplum",
  "redshift",
  "mssql",
  "redis",
  "mongodb",
  "vertica",
  "clickhouse",
  "bigquery",
  "libsql",
  "cloudflare_d1",
  "oracle",
];

/**
 * Signatures for the cross-dialect function vocabulary (COMMON_FUNCTIONS).
 * Keys are lowercase; lookup falls back to this map when a dialect has no
 * override. Entries intentionally cover only real callable functions — the
 * keyword-shaped entries in COMMON_FUNCTIONS (CASE, UNION, …) get none.
 */
const COMMON_FUNCTION_SIGNATURES: Record<string, SqlFunctionSignature> = {
  // Aggregate
  count: { signature: "count(expr | *)", doc: "Number of rows / non-null values" },
  "count(*)": { signature: "count(*)", doc: "Number of rows" },
  sum: { signature: "sum(expr)", doc: "Total of non-null values" },
  avg: { signature: "avg(expr)", doc: "Mean of non-null values" },
  min: { signature: "min(expr)", doc: "Smallest value" },
  max: { signature: "max(expr)", doc: "Largest value" },
  array_agg: { signature: "array_agg(expr)", doc: "Aggregate values into an array" },
  string_agg: {
    signature: "string_agg(expr, delimiter)",
    doc: "Concatenate values with a delimiter",
  },
  listagg: { signature: "listagg(expr, delimiter)", doc: "Concatenate values with a delimiter" },
  group_concat: { signature: "group_concat(expr [, sep])", doc: "Concatenate group values" },
  grouping: { signature: "grouping(expr)", doc: "Distinguish super-aggregate rows" },
  // Numeric
  abs: { signature: "abs(n)", doc: "Absolute value" },
  round: { signature: "round(n [, digits])", doc: "Round to nearest value" },
  floor: { signature: "floor(n)", doc: "Largest integer <= n" },
  ceil: { signature: "ceil(n)", doc: "Smallest integer >= n" },
  ceiling: { signature: "ceiling(n)", doc: "Smallest integer >= n" },
  mod: { signature: "mod(a, b)", doc: "Remainder of a / b" },
  power: { signature: "power(base, exp)", doc: "base raised to exp" },
  sqrt: { signature: "sqrt(n)", doc: "Square root" },
  ln: { signature: "ln(n)", doc: "Natural logarithm" },
  log: { signature: "log(n) / log(base, n)", doc: "Logarithm" },
  log10: { signature: "log10(n)", doc: "Base-10 logarithm" },
  log2: { signature: "log2(n)", doc: "Base-2 logarithm" },
  exp: { signature: "exp(n)", doc: "e raised to n" },
  sign: { signature: "sign(n)", doc: "-1, 0 or 1" },
  trunc: { signature: "trunc(n [, digits])", doc: "Truncate toward zero" },
  random: { signature: "random()", doc: "Random value in [0, 1)" },
  rand: { signature: "rand([seed])", doc: "Random value in [0, 1)" },
  // String
  concat: { signature: "concat(a, b, …)", doc: "Concatenate strings" },
  concat_ws: { signature: "concat_ws(sep, a, b, …)", doc: "Concatenate with separator" },
  substring: { signature: "substring(str, from [, count])", doc: "Extract a substring" },
  substr: { signature: "substr(str, from [, count])", doc: "Extract a substring" },
  length: { signature: "length(str)", doc: "String length" },
  len: { signature: "len(str)", doc: "String length" },
  char_length: { signature: "char_length(str)", doc: "String length in characters" },
  upper: { signature: "upper(str)", doc: "Uppercase" },
  lower: { signature: "lower(str)", doc: "Lowercase" },
  trim: { signature: "trim([chars FROM] str)", doc: "Strip leading/trailing chars" },
  ltrim: { signature: "ltrim(str [, chars])", doc: "Strip leading chars" },
  rtrim: { signature: "rtrim(str [, chars])", doc: "Strip trailing chars" },
  lpad: { signature: "lpad(str, len [, fill])", doc: "Left-pad to length" },
  rpad: { signature: "rpad(str, len [, fill])", doc: "Right-pad to length" },
  replace: { signature: "replace(str, from, to)", doc: "Replace occurrences" },
  reverse: { signature: "reverse(str)", doc: "Reverse a string" },
  left: { signature: "left(str, n)", doc: "First n characters" },
  right: { signature: "right(str, n)", doc: "Last n characters" },
  position: { signature: "position(needle IN str)", doc: "Index of substring" },
  strpos: { signature: "strpos(str, needle)", doc: "Index of substring" },
  instr: { signature: "instr(str, needle)", doc: "Index of substring" },
  regexp_replace: {
    signature: "regexp_replace(str, pattern, repl [, flags])",
    doc: "Regex replace",
  },
  split_part: { signature: "split_part(str, delim, n)", doc: "Nth part of a split string" },
  regexp_substr: { signature: "regexp_substr(str, pattern)", doc: "Substring matching a regex" },
  translate: { signature: "translate(str, from, to)", doc: "Map characters one-to-one" },
  initcap: { signature: "initcap(str)", doc: "Capitalize each word" },
  ascii: { signature: "ascii(char)", doc: "Character code" },
  char: { signature: "char(code)", doc: "Character for a code" },
  soundex: { signature: "soundex(str)", doc: "Phonetic code" },
  difference: { signature: "difference(a, b)", doc: "Soundex similarity (0–4)" },
  quote_ident: { signature: "quote_ident(str)", doc: "Quote as an identifier" },
  quote_literal: { signature: "quote_literal(str)", doc: "Quote as a string literal" },
  // Date/Time
  now: { signature: "now()", doc: "Current timestamp" },
  current_timestamp: { signature: "current_timestamp", doc: "Current timestamp" },
  current_date: { signature: "current_date", doc: "Current date" },
  current_time: { signature: "current_time", doc: "Current time" },
  date: { signature: "date(expr)", doc: "Cast to date" },
  time: { signature: "time(expr)", doc: "Cast to time" },
  datetime: { signature: "datetime(expr)", doc: "Cast to datetime" },
  timestamp: { signature: "timestamp(expr)", doc: "Cast to timestamp" },
  datediff: { signature: "datediff(a, b)", doc: "Difference between dates" },
  date_diff: { signature: "date_diff(a, b, part)", doc: "Difference between dates" },
  dateadd: { signature: "dateadd(part, n, date)", doc: "Add an interval to a date" },
  date_add: { signature: "date_add(date, interval)", doc: "Add an interval to a date" },
  date_sub: { signature: "date_sub(date, interval)", doc: "Subtract an interval" },
  date_subtract: { signature: "date_subtract(date, interval)", doc: "Subtract an interval" },
  date_trunc: { signature: "date_trunc(part, ts)", doc: "Truncate to a precision" },
  extract: { signature: "extract(part FROM ts)", doc: "Date/time field" },
  date_part: { signature: "date_part(part, ts)", doc: "Date/time field" },
  to_char: { signature: "to_char(value, fmt)", doc: "Format as text" },
  to_date: { signature: "to_date(str, fmt)", doc: "Parse a date" },
  to_timestamp: { signature: "to_timestamp(str, fmt)", doc: "Parse a timestamp" },
  timestampdiff: { signature: "timestampdiff(part, a, b)", doc: "Difference between timestamps" },
  age: { signature: "age(a [, b])", doc: "Interval between timestamps" },
  overlaps: { signature: "overlaps(a1, a2, b1, b2)", doc: "Time ranges overlap" },
  isfinite: { signature: "isfinite(ts)", doc: "Timestamp is finite" },
  to_seconds: { signature: "to_seconds(ts)", doc: "Seconds since epoch" },
  // Null handling / conditional
  coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
  nullif: { signature: "nullif(a, b)", doc: "NULL when a = b" },
  nvl: { signature: "nvl(a, b)", doc: "b when a is null" },
  nvl2: { signature: "nvl2(a, b, c)", doc: "b when a not null else c" },
  ifnull: { signature: "ifnull(a, b)", doc: "b when a is null" },
  if: { signature: "if(cond, a, b)", doc: "Conditional value" },
  isnull: { signature: "isnull(a [, b])", doc: "Null test / coalesce" },
  decode: { signature: "decode(expr, k1, v1, …, default)", doc: "Inline switch" },
  iif: { signature: "iif(cond, a, b)", doc: "Conditional value" },
  // Conversion
  cast: { signature: "cast(expr AS type)", doc: "Convert a value's type" },
  convert: { signature: "convert(type, expr)", doc: "Convert a value's type" },
  try_cast: { signature: "try_cast(expr AS type)", doc: "Cast, NULL on failure" },
  try_convert: { signature: "try_convert(type, expr)", doc: "Convert, NULL on failure" },
  typeof: { signature: "typeof(expr)", doc: "Runtime type name" },
  pg_typeof: { signature: "pg_typeof(expr)", doc: "Runtime type name" },
  // Window
  row_number: { signature: "row_number() OVER (…)", doc: "Sequential row number" },
  rank: { signature: "rank() OVER (…)", doc: "Rank with gaps" },
  dense_rank: { signature: "dense_rank() OVER (…)", doc: "Rank without gaps" },
  percent_rank: { signature: "percent_rank() OVER (…)", doc: "Relative rank 0–1" },
  ntile: { signature: "ntile(n) OVER (…)", doc: "Bucket rows into n groups" },
  lag: { signature: "lag(expr [, n [, default]]) OVER (…)", doc: "Value n rows back" },
  lead: { signature: "lead(expr [, n [, default]]) OVER (…)", doc: "Value n rows ahead" },
  first_value: { signature: "first_value(expr) OVER (…)", doc: "First value in frame" },
  last_value: { signature: "last_value(expr) OVER (…)", doc: "Last value in frame" },
  nth_value: { signature: "nth_value(expr, n) OVER (…)", doc: "Nth value in frame" },
  cume_dist: { signature: "cume_dist() OVER (…)", doc: "Cumulative distribution" },
  // JSON
  json_extract: { signature: "json_extract(doc, path)", doc: "Extract a JSON value" },
  json_value: { signature: "json_value(doc, path)", doc: "Extract a JSON scalar" },
  json_object: { signature: "json_object(k, v, …)", doc: "Build a JSON object" },
  json_array: { signature: "json_array(v, …)", doc: "Build a JSON array" },
  json_arrayagg: { signature: "json_arrayagg(expr)", doc: "Aggregate into a JSON array" },
  json_objectagg: { signature: "json_objectagg(k, v)", doc: "Aggregate into a JSON object" },
  json_keys: { signature: "json_keys(doc)", doc: "Top-level JSON keys" },
  json_length: { signature: "json_length(doc)", doc: "JSON document length" },
  json_valid: { signature: "json_valid(doc)", doc: "Is valid JSON" },
  json_type: { signature: "json_type(doc)", doc: "JSON value type" },
  json_quote: { signature: "json_quote(str)", doc: "Quote as a JSON string" },
  to_json: { signature: "to_json(value)", doc: "Convert to JSON" },
  to_jsonb: { signature: "to_jsonb(value)", doc: "Convert to JSONB" },
  jsonb_set: { signature: "jsonb_set(doc, path, value)", doc: "Set a JSONB path" },
  jsonb_insert: { signature: "jsonb_insert(doc, path, value)", doc: "Insert into JSONB" },
  jsonb_path_exists: { signature: "jsonb_path_exists(doc, path)", doc: "JSONPath match exists" },
  json_strip_nulls: { signature: "json_strip_nulls(doc)", doc: "Drop null fields" },
  jsonb_strip_nulls: { signature: "jsonb_strip_nulls(doc)", doc: "Drop null fields" },
  json_build_object: { signature: "json_build_object(k, v, …)", doc: "Build a JSON object" },
  jsonb_build_object: { signature: "jsonb_build_object(k, v, …)", doc: "Build a JSONB object" },
  json_build_array: { signature: "json_build_array(v, …)", doc: "Build a JSON array" },
  jsonb_build_array: { signature: "jsonb_build_array(v, …)", doc: "Build a JSONB array" },
  row_to_json: { signature: "row_to_json(row)", doc: "Row as JSON object" },
  json_each: { signature: "json_each(doc)", doc: "Expand object into rows" },
  jsonb_each: { signature: "jsonb_each(doc)", doc: "Expand object into rows" },
  json_each_text: { signature: "json_each_text(doc)", doc: "Expand object into text rows" },
  jsonb_each_text: { signature: "jsonb_each_text(doc)", doc: "Expand object into text rows" },
  jsonb_pretty: { signature: "jsonb_pretty(doc)", doc: "Pretty-printed JSONB" },
  // Array
  array_length: { signature: "array_length(arr, dim)", doc: "Array dimension length" },
  cardinality: { signature: "cardinality(arr)", doc: "Total array elements" },
  array_upper: { signature: "array_upper(arr, dim)", doc: "Array upper bound" },
  array_lower: { signature: "array_lower(arr, dim)", doc: "Array lower bound" },
  array_cat: { signature: "array_cat(a, b)", doc: "Concatenate arrays" },
  array_append: { signature: "array_append(arr, v)", doc: "Append to array" },
  array_prepend: { signature: "array_prepend(v, arr)", doc: "Prepend to array" },
  array_remove: { signature: "array_remove(arr, v)", doc: "Remove all occurrences" },
  array_replace: { signature: "array_replace(arr, from, to)", doc: "Replace elements" },
  unnest: { signature: "unnest(arr)", doc: "Expand array into rows" },
  generate_series: { signature: "generate_series(start, stop [, step])", doc: "Row series" },
  array_position: { signature: "array_position(arr, v)", doc: "Index of element" },
  array_contains: { signature: "array_contains(arr, v)", doc: "Array membership" },
  array_slice: { signature: "array_slice(arr, from, to)", doc: "Array slice" },
  // Bitwise
  bit_and: { signature: "bit_and(expr)", doc: "Aggregate bitwise AND" },
  bit_or: { signature: "bit_or(expr)", doc: "Aggregate bitwise OR" },
  bit_xor: { signature: "bit_xor(expr)", doc: "Aggregate bitwise XOR" },
  bit_count: { signature: "bit_count(n)", doc: "Number of set bits" },
  get_bit: { signature: "get_bit(n, i)", doc: "Bit at position" },
  set_bit: { signature: "set_bit(n, i, v)", doc: "Set bit at position" },
  // Formatting
  format: { signature: "format(fmt, args…)", doc: "printf-style formatting" },
  space: { signature: "space(n)", doc: "n spaces" },
  repeat: { signature: "repeat(str, n)", doc: "Repeat a string" },
  // XML
  xmlcomment: { signature: "xmlcomment(str)", doc: "XML comment" },
  xmlconcat: { signature: "xmlconcat(a, b, …)", doc: "Concatenate XML" },
  xmlelement: { signature: "xmlelement(NAME tag, …)", doc: "Build an XML element" },
  xmlforest: { signature: "xmlforest(expr AS name, …)", doc: "Build an XML forest" },
  xmlagg: { signature: "xmlagg(expr)", doc: "Aggregate XML fragments" },
  xmlparse: { signature: "xmlparse(DOCUMENT str)", doc: "Parse XML" },
  xmlserialize: { signature: "xmlserialize(DOCUMENT expr AS type)", doc: "Serialize XML" },
  xmlpi: { signature: "xmlpi(NAME target [, str])", doc: "XML processing instruction" },
  xmlroot: { signature: "xmlroot(xml, VERSION …)", doc: "Set XML root properties" },
  xpath: { signature: "xpath(path, doc)", doc: "Evaluate an XPath" },
  // Network
  inet_aton: { signature: "inet_aton(ip)", doc: "IPv4 string to number" },
  inet_ntoa: { signature: "inet_ntoa(n)", doc: "Number to IPv4 string" },
  inet_same_family: { signature: "inet_same_family(a, b)", doc: "Same address family" },
  inet_merge: { signature: "inet_merge(a, b)", doc: "Smallest covering CIDR" },
  // UUID
  gen_random_uuid: { signature: "gen_random_uuid()", doc: "Random UUID" },
  uuid_generate_v4: { signature: "uuid_generate_v4()", doc: "Random UUID" },
  uuid: { signature: "uuid()", doc: "Random UUID" },
  uuid_ns_dns: { signature: "uuid_ns_dns()", doc: "DNS namespace UUID" },
  uuid_ns_url: { signature: "uuid_ns_url()", doc: "URL namespace UUID" },
  uuid_ns_oid: { signature: "uuid_ns_oid()", doc: "OID namespace UUID" },
  uuid_ns_x500: { signature: "uuid_ns_x500()", doc: "X.500 namespace UUID" },
  uuid_generate_v1mc: { signature: "uuid_generate_v1mc()", doc: "v1 UUID (multicast)" },
  uuid_generate_v1: { signature: "uuid_generate_v1()", doc: "v1 UUID" },
  // Crypto
  md5: { signature: "md5(str)", doc: "MD5 hash" },
  sha1: { signature: "sha1(str)", doc: "SHA-1 hash" },
  sha224: { signature: "sha224(str)", doc: "SHA-224 hash" },
  sha256: { signature: "sha256(str)", doc: "SHA-256 hash" },
  sha384: { signature: "sha384(str)", doc: "SHA-384 hash" },
  sha512: { signature: "sha512(str)", doc: "SHA-512 hash" },
  digest: { signature: "digest(str, algo)", doc: "Hash with algorithm" },
  hmac: { signature: "hmac(str, key, algo)", doc: "Keyed hash" },
  encrypt: { signature: "encrypt(data, key, algo)", doc: "Encrypt bytes" },
  decrypt: { signature: "decrypt(data, key, algo)", doc: "Decrypt bytes" },
  gen_salt: { signature: "gen_salt(algo [, rounds])", doc: "Salt for crypt()" },
};

/**
 * Dialect overrides/additions for DB_SPECIFIC_FUNCTIONS. Keys are lowercase
 * function names; these win over COMMON_FUNCTION_SIGNATURES on a conflict.
 */
const DIALECT_FUNCTION_SIGNATURES: Partial<
  Record<DatabaseType, Record<string, SqlFunctionSignature>>
> = {
  postgresql: {
    now: { signature: "now()", doc: "Transaction start timestamp" },
    to_char: { signature: "to_char(value, fmt)", doc: "Format timestamp/number as text" },
    to_date: { signature: "to_date(str, fmt)", doc: "Parse text as date" },
    to_timestamp: { signature: "to_timestamp(str, fmt)", doc: "Parse text as timestamptz" },
    to_number: { signature: "to_number(str, fmt)", doc: "Parse text as numeric" },
    date_trunc: { signature: "date_trunc(part, ts)", doc: "Truncate to a precision" },
    date_part: { signature: "date_part(part, ts)", doc: "Extract a date/time field" },
    string_agg: { signature: "string_agg(expr, delim)", doc: "Concatenate with delimiter" },
    format: { signature: "format(fmt, args…)", doc: "sprintf-style formatting" },
    format_type: { signature: "format_type(oid, typmod)", doc: "SQL name of a type" },
    current_setting: { signature: "current_setting(name)", doc: "Read a GUC" },
    set_config: { signature: "set_config(name, value, is_local)", doc: "Set a GUC" },
    pg_typeof: { signature: "pg_typeof(expr)", doc: "Runtime type name" },
    pg_size_pretty: { signature: "pg_size_pretty(bytes)", doc: "Human-readable size" },
    pg_total_relation_size: {
      signature: "pg_total_relation_size(rel)",
      doc: "Table + indexes size",
    },
    pg_relation_size: { signature: "pg_relation_size(rel)", doc: "Relation size" },
    pg_indexes_size: { signature: "pg_indexes_size(rel)", doc: "Index size" },
    pg_tablespace_size: { signature: "pg_tablespace_size(name)", doc: "Tablespace size" },
    pg_database_size: { signature: "pg_database_size(name)", doc: "Database size" },
    pg_table_size: { signature: "pg_table_size(rel)", doc: "Table size" },
    pg_column_size: { signature: "pg_column_size(value)", doc: "Stored value size" },
    pg_get_userbyid: { signature: "pg_get_userbyid(oid)", doc: "Role name by oid" },
    pg_get_expr: { signature: "pg_get_expr(expr, relid)", doc: "Deparse an expression" },
    pg_get_functiondef: { signature: "pg_get_functiondef(oid)", doc: "Function definition" },
    pg_get_constraintdef: { signature: "pg_get_constraintdef(oid)", doc: "Constraint definition" },
    pg_get_indexdef: { signature: "pg_get_indexdef(oid)", doc: "Index definition" },
    pg_get_ruledef: { signature: "pg_get_ruledef(oid)", doc: "Rule definition" },
    pg_get_triggerdef: { signature: "pg_get_triggerdef(oid)", doc: "Trigger definition" },
    pg_get_serial_sequence: {
      signature: "pg_get_serial_sequence(table, col)",
      doc: "Sequence for a serial column",
    },
    pg_cancel_backend: { signature: "pg_cancel_backend(pid)", doc: "Cancel a backend's query" },
    pg_terminate_backend: { signature: "pg_terminate_backend(pid)", doc: "Terminate a backend" },
    pg_blocking_pids: { signature: "pg_blocking_pids(pid)", doc: "Blocking backend pids" },
    pg_ls_dir: { signature: "pg_ls_dir(path)", doc: "List a server directory" },
    pg_read_file: { signature: "pg_read_file(path)", doc: "Read a server file" },
    pg_stat_file: { signature: "pg_stat_file(path)", doc: "Stat a server file" },
    pg_stat_activity: { signature: "pg_stat_activity", doc: "Per-backend activity view" },
    pg_extensions: { signature: "pg_extensions", doc: "Installed extensions view" },
    pg_available_extensions: {
      signature: "pg_available_extensions",
      doc: "Installable extensions view",
    },
    col_description: { signature: "col_description(rel, col)", doc: "Column comment" },
    obj_description: { signature: "obj_description(oid [, catalog])", doc: "Object comment" },
    shobj_description: {
      signature: "shobj_description(oid, catalog)",
      doc: "Shared-object comment",
    },
    to_regclass: { signature: "to_regclass(name)", doc: "Relation name to oid" },
    to_regnamespace: { signature: "to_regnamespace(name)", doc: "Schema name to oid" },
    to_regrole: { signature: "to_regrole(name)", doc: "Role name to oid" },
    to_regtype: { signature: "to_regtype(name)", doc: "Type name to oid" },
    make_date: { signature: "make_date(y, m, d)", doc: "Build a date" },
    make_time: { signature: "make_time(h, m, s)", doc: "Build a time" },
    make_interval: { signature: "make_interval(y, m, w, d, h, min, s)", doc: "Build an interval" },
    make_timestamp: { signature: "make_timestamp(y, m, d, h, min, s)", doc: "Build a timestamp" },
    make_timestamptz: {
      signature: "make_timestamptz(y, m, d, h, min, s [, tz])",
      doc: "Build a timestamptz",
    },
    jsonb_path_query: { signature: "jsonb_path_query(doc, path)", doc: "JSONPath query rows" },
    jsonb_path_query_first: {
      signature: "jsonb_path_query_first(doc, path)",
      doc: "First JSONPath match",
    },
    jsonb_extract_path: {
      signature: "jsonb_extract_path(doc, keys…)",
      doc: "Extract nested value",
    },
    jsonb_array_elements: { signature: "jsonb_array_elements(doc)", doc: "Expand array into rows" },
    jsonb_array_elements_text: {
      signature: "jsonb_array_elements_text(doc)",
      doc: "Expand array into text rows",
    },
    jsonb_delete: { signature: "jsonb_delete(doc, key)", doc: "Delete a key" },
    jsonb_delete_path: { signature: "jsonb_delete_path(doc, path)", doc: "Delete a path" },
    jsonb_populate_record: {
      signature: "jsonb_populate_record(base, doc)",
      doc: "JSONB to record",
    },
    jsonb_to_record: { signature: "jsonb_to_record(doc)", doc: "JSONB object to record" },
    jsonb_to_recordset: { signature: "jsonb_to_recordset(doc)", doc: "JSONB array to records" },
    json_object_agg: { signature: "json_object_agg(k, v)", doc: "Aggregate into a JSON object" },
    json_array_elements: { signature: "json_array_elements(doc)", doc: "Expand array into rows" },
    json_array_elements_text: {
      signature: "json_array_elements_text(doc)",
      doc: "Expand array into text rows",
    },
    json_object_keys: { signature: "json_object_keys(doc)", doc: "Top-level keys" },
    json_typeof: { signature: "json_typeof(doc)", doc: "JSON value type" },
    jsonb_typeof: { signature: "jsonb_typeof(doc)", doc: "JSONB value type" },
    inet_server_addr: { signature: "inet_server_addr()", doc: "Server address" },
    inet_server_port: { signature: "inet_server_port()", doc: "Server port" },
    inet_client_addr: { signature: "inet_client_addr()", doc: "Client address" },
    inet_client_port: { signature: "inet_client_port()", doc: "Client port" },
    version: { signature: "version()", doc: "Server version string" },
    current_schemas: { signature: "current_schemas(include_implicit)", doc: "Search path schemas" },
    transaction_timestamp: { signature: "transaction_timestamp()", doc: "Transaction start time" },
    statement_timestamp: { signature: "statement_timestamp()", doc: "Statement start time" },
    clock_timestamp: { signature: "clock_timestamp()", doc: "Wall-clock time" },
    uuid_generate_v1: { signature: "uuid_generate_v1()", doc: "v1 UUID" },
    uuid_generate_v1mc: { signature: "uuid_generate_v1mc()", doc: "v1 UUID (multicast)" },
    uuid_generate_v4: { signature: "uuid_generate_v4()", doc: "Random UUID" },
    gen_random_uuid: { signature: "gen_random_uuid()", doc: "Random UUID" },
    quote_ident: { signature: "quote_ident(str)", doc: "Quote as an identifier" },
    quote_literal: { signature: "quote_literal(str)", doc: "Quote as a literal" },
    quote_nullable: { signature: "quote_nullable(value)", doc: "Quote, NULL-aware" },
    jsonb_pretty: { signature: "jsonb_pretty(doc)", doc: "Pretty-printed JSONB" },
    json_strip_nulls: { signature: "json_strip_nulls(doc)", doc: "Drop null fields" },
    jsonb_strip_nulls: { signature: "jsonb_strip_nulls(doc)", doc: "Drop null fields" },
    row_to_json: { signature: "row_to_json(row)", doc: "Row as JSON object" },
    json_each: { signature: "json_each(doc)", doc: "Expand object into rows" },
    jsonb_each: { signature: "jsonb_each(doc)", doc: "Expand object into rows" },
    json_each_text: { signature: "json_each_text(doc)", doc: "Expand object into text rows" },
    jsonb_each_text: { signature: "jsonb_each_text(doc)", doc: "Expand object into text rows" },
    json_build_object: { signature: "json_build_object(k, v, …)", doc: "Build a JSON object" },
    jsonb_build_object: { signature: "jsonb_build_object(k, v, …)", doc: "Build a JSONB object" },
    json_build_array: { signature: "json_build_array(v, …)", doc: "Build a JSON array" },
    jsonb_build_array: { signature: "jsonb_build_array(v, …)", doc: "Build a JSONB array" },
    reset: { signature: "reset", doc: "Reset a GUC" },
  },
  mysql: {
    now: { signature: "now()", doc: "Current timestamp" },
    datediff: { signature: "datediff(a, b)", doc: "Days between dates" },
    date_add: { signature: "date_add(date, INTERVAL n unit)", doc: "Add an interval" },
    date_sub: { signature: "date_sub(date, INTERVAL n unit)", doc: "Subtract an interval" },
    date_format: { signature: "date_format(date, fmt)", doc: "Format a date" },
    str_to_date: { signature: "str_to_date(str, fmt)", doc: "Parse a date" },
    group_concat: {
      signature: "group_concat(expr [SEPARATOR s])",
      doc: "Concatenate group values",
    },
    ifnull: { signature: "ifnull(a, b)", doc: "b when a is null" },
    if: { signature: "if(cond, a, b)", doc: "Conditional value" },
    json_extract: { signature: "json_extract(doc, path)", doc: "Extract a JSON value" },
    json_unquote: { signature: "json_unquote(doc)", doc: "Unquote a JSON value" },
    json_set: { signature: "json_set(doc, path, v, …)", doc: "Set JSON paths" },
    json_insert: { signature: "json_insert(doc, path, v, …)", doc: "Insert JSON paths" },
    json_replace: { signature: "json_replace(doc, path, v, …)", doc: "Replace JSON paths" },
    json_remove: { signature: "json_remove(doc, path, …)", doc: "Remove JSON paths" },
    json_contains: { signature: "json_contains(doc, v)", doc: "JSON containment" },
    json_search: { signature: "json_search(doc, one|all, str)", doc: "Find a JSON value" },
    json_table: { signature: "json_table(doc, path COLUMNS (…))", doc: "JSON to relational rows" },
    regexp: { signature: "expr REGEXP pattern", doc: "Regex match" },
    regexp_like: { signature: "regexp_like(str, pattern)", doc: "Regex match" },
    regexp_instr: { signature: "regexp_instr(str, pattern)", doc: "Regex match position" },
    regexp_substr: { signature: "regexp_substr(str, pattern)", doc: "Regex substring" },
    regexp_replace: { signature: "regexp_replace(str, pattern, repl)", doc: "Regex replace" },
    uuid: { signature: "uuid()", doc: "Random UUID" },
    uuid_to_bin: { signature: "uuid_to_bin(uuid [, swap])", doc: "UUID to binary" },
    bin_to_uuid: { signature: "bin_to_uuid(bin [, swap])", doc: "Binary to UUID" },
    last_insert_id: { signature: "last_insert_id()", doc: "Last AUTO_INCREMENT id" },
    found_rows: { signature: "found_rows()", doc: "Rows without LIMIT" },
    row_count: { signature: "row_count()", doc: "Rows changed by last statement" },
    connection_id: { signature: "connection_id()", doc: "Connection id" },
    database: { signature: "database()", doc: "Current schema" },
    user: { signature: "user()", doc: "Current user@host" },
    version: { signature: "version()", doc: "Server version" },
    sleep: { signature: "sleep(seconds)", doc: "Pause execution" },
    benchmark: { signature: "benchmark(n, expr)", doc: "Time an expression" },
    inet_aton: { signature: "inet_aton(ip)", doc: "IPv4 string to number" },
    inet_ntoa: { signature: "inet_ntoa(n)", doc: "Number to IPv4 string" },
    inet6_aton: { signature: "inet6_aton(ip)", doc: "IPv6 string to binary" },
    inet6_ntoa: { signature: "inet6_ntoa(bin)", doc: "Binary to IPv6 string" },
    is_ipv4: { signature: "is_ipv4(str)", doc: "Is IPv4 address" },
    is_ipv6: { signature: "is_ipv6(str)", doc: "Is IPv6 address" },
    aes_encrypt: { signature: "aes_encrypt(str, key)", doc: "AES encrypt" },
    aes_decrypt: { signature: "aes_decrypt(data, key)", doc: "AES decrypt" },
    md5: { signature: "md5(str)", doc: "MD5 hash" },
    sha1: { signature: "sha1(str)", doc: "SHA-1 hash" },
    sha2: { signature: "sha2(str, bits)", doc: "SHA-2 hash" },
    compress: { signature: "compress(str)", doc: "Compress a string" },
    uncompress: { signature: "uncompress(data)", doc: "Uncompress a string" },
    from_unixtime: { signature: "from_unixtime(ts [, fmt])", doc: "Unix time to datetime" },
    unix_timestamp: { signature: "unix_timestamp([date])", doc: "Unix timestamp" },
    timestampdiff: { signature: "timestampdiff(unit, a, b)", doc: "Difference in units" },
    timestampadd: { signature: "timestampadd(unit, n, ts)", doc: "Add units to a timestamp" },
    curdate: { signature: "curdate()", doc: "Current date" },
    curtime: { signature: "curtime()", doc: "Current time" },
    utc_timestamp: { signature: "utc_timestamp()", doc: "Current UTC timestamp" },
    sysdate: { signature: "sysdate()", doc: "Execution-time timestamp" },
    dayname: { signature: "dayname(date)", doc: "Weekday name" },
    monthname: { signature: "monthname(date)", doc: "Month name" },
    week: { signature: "week(date [, mode])", doc: "Week number" },
    quarter: { signature: "quarter(date)", doc: "Quarter 1–4" },
    yearweek: { signature: "yearweek(date)", doc: "Year + week" },
    period_add: { signature: "period_add(yyyymm, n)", doc: "Add months to a period" },
    period_diff: { signature: "period_diff(a, b)", doc: "Months between periods" },
    sec_to_time: { signature: "sec_to_time(n)", doc: "Seconds to time" },
    time_to_sec: { signature: "time_to_sec(t)", doc: "Time to seconds" },
    make_set: { signature: "make_set(bits, a, b, …)", doc: "Comma list from bit mask" },
    field: { signature: "field(v, a, b, …)", doc: "Index of v in list" },
    find_in_set: { signature: "find_in_set(v, list)", doc: "Index in a comma list" },
    elt: { signature: "elt(n, a, b, …)", doc: "Nth list element" },
    export_set: { signature: "export_set(bits, on, off)", doc: "Bit mask as string" },
    char_length: { signature: "char_length(str)", doc: "Length in characters" },
    character_length: { signature: "character_length(str)", doc: "Length in characters" },
    octet_length: { signature: "octet_length(str)", doc: "Length in bytes" },
    locate: { signature: "locate(needle, str [, pos])", doc: "Substring position" },
    insert: { signature: "insert(str, pos, len, new)", doc: "Replace a substring range" },
    space: { signature: "space(n)", doc: "n spaces" },
    repeat: { signature: "repeat(str, n)", doc: "Repeat a string" },
    soundex: { signature: "soundex(str)", doc: "Phonetic code" },
    conv: { signature: "conv(n, from_base, to_base)", doc: "Convert between bases" },
    bin: { signature: "bin(n)", doc: "Binary string" },
    oct: { signature: "oct(n)", doc: "Octal string" },
    hex: { signature: "hex(n)", doc: "Hex string" },
    unhex: { signature: "unhex(str)", doc: "Hex to binary" },
    ord: { signature: "ord(char)", doc: "Character code" },
  },
  sqlite: {
    date: { signature: "date(timestring [, modifier…])", doc: "Date from a timestring" },
    time: { signature: "time(timestring [, modifier…])", doc: "Time from a timestring" },
    datetime: {
      signature: "datetime(timestring [, modifier…])",
      doc: "Datetime from a timestring",
    },
    julianday: { signature: "julianday(timestring)", doc: "Julian day number" },
    unixepoch: { signature: "unixepoch(timestring)", doc: "Unix timestamp" },
    strftime: { signature: "strftime(fmt, timestring)", doc: "Format a timestring" },
    typeof: { signature: "typeof(expr)", doc: "Storage class name" },
    quote: { signature: "quote(expr)", doc: "SQL literal for a value" },
    hex: { signature: "hex(blob)", doc: "Hex string" },
    unhex: { signature: "unhex(str)", doc: "Hex to blob" },
    zeroblob: { signature: "zeroblob(n)", doc: "n zero bytes" },
    randomblob: { signature: "randomblob(n)", doc: "n random bytes" },
    last_insert_rowid: { signature: "last_insert_rowid()", doc: "Last inserted rowid" },
    changes: { signature: "changes()", doc: "Rows changed by last statement" },
    total_changes: { signature: "total_changes()", doc: "Rows changed since open" },
    sqlite_version: { signature: "sqlite_version()", doc: "SQLite version" },
    sqlite_source_id: { signature: "sqlite_source_id()", doc: "Source id" },
    json: { signature: "json(doc)", doc: "Validate/minify JSON" },
    json_extract: { signature: "json_extract(doc, path)", doc: "Extract a JSON value" },
    json_set: { signature: "json_set(doc, path, v, …)", doc: "Set JSON paths" },
    json_insert: { signature: "json_insert(doc, path, v, …)", doc: "Insert JSON paths" },
    json_replace: { signature: "json_replace(doc, path, v, …)", doc: "Replace JSON paths" },
    json_remove: { signature: "json_remove(doc, path, …)", doc: "Remove JSON paths" },
    json_type: { signature: "json_type(doc [, path])", doc: "JSON value type" },
    json_valid: { signature: "json_valid(doc)", doc: "Is valid JSON" },
    json_quote: { signature: "json_quote(v)", doc: "Quote as a JSON value" },
    json_array: { signature: "json_array(v, …)", doc: "Build a JSON array" },
    json_object: { signature: "json_object(k, v, …)", doc: "Build a JSON object" },
    json_array_length: { signature: "json_array_length(doc [, path])", doc: "Array length" },
    json_each: { signature: "json_each(doc [, path])", doc: "Expand JSON into rows" },
    json_tree: { signature: "json_tree(doc [, path])", doc: "Expand JSON recursively" },
    group_concat: { signature: "group_concat(expr [, sep])", doc: "Concatenate group values" },
    ifnull: { signature: "ifnull(a, b)", doc: "b when a is null" },
    iif: { signature: "iif(cond, a, b)", doc: "Conditional value" },
    instr: { signature: "instr(str, needle)", doc: "Substring position" },
    substr: { signature: "substr(str, from [, count])", doc: "Extract a substring" },
    glob: { signature: "glob(pattern, str)", doc: "GLOB match" },
    like: { signature: "like(pattern, str [, esc])", doc: "LIKE match" },
    printf: { signature: "printf(fmt, args…)", doc: "printf-style formatting" },
    format: { signature: "format(fmt, args…)", doc: "printf-style formatting" },
    unicode: { signature: "unicode(char)", doc: "Code point" },
    char: { signature: "char(code, …)", doc: "Characters for code points" },
    likelihood: { signature: "likelihood(expr, p)", doc: "Planner hint" },
    likely: { signature: "likely(expr)", doc: "Planner hint (0.9)" },
    unlikely: { signature: "unlikely(expr)", doc: "Planner hint (0.1)" },
    abs: { signature: "abs(n)", doc: "Absolute value" },
    round: { signature: "round(n [, digits])", doc: "Round to nearest value" },
    random: { signature: "random()", doc: "Random 64-bit integer" },
    min: { signature: "min(a, b, …)", doc: "Smallest argument / aggregate" },
    max: { signature: "max(a, b, …)", doc: "Largest argument / aggregate" },
  },
  mssql: {
    getdate: { signature: "getdate()", doc: "Current datetime" },
    sysdatetime: { signature: "sysdatetime()", doc: "Current datetime2" },
    getutcdate: { signature: "getutcdate()", doc: "Current UTC datetime" },
    dateadd: { signature: "dateadd(part, n, date)", doc: "Add an interval" },
    datediff: { signature: "datediff(part, a, b)", doc: "Difference in parts" },
    datediff_big: { signature: "datediff_big(part, a, b)", doc: "Difference as bigint" },
    datename: { signature: "datename(part, date)", doc: "Date part as text" },
    datepart: { signature: "datepart(part, date)", doc: "Date part as int" },
    datefromparts: { signature: "datefromparts(y, m, d)", doc: "Build a date" },
    eomonth: { signature: "eomonth(date [, n])", doc: "Last day of month" },
    isnull: { signature: "isnull(a, b)", doc: "b when a is null" },
    coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
    iif: { signature: "iif(cond, a, b)", doc: "Conditional value" },
    choose: { signature: "choose(n, a, b, …)", doc: "Nth list element" },
    len: { signature: "len(str)", doc: "String length" },
    datalength: { signature: "datalength(expr)", doc: "Bytes used" },
    charindex: { signature: "charindex(needle, str [, pos])", doc: "Substring position" },
    patindex: { signature: "patindex(pattern, str)", doc: "Pattern position" },
    stuff: { signature: "stuff(str, pos, len, new)", doc: "Replace a substring range" },
    string_split: { signature: "string_split(str, sep)", doc: "Split into rows" },
    string_agg: { signature: "string_agg(expr, sep)", doc: "Concatenate with separator" },
    concat: { signature: "concat(a, b, …)", doc: "Concatenate strings" },
    concat_ws: { signature: "concat_ws(sep, a, b, …)", doc: "Concatenate with separator" },
    format: { signature: "format(value, fmt [, culture])", doc: "Format a value" },
    cast: { signature: "cast(expr AS type)", doc: "Convert a value's type" },
    convert: { signature: "convert(type, expr [, style])", doc: "Convert a value's type" },
    try_cast: { signature: "try_cast(expr AS type)", doc: "Cast, NULL on failure" },
    try_convert: {
      signature: "try_convert(type, expr [, style])",
      doc: "Convert, NULL on failure",
    },
    parse: { signature: "parse(str AS type [USING culture])", doc: "Parse a value" },
    try_parse: {
      signature: "try_parse(str AS type [USING culture])",
      doc: "Parse, NULL on failure",
    },
    newid: { signature: "newid()", doc: "Random uniqueidentifier" },
    newsequentialid: { signature: "newsequentialid()", doc: "Sequential GUID" },
    scope_identity: { signature: "scope_identity()", doc: "Last identity in scope" },
    ident_current: { signature: "ident_current(table)", doc: "Last identity value" },
    rowcount_big: { signature: "rowcount_big()", doc: "Rows affected (bigint)" },
    error_message: { signature: "error_message()", doc: "Error text in CATCH" },
    error_number: { signature: "error_number()", doc: "Error number in CATCH" },
    error_line: { signature: "error_line()", doc: "Error line in CATCH" },
    error_procedure: { signature: "error_procedure()", doc: "Error procedure in CATCH" },
    error_severity: { signature: "error_severity()", doc: "Error severity in CATCH" },
    error_state: { signature: "error_state()", doc: "Error state in CATCH" },
    xact_state: { signature: "xact_state()", doc: "Transaction state" },
    db_name: { signature: "db_name([id])", doc: "Database name" },
    db_id: { signature: "db_id([name])", doc: "Database id" },
    object_id: { signature: "object_id(name)", doc: "Object id" },
    object_name: { signature: "object_name(id)", doc: "Object name" },
    schema_name: { signature: "schema_name([id])", doc: "Schema name" },
    schema_id: { signature: "schema_id([name])", doc: "Schema id" },
    suser_name: { signature: "suser_name()", doc: "Login name" },
    suser_id: { signature: "suser_id()", doc: "Login id" },
    user_name: { signature: "user_name()", doc: "Database user name" },
    host_name: { signature: "host_name()", doc: "Client host name" },
    app_name: { signature: "app_name()", doc: "Application name" },
    serverproperty: { signature: "serverproperty(name)", doc: "Server property" },
    checksum: { signature: "checksum(expr, …)", doc: "Checksum" },
    binary_checksum: { signature: "binary_checksum(expr, …)", doc: "Binary checksum" },
    hashbytes: { signature: "hashbytes(algo, data)", doc: "Hash bytes" },
    compress: { signature: "compress(data)", doc: "GZip compress" },
    decompress: { signature: "decompress(data)", doc: "GZip decompress" },
    json_value: { signature: "json_value(doc, path)", doc: "Extract a JSON scalar" },
    json_query: { signature: "json_query(doc, path)", doc: "Extract a JSON fragment" },
    json_modify: { signature: "json_modify(doc, path, v)", doc: "Set a JSON path" },
    isjson: { signature: "isjson(doc)", doc: "Is valid JSON" },
    openjson: { signature: "openjson(doc [, path])", doc: "Expand JSON into rows" },
    replicate: { signature: "replicate(str, n)", doc: "Repeat a string" },
    unicode: { signature: "unicode(char)", doc: "Code point" },
    nchar: { signature: "nchar(code)", doc: "Character for a code point" },
    quotename: { signature: "quotename(str [, quote])", doc: "Quote as an identifier" },
    parsename: { signature: "parsename(name, part)", doc: "Part of a qualified name" },
    col_name: { signature: "col_name(table_id, col_id)", doc: "Column name" },
    col_length: { signature: "col_length(table, col)", doc: "Column length" },
    row_number: { signature: "row_number() OVER (…)", doc: "Sequential row number" },
    rank: { signature: "rank() OVER (…)", doc: "Rank with gaps" },
    dense_rank: { signature: "dense_rank() OVER (…)", doc: "Rank without gaps" },
    ntile: { signature: "ntile(n) OVER (…)", doc: "Bucket rows into n groups" },
    lag: { signature: "lag(expr [, n [, default]]) OVER (…)", doc: "Value n rows back" },
    lead: { signature: "lead(expr [, n [, default]]) OVER (…)", doc: "Value n rows ahead" },
    first_value: { signature: "first_value(expr) OVER (…)", doc: "First value in frame" },
    last_value: { signature: "last_value(expr) OVER (…)", doc: "Last value in frame" },
    percent_rank: { signature: "percent_rank() OVER (…)", doc: "Relative rank 0–1" },
    cume_dist: { signature: "cume_dist() OVER (…)", doc: "Cumulative distribution" },
    count_big: { signature: "count_big(expr | *)", doc: "Count as bigint" },
    grouping_id: { signature: "grouping_id(expr, …)", doc: "Grouping level" },
    checksum_agg: { signature: "checksum_agg(expr)", doc: "Aggregate checksum" },
    stdev: { signature: "stdev(expr)", doc: "Sample standard deviation" },
    stdevp: { signature: "stdevp(expr)", doc: "Population standard deviation" },
    var: { signature: "var(expr)", doc: "Sample variance" },
    varp: { signature: "varp(expr)", doc: "Population variance" },
    approx_count_distinct: {
      signature: "approx_count_distinct(expr)",
      doc: "Approximate distinct count",
    },
    approx_percentile_cont: {
      signature: "approx_percentile_cont(p) WITHIN GROUP (…)",
      doc: "Approximate percentile",
    },
  },
  clickhouse: {
    now: { signature: "now()", doc: "Current timestamp" },
    today: { signature: "today()", doc: "Current date" },
    yesterday: { signature: "yesterday()", doc: "Previous date" },
    todatetime: { signature: "toDateTime(expr)", doc: "Cast to DateTime" },
    todate: { signature: "toDate(expr)", doc: "Cast to Date" },
    tostring: { signature: "toString(expr)", doc: "Cast to String" },
    touint64: { signature: "toUInt64(expr)", doc: "Cast to UInt64" },
    toint64: { signature: "toInt64(expr)", doc: "Cast to Int64" },
    tofloat64: { signature: "toFloat64(expr)", doc: "Cast to Float64" },
    todecimal64: { signature: "toDecimal64(expr, scale)", doc: "Cast to Decimal64" },
    tostartofday: { signature: "toStartOfDay(ts)", doc: "Truncate to day" },
    tostartofhour: { signature: "toStartOfHour(ts)", doc: "Truncate to hour" },
    tostartofminute: { signature: "toStartOfMinute(ts)", doc: "Truncate to minute" },
    tostartofmonth: { signature: "toStartOfMonth(ts)", doc: "Truncate to month" },
    tostartofweek: { signature: "toStartOfWeek(ts)", doc: "Truncate to week" },
    tostartofyear: { signature: "toStartOfYear(ts)", doc: "Truncate to year" },
    toyyyymm: { signature: "toYYYYMM(date)", doc: "Year-month number" },
    formatdatetime: { signature: "formatDateTime(ts, fmt)", doc: "Format a timestamp" },
    date_diff: { signature: "date_diff(unit, a, b)", doc: "Difference in units" },
    date_add: { signature: "date_add(unit, n, date)", doc: "Add an interval" },
    date_sub: { signature: "date_sub(unit, n, date)", doc: "Subtract an interval" },
    uniq: { signature: "uniq(expr)", doc: "Approximate distinct count" },
    uniqexact: { signature: "uniqExact(expr)", doc: "Exact distinct count" },
    quantile: { signature: "quantile(p)(expr)", doc: "Approximate quantile" },
    quantiles: { signature: "quantiles(p1, p2, …)(expr)", doc: "Approximate quantiles" },
    grouparray: { signature: "groupArray(expr)", doc: "Aggregate into an array" },
    groupuniqarray: { signature: "groupUniqArray(expr)", doc: "Aggregate distinct into an array" },
    argmin: { signature: "argMin(v, k)", doc: "v where k is minimal" },
    argmax: { signature: "argMax(v, k)", doc: "v where k is maximal" },
    any: { signature: "any(expr)", doc: "Any encountered value" },
    anylast: { signature: "anyLast(expr)", doc: "Last encountered value" },
    sumif: { signature: "sumIf(expr, cond)", doc: "Conditional sum" },
    countif: { signature: "countIf(cond)", doc: "Conditional count" },
    avgif: { signature: "avgIf(expr, cond)", doc: "Conditional average" },
    minif: { signature: "minIf(expr, cond)", doc: "Conditional min" },
    maxif: { signature: "maxIf(expr, cond)", doc: "Conditional max" },
    arrayjoin: { signature: "arrayJoin(arr)", doc: "Expand array into rows" },
    arraymap: { signature: "arrayMap(f, arr)", doc: "Map over an array" },
    arrayfilter: { signature: "arrayFilter(f, arr)", doc: "Filter an array" },
    arrayreduce: { signature: "arrayReduce(f, arr)", doc: "Reduce an array" },
    has: { signature: "has(arr, v)", doc: "Array membership" },
    indexof: { signature: "indexOf(arr, v)", doc: "Index of element" },
    length: { signature: "length(str | arr)", doc: "Length" },
    empty: { signature: "empty(str | arr)", doc: "Is empty" },
    notempty: { signature: "notEmpty(str | arr)", doc: "Is not empty" },
    splitbychar: { signature: "splitByChar(sep, str)", doc: "Split into an array" },
    splitbystring: { signature: "splitByString(sep, str)", doc: "Split into an array" },
    arraystringconcat: { signature: "arrayStringConcat(arr [, sep])", doc: "Join an array" },
    extract: { signature: "extract(str, pattern)", doc: "First regex group" },
    extractall: { signature: "extractAll(str, pattern)", doc: "All regex matches" },
    match: { signature: "match(str, pattern)", doc: "Regex match" },
    like: { signature: "like(str, pattern)", doc: "LIKE match" },
    multilike: { signature: "multiLike(str, p1, p2, …)", doc: "Match any LIKE pattern" },
    position: { signature: "position(str, needle)", doc: "Substring position" },
    jsonextractstring: { signature: "JSONExtractString(doc, key)", doc: "JSON string field" },
    jsonextractint: { signature: "JSONExtractInt(doc, key)", doc: "JSON int field" },
    jsonextract: { signature: "JSONExtract(doc, key, type)", doc: "JSON field cast" },
    jsonhas: { signature: "JSONHas(doc, key)", doc: "JSON key exists" },
    dictget: { signature: "dictGet(dict, attr, key)", doc: "Dictionary lookup" },
    dictgetstring: { signature: "dictGetString(dict, attr, key)", doc: "Dictionary lookup" },
    generateuuidv4: { signature: "generateUUIDv4()", doc: "Random UUID" },
    rand: { signature: "rand()", doc: "Random UInt32" },
    rand64: { signature: "rand64()", doc: "Random UInt64" },
    cityhash64: { signature: "cityHash64(v, …)", doc: "CityHash" },
    siphash64: { signature: "sipHash64(v, …)", doc: "SipHash" },
    md5: { signature: "MD5(str)", doc: "MD5 hash" },
    sha256: { signature: "SHA256(str)", doc: "SHA-256 hash" },
    hostname: { signature: "hostName()", doc: "Server host name" },
    version: { signature: "version()", doc: "Server version" },
    uptime: { signature: "uptime()", doc: "Server uptime seconds" },
    timezone: { signature: "timeZone()", doc: "Server timezone" },
    if: { signature: "if(cond, a, b)", doc: "Conditional value" },
    multiif: { signature: "multiIf(c1, v1, …, else)", doc: "Multi-branch conditional" },
    coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
    nullif: { signature: "nullIf(a, b)", doc: "NULL when a = b" },
    assumenotnull: { signature: "assumeNotNull(v)", doc: "Strip Nullable" },
    tonullable: { signature: "toNullable(v)", doc: "Wrap as Nullable" },
  },
  duckdb: {
    now: { signature: "now()", doc: "Current timestamp" },
    current_timestamp: { signature: "current_timestamp", doc: "Current timestamp" },
    date_trunc: { signature: "date_trunc(part, ts)", doc: "Truncate to a precision" },
    date_part: { signature: "date_part(part, ts)", doc: "Extract a date/time field" },
    date_diff: { signature: "date_diff(part, a, b)", doc: "Difference in parts" },
    epoch: { signature: "epoch(ts)", doc: "Seconds since epoch" },
    strftime: { signature: "strftime(ts, fmt)", doc: "Format a timestamp" },
    strptime: { signature: "strptime(str, fmt)", doc: "Parse a timestamp" },
    list_aggregate: { signature: "list_aggregate(list, fn)", doc: "Aggregate a list" },
    list_transform: { signature: "list_transform(list, f)", doc: "Map over a list" },
    list_filter: { signature: "list_filter(list, f)", doc: "Filter a list" },
    list_contains: { signature: "list_contains(list, v)", doc: "List membership" },
    list_position: { signature: "list_position(list, v)", doc: "Index of element" },
    unnest: { signature: "unnest(list)", doc: "Expand list into rows" },
    generate_series: { signature: "generate_series(start, stop [, step])", doc: "Row series" },
    range: { signature: "range(start, stop [, step])", doc: "Row series" },
    regexp_matches: { signature: "regexp_matches(str, pattern)", doc: "Regex match" },
    regexp_extract: { signature: "regexp_extract(str, pattern [, group])", doc: "Regex group" },
    regexp_replace: { signature: "regexp_replace(str, pattern, repl)", doc: "Regex replace" },
    regexp_full_match: { signature: "regexp_full_match(str, pattern)", doc: "Full regex match" },
    string_split: { signature: "string_split(str, sep)", doc: "Split into a list" },
    string_agg: { signature: "string_agg(expr, sep)", doc: "Concatenate with separator" },
    quantile: { signature: "quantile(expr, p)", doc: "Quantile" },
    quantile_cont: { signature: "quantile_cont(expr, p)", doc: "Continuous quantile" },
    quantile_disc: { signature: "quantile_disc(expr, p)", doc: "Discrete quantile" },
    approx_count_distinct: {
      signature: "approx_count_distinct(expr)",
      doc: "Approximate distinct count",
    },
    arg_min: { signature: "arg_min(v, k)", doc: "v where k is minimal" },
    arg_max: { signature: "arg_max(v, k)", doc: "v where k is maximal" },
    any_value: { signature: "any_value(expr)", doc: "Any encountered value" },
    first: { signature: "first(expr)", doc: "First value" },
    last: { signature: "last(expr)", doc: "Last value" },
    histogram: { signature: "histogram(expr)", doc: "Value histogram" },
    mode: { signature: "mode(expr)", doc: "Most frequent value" },
    entropy: { signature: "entropy(expr)", doc: "Shannon entropy" },
    struct_pack: { signature: "struct_pack(k := v, …)", doc: "Build a struct" },
    row: { signature: "row(v, …)", doc: "Build a struct" },
    map: { signature: "map(keys, values)", doc: "Build a map" },
    uuid: { signature: "uuid()", doc: "Random UUID" },
    hash: { signature: "hash(v)", doc: "Hash value" },
    md5: { signature: "md5(str)", doc: "MD5 hash" },
    read_csv: { signature: "read_csv(path [, opts])", doc: "Read a CSV file" },
    read_parquet: { signature: "read_parquet(path)", doc: "Read Parquet files" },
    read_json: { signature: "read_json(path)", doc: "Read a JSON file" },
    parquet_schema: { signature: "parquet_schema(path)", doc: "Parquet file schema" },
    glob: { signature: "glob(pattern)", doc: "Matching file paths" },
    typeof: { signature: "typeof(expr)", doc: "Type name" },
    coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
    ifnull: { signature: "ifnull(a, b)", doc: "b when a is null" },
    nullif: { signature: "nullif(a, b)", doc: "NULL when a = b" },
    if: { signature: "if(cond, a, b)", doc: "Conditional value" },
    greatest: { signature: "greatest(a, b, …)", doc: "Largest argument" },
    least: { signature: "least(a, b, …)", doc: "Smallest argument" },
    row_number: { signature: "row_number() OVER (…)", doc: "Sequential row number" },
    rank: { signature: "rank() OVER (…)", doc: "Rank with gaps" },
    dense_rank: { signature: "dense_rank() OVER (…)", doc: "Rank without gaps" },
    lag: { signature: "lag(expr [, n [, default]]) OVER (…)", doc: "Value n rows back" },
    lead: { signature: "lead(expr [, n [, default]]) OVER (…)", doc: "Value n rows ahead" },
  },
  bigquery: {
    current_timestamp: { signature: "current_timestamp()", doc: "Current timestamp" },
    current_date: { signature: "current_date()", doc: "Current date" },
    current_datetime: { signature: "current_datetime()", doc: "Current datetime" },
    date_diff: { signature: "date_diff(a, b, part)", doc: "Difference in parts" },
    date_add: { signature: "date_add(date, INTERVAL n part)", doc: "Add an interval" },
    date_sub: { signature: "date_sub(date, INTERVAL n part)", doc: "Subtract an interval" },
    date_trunc: { signature: "date_trunc(date, part)", doc: "Truncate to a precision" },
    timestamp_diff: { signature: "timestamp_diff(a, b, part)", doc: "Difference in parts" },
    timestamp_add: { signature: "timestamp_add(ts, INTERVAL n part)", doc: "Add an interval" },
    timestamp_trunc: { signature: "timestamp_trunc(ts, part)", doc: "Truncate to a precision" },
    format_date: { signature: "format_date(fmt, date)", doc: "Format a date" },
    format_timestamp: { signature: "format_timestamp(fmt, ts)", doc: "Format a timestamp" },
    parse_date: { signature: "parse_date(fmt, str)", doc: "Parse a date" },
    parse_timestamp: { signature: "parse_timestamp(fmt, str)", doc: "Parse a timestamp" },
    string_agg: { signature: "string_agg(expr [, sep])", doc: "Concatenate with separator" },
    array_agg: { signature: "array_agg(expr)", doc: "Aggregate into an array" },
    array_concat: { signature: "array_concat(a, b, …)", doc: "Concatenate arrays" },
    array_length: { signature: "array_length(arr)", doc: "Array length" },
    array_to_string: { signature: "array_to_string(arr, sep)", doc: "Join an array" },
    generate_array: { signature: "generate_array(start, stop [, step])", doc: "Number array" },
    generate_date_array: {
      signature: "generate_date_array(a, b [, INTERVAL n part])",
      doc: "Date array",
    },
    unnest: { signature: "unnest(arr)", doc: "Expand array into rows" },
    safe_cast: { signature: "safe_cast(expr AS type)", doc: "Cast, NULL on failure" },
    cast: { signature: "cast(expr AS type)", doc: "Convert a value's type" },
    ifnull: { signature: "ifnull(a, b)", doc: "b when a is null" },
    nullif: { signature: "nullif(a, b)", doc: "NULL when a = b" },
    coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
    if: { signature: "if(cond, a, b)", doc: "Conditional value" },
    json_extract: { signature: "json_extract(doc, path)", doc: "Extract a JSON value" },
    json_extract_scalar: {
      signature: "json_extract_scalar(doc, path)",
      doc: "Extract a JSON scalar",
    },
    json_query: { signature: "json_query(doc, path)", doc: "Extract a JSON fragment" },
    json_value: { signature: "json_value(doc, path)", doc: "Extract a JSON scalar" },
    to_json: { signature: "to_json(value)", doc: "Convert to JSON" },
    to_json_string: { signature: "to_json_string(value)", doc: "Convert to JSON text" },
    regexp_contains: { signature: "regexp_contains(str, pattern)", doc: "Regex match" },
    regexp_extract: { signature: "regexp_extract(str, pattern)", doc: "Regex group" },
    regexp_replace: { signature: "regexp_replace(str, pattern, repl)", doc: "Regex replace" },
    regexp_instr: { signature: "regexp_instr(str, pattern)", doc: "Regex position" },
    split: { signature: "split(str [, sep])", doc: "Split into an array" },
    starts_with: { signature: "starts_with(str, prefix)", doc: "Prefix test" },
    ends_with: { signature: "ends_with(str, suffix)", doc: "Suffix test" },
    farm_fingerprint: { signature: "farm_fingerprint(v)", doc: "Fingerprint hash" },
    md5: { signature: "md5(str)", doc: "MD5 hash" },
    sha256: { signature: "sha256(str)", doc: "SHA-256 hash" },
    sha512: { signature: "sha512(str)", doc: "SHA-512 hash" },
    generate_uuid: { signature: "generate_uuid()", doc: "Random UUID" },
    approx_count_distinct: {
      signature: "approx_count_distinct(expr)",
      doc: "Approximate distinct count",
    },
    approx_quantiles: { signature: "approx_quantiles(expr, n)", doc: "Approximate quantiles" },
    approx_top_count: { signature: "approx_top_count(expr, n)", doc: "Approximate top values" },
    approx_top_sum: { signature: "approx_top_sum(v, w, n)", doc: "Approximate top sums" },
    countif: { signature: "countif(cond)", doc: "Conditional count" },
    logical_and: { signature: "logical_and(expr)", doc: "Aggregate AND" },
    logical_or: { signature: "logical_or(expr)", doc: "Aggregate OR" },
    any_value: { signature: "any_value(expr)", doc: "Any encountered value" },
    row_number: { signature: "row_number() OVER (…)", doc: "Sequential row number" },
    rank: { signature: "rank() OVER (…)", doc: "Rank with gaps" },
    dense_rank: { signature: "dense_rank() OVER (…)", doc: "Rank without gaps" },
    lag: { signature: "lag(expr [, n [, default]]) OVER (…)", doc: "Value n rows back" },
    lead: { signature: "lead(expr [, n [, default]]) OVER (…)", doc: "Value n rows ahead" },
    first_value: { signature: "first_value(expr) OVER (…)", doc: "First value in frame" },
    last_value: { signature: "last_value(expr) OVER (…)", doc: "Last value in frame" },
    session_user: { signature: "session_user()", doc: "Session user" },
    st_geogpoint: { signature: "st_geogpoint(lon, lat)", doc: "Geography point" },
    st_distance: { signature: "st_distance(a, b)", doc: "Distance between geographies" },
    net: { signature: "net.ip_from_string(str)", doc: "Parse an IP" },
  },
  oracle: {
    sysdate: { signature: "sysdate", doc: "Current date/time" },
    systimestamp: { signature: "systimestamp", doc: "Current timestamp" },
    current_timestamp: { signature: "current_timestamp", doc: "Session timestamp" },
    current_date: { signature: "current_date", doc: "Session date" },
    add_months: { signature: "add_months(date, n)", doc: "Add months" },
    months_between: { signature: "months_between(a, b)", doc: "Months between dates" },
    next_day: { signature: "next_day(date, weekday)", doc: "Next weekday" },
    last_day: { signature: "last_day(date)", doc: "Last day of month" },
    trunc: { signature: "trunc(n | date [, fmt])", doc: "Truncate number/date" },
    round: { signature: "round(n | date [, fmt])", doc: "Round number/date" },
    to_char: { signature: "to_char(value [, fmt [, nlsparam]])", doc: "Format as text" },
    to_date: { signature: "to_date(str [, fmt])", doc: "Parse a date" },
    to_timestamp: { signature: "to_timestamp(str [, fmt])", doc: "Parse a timestamp" },
    to_number: { signature: "to_number(str [, fmt])", doc: "Parse a number" },
    to_clob: { signature: "to_clob(v)", doc: "Convert to CLOB" },
    to_blob: { signature: "to_blob(v)", doc: "Convert to BLOB" },
    nvl: { signature: "nvl(a, b)", doc: "b when a is null" },
    nvl2: { signature: "nvl2(a, b, c)", doc: "b when a not null else c" },
    decode: { signature: "decode(expr, k1, v1, …, default)", doc: "Inline switch" },
    coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
    nullif: { signature: "nullif(a, b)", doc: "NULL when a = b" },
    greatest: { signature: "greatest(a, b, …)", doc: "Largest argument" },
    least: { signature: "least(a, b, …)", doc: "Smallest argument" },
    listagg: {
      signature: "listagg(expr [, sep]) WITHIN GROUP (…)",
      doc: "Concatenate group values",
    },
    wm_concat: { signature: "wm_concat(expr)", doc: "Concatenate group values" },
    instr: { signature: "instr(str, needle [, pos [, n]])", doc: "Substring position" },
    substr: { signature: "substr(str, from [, count])", doc: "Extract a substring" },
    regexp_substr: { signature: "regexp_substr(str, pattern)", doc: "Regex substring" },
    regexp_replace: { signature: "regexp_replace(str, pattern, repl)", doc: "Regex replace" },
    regexp_instr: { signature: "regexp_instr(str, pattern)", doc: "Regex position" },
    regexp_count: { signature: "regexp_count(str, pattern)", doc: "Regex match count" },
    regexp_like: { signature: "regexp_like(str, pattern)", doc: "Regex match" },
    lpad: { signature: "lpad(str, len [, fill])", doc: "Left-pad to length" },
    rpad: { signature: "rpad(str, len [, fill])", doc: "Right-pad to length" },
    initcap: { signature: "initcap(str)", doc: "Capitalize each word" },
    soundex: { signature: "soundex(str)", doc: "Phonetic code" },
    translate: { signature: "translate(str, from, to)", doc: "Map characters one-to-one" },
    ascii: { signature: "ascii(char)", doc: "Character code" },
    chr: { signature: "chr(code)", doc: "Character for a code" },
    uid: { signature: "uid", doc: "Session user id" },
    user: { signature: "user", doc: "Session user" },
    userenv: { signature: "userenv(param)", doc: "Session environment" },
    sys_context: { signature: "sys_context(ns, param)", doc: "Context value" },
    ora_hash: { signature: "ora_hash(v [, buckets])", doc: "Hash value" },
    standard_hash: { signature: "standard_hash(v [, algo])", doc: "Hash value" },
    rownum: { signature: "rownum", doc: "Row number pseudo-column" },
    rowid: { signature: "rowid", doc: "Row address pseudo-column" },
    dump: { signature: "dump(expr [, fmt])", doc: "Internal representation" },
    vsize: { signature: "vsize(expr)", doc: "Bytes used" },
    cast: { signature: "cast(expr AS type)", doc: "Convert a value's type" },
    extract: { signature: "extract(part FROM ts)", doc: "Date/time field" },
    row_number: { signature: "row_number() OVER (…)", doc: "Sequential row number" },
    rank: { signature: "rank() OVER (…)", doc: "Rank with gaps" },
    dense_rank: { signature: "dense_rank() OVER (…)", doc: "Rank without gaps" },
    lag: { signature: "lag(expr [, n [, default]]) OVER (…)", doc: "Value n rows back" },
    lead: { signature: "lead(expr [, n [, default]]) OVER (…)", doc: "Value n rows ahead" },
    first_value: { signature: "first_value(expr) OVER (…)", doc: "First value in frame" },
    last_value: { signature: "last_value(expr) OVER (…)", doc: "Last value in frame" },
    ratio_to_report: { signature: "ratio_to_report(expr) OVER (…)", doc: "Share of total" },
    percentile_cont: {
      signature: "percentile_cont(p) WITHIN GROUP (…)",
      doc: "Continuous percentile",
    },
    percentile_disc: {
      signature: "percentile_disc(p) WITHIN GROUP (…)",
      doc: "Discrete percentile",
    },
    median: { signature: "median(expr)", doc: "Median value" },
    stats_mode: { signature: "stats_mode(expr)", doc: "Most frequent value" },
  },
  snowflake: {
    current_timestamp: { signature: "current_timestamp()", doc: "Current timestamp" },
    current_date: { signature: "current_date()", doc: "Current date" },
    sysdate: { signature: "sysdate()", doc: "Current timestamp" },
    dateadd: { signature: "dateadd(part, n, date)", doc: "Add an interval" },
    datediff: { signature: "datediff(part, a, b)", doc: "Difference in parts" },
    date_trunc: { signature: "date_trunc(part, ts)", doc: "Truncate to a precision" },
    timeadd: { signature: "timeadd(part, n, time)", doc: "Add an interval" },
    timestampadd: { signature: "timestampadd(part, n, ts)", doc: "Add an interval" },
    last_day: { signature: "last_day(date [, part])", doc: "Last day of period" },
    next_day: { signature: "next_day(date, weekday)", doc: "Next weekday" },
    previous_day: { signature: "previous_day(date, weekday)", doc: "Previous weekday" },
    monthname: { signature: "monthname(date)", doc: "Month name" },
    dayname: { signature: "dayname(date)", doc: "Weekday name" },
    to_date: { signature: "to_date(str [, fmt])", doc: "Parse a date" },
    to_timestamp: { signature: "to_timestamp(str [, fmt])", doc: "Parse a timestamp" },
    to_time: { signature: "to_time(str [, fmt])", doc: "Parse a time" },
    to_char: { signature: "to_char(value [, fmt])", doc: "Format as text" },
    to_varchar: { signature: "to_varchar(value [, fmt])", doc: "Format as text" },
    to_number: { signature: "to_number(str [, fmt])", doc: "Parse a number" },
    try_to_date: { signature: "try_to_date(str [, fmt])", doc: "Parse, NULL on failure" },
    try_to_timestamp: { signature: "try_to_timestamp(str [, fmt])", doc: "Parse, NULL on failure" },
    try_to_number: { signature: "try_to_number(str [, fmt])", doc: "Parse, NULL on failure" },
    nvl: { signature: "nvl(a, b)", doc: "b when a is null" },
    nvl2: { signature: "nvl2(a, b, c)", doc: "b when a not null else c" },
    ifnull: { signature: "ifnull(a, b)", doc: "b when a is null" },
    zeroifnull: { signature: "zeroifnull(v)", doc: "0 when null" },
    nullifzero: { signature: "nullifzero(v)", doc: "NULL when 0" },
    coalesce: { signature: "coalesce(a, b, …)", doc: "First non-null argument" },
    iff: { signature: "iff(cond, a, b)", doc: "Conditional value" },
    decode: { signature: "decode(expr, k1, v1, …, default)", doc: "Inline switch" },
    listagg: { signature: "listagg(expr [, sep])", doc: "Concatenate group values" },
    array_agg: { signature: "array_agg(expr)", doc: "Aggregate into an array" },
    object_agg: { signature: "object_agg(k, v)", doc: "Aggregate into an object" },
    array_construct: { signature: "array_construct(v, …)", doc: "Build an array" },
    array_append: { signature: "array_append(arr, v)", doc: "Append to array" },
    array_prepend: { signature: "array_prepend(v, arr)", doc: "Prepend to array" },
    array_cat: { signature: "array_cat(a, b)", doc: "Concatenate arrays" },
    array_contains: { signature: "array_contains(v, arr)", doc: "Array membership" },
    array_size: { signature: "array_size(arr)", doc: "Array length" },
    object_construct: { signature: "object_construct(k, v, …)", doc: "Build an object" },
    object_keys: { signature: "object_keys(obj)", doc: "Object keys" },
    object_delete: { signature: "object_delete(obj, k, …)", doc: "Delete keys" },
    object_insert: { signature: "object_insert(obj, k, v)", doc: "Insert a key" },
    object_pick: { signature: "object_pick(obj, k, …)", doc: "Pick keys" },
    parse_json: { signature: "parse_json(str)", doc: "Parse JSON to VARIANT" },
    try_parse_json: { signature: "try_parse_json(str)", doc: "Parse, NULL on failure" },
    to_json: { signature: "to_json(v)", doc: "Convert to JSON" },
    to_variant: { signature: "to_variant(v)", doc: "Convert to VARIANT" },
    get: { signature: "get(obj, key)", doc: "Object/array element" },
    get_path: { signature: "get_path(obj, path)", doc: "Nested element" },
    flatten: { signature: "flatten(input)", doc: "Expand into rows" },
    regexp_like: { signature: "regexp_like(str, pattern)", doc: "Regex match" },
    regexp_replace: { signature: "regexp_replace(str, pattern, repl)", doc: "Regex replace" },
    regexp_substr: { signature: "regexp_substr(str, pattern)", doc: "Regex substring" },
    regexp_count: { signature: "regexp_count(str, pattern)", doc: "Regex match count" },
    regexp_instr: { signature: "regexp_instr(str, pattern)", doc: "Regex position" },
    split: { signature: "split(str, sep)", doc: "Split into an array" },
    split_to_table: { signature: "split_to_table(str, sep)", doc: "Split into rows" },
    startswith: { signature: "startswith(str, prefix)", doc: "Prefix test" },
    endswith: { signature: "endswith(str, suffix)", doc: "Suffix test" },
    contains: { signature: "contains(str, sub)", doc: "Substring test" },
    editdistance: { signature: "editdistance(a, b)", doc: "Levenshtein distance" },
    soundex: { signature: "soundex(str)", doc: "Phonetic code" },
    translate: { signature: "translate(str, from, to)", doc: "Map characters" },
    md5: { signature: "md5(str)", doc: "MD5 hash" },
    sha1: { signature: "sha1(str)", doc: "SHA-1 hash" },
    sha2: { signature: "sha2(str, bits)", doc: "SHA-2 hash" },
    hash: { signature: "hash(v, …)", doc: "Hash value" },
    uuid_string: { signature: "uuid_string()", doc: "Random UUID" },
    random: { signature: "random()", doc: "Random 64-bit integer" },
    uniform: { signature: "uniform(min, max, gen)", doc: "Uniform random" },
    seq1: { signature: "seq1()", doc: "Sequence value" },
    seq4: { signature: "seq4()", doc: "Sequence value" },
    seq8: { signature: "seq8()", doc: "Sequence value" },
    row_number: { signature: "row_number() OVER (…)", doc: "Sequential row number" },
    rank: { signature: "rank() OVER (…)", doc: "Rank with gaps" },
    dense_rank: { signature: "dense_rank() OVER (…)", doc: "Rank without gaps" },
    lag: { signature: "lag(expr [, n [, default]]) OVER (…)", doc: "Value n rows back" },
    lead: { signature: "lead(expr [, n [, default]]) OVER (…)", doc: "Value n rows ahead" },
    first_value: { signature: "first_value(expr) OVER (…)", doc: "First value in frame" },
    last_value: { signature: "last_value(expr) OVER (…)", doc: "Last value in frame" },
    ntile: { signature: "ntile(n) OVER (…)", doc: "Bucket rows into n groups" },
    ratio_to_report: { signature: "ratio_to_report(expr) OVER (…)", doc: "Share of total" },
    approx_count_distinct: {
      signature: "approx_count_distinct(expr)",
      doc: "Approximate distinct count",
    },
    approx_percentile: { signature: "approx_percentile(expr, p)", doc: "Approximate percentile" },
    approx_top_k: { signature: "approx_top_k(expr, k)", doc: "Approximate top values" },
    hll: { signature: "hll(expr)", doc: "HyperLogLog state" },
    median: { signature: "median(expr)", doc: "Median value" },
    mode: { signature: "mode(expr)", doc: "Most frequent value" },
    current_user: { signature: "current_user()", doc: "Current user" },
    current_role: { signature: "current_role()", doc: "Current role" },
    current_database: { signature: "current_database()", doc: "Current database" },
    current_schema: { signature: "current_schema()", doc: "Current schema" },
    current_warehouse: { signature: "current_warehouse()", doc: "Current warehouse" },
    current_session: { signature: "current_session()", doc: "Current session" },
    current_account: { signature: "current_account()", doc: "Current account" },
    current_region: { signature: "current_region()", doc: "Current region" },
    invoker_role: { signature: "invoker_role()", doc: "Invoker role" },
    is_role_in_session: { signature: "is_role_in_session(role)", doc: "Role active in session" },
  },
  cassandra: {
    now: { signature: "now()", doc: "Current timeuuid" },
    uuid: { signature: "uuid()", doc: "Random UUID" },
    totimestamp: { signature: "toTimestamp(timeuuid)", doc: "timeuuid to timestamp" },
    tounixtimestamp: { signature: "toUnixTimestamp(timeuuid)", doc: "timeuuid to unix time" },
    todate: { signature: "toDate(timeuuid)", doc: "timeuuid to date" },
    blobastext: { signature: "blobAsText(blob)", doc: "Blob to text" },
    textasblob: { signature: "textAsBlob(str)", doc: "Text to blob" },
    token: { signature: "token(pk)", doc: "Partition token" },
    writetime: { signature: "writetime(col)", doc: "Cell write timestamp" },
    ttl: { signature: "ttl(col)", doc: "Cell TTL" },
    count: { signature: "count(expr | *)", doc: "Number of rows" },
    min: { signature: "min(expr)", doc: "Smallest value" },
    max: { signature: "max(expr)", doc: "Largest value" },
    sum: { signature: "sum(expr)", doc: "Total of values" },
    avg: { signature: "avg(expr)", doc: "Mean of values" },
  },
};

function mergeSignatures(dialect: DatabaseType): Readonly<Record<string, SqlFunctionSignature>> {
  const overrides = DIALECT_FUNCTION_SIGNATURES[dialect];
  return Object.freeze(
    overrides ? { ...COMMON_FUNCTION_SIGNATURES, ...overrides } : COMMON_FUNCTION_SIGNATURES,
  );
}

function uniqueFrozen(items: readonly string[]): readonly string[] {
  return Object.freeze([...new Set(items)]);
}

function mergeUniqueFrozen(base: ReadonlySet<string>, extra: readonly string[]): readonly string[] {
  const merged = new Set(base);
  for (const item of extra) merged.add(item);
  return Object.freeze([...merged]);
}

/**
 * Builds the SQL completions map for all supported database types.
 *
 * Base keyword/function lists are computed once and shared (frozen) across
 * database types that have no engine-specific additions, instead of being
 * rebuilt per type. All output arrays are frozen so consumers can safely
 * iterate without defensive copies and V8 keeps them in fast mode.
 */
function buildSqlCompletions(): Record<DatabaseType, SqlCompletionSet> {
  const baseKeywords = uniqueFrozen(BASE_KEYWORDS);
  const baseKeywordsSet = new Set(baseKeywords);

  const baseFunctionsSet = new Set<string>();
  for (const category of Object.values(COMMON_FUNCTIONS)) {
    for (const fn of category) baseFunctionsSet.add(fn);
  }
  const baseFunctions = Object.freeze([...baseFunctionsSet]);

  let sharedKeywords: readonly string[] | null = null;
  let sharedFunctions: readonly string[] | null = null;

  const result = {} as Record<DatabaseType, SqlCompletionSet>;

  for (const dbType of DATABASE_TYPES) {
    const dbKeywords = DB_SPECIFIC_KEYWORDS[dbType];
    const dbFunctions = DB_SPECIFIC_FUNCTIONS[dbType];

    result[dbType] = {
      keywords: dbKeywords?.length
        ? mergeUniqueFrozen(baseKeywordsSet, dbKeywords)
        : (sharedKeywords ??= baseKeywords),
      functions: dbFunctions?.length
        ? mergeUniqueFrozen(baseFunctionsSet, dbFunctions)
        : (sharedFunctions ??= baseFunctions),
      operators: OPERATORS,
      functionSignatures: mergeSignatures(dbType),
    };
  }

  return Object.freeze(result);
}

export const SQL_COMPLETIONS: Record<DatabaseType, SqlCompletionSet> = buildSqlCompletions();

/**
 * Returns the completion set for a given database type.
 * Falls back to postgresql if the type is unknown.
 */
export function getCompletionSet(dbType: DatabaseType | undefined): SqlCompletionSet {
  return (dbType && SQL_COMPLETIONS[dbType]) || SQL_COMPLETIONS.postgresql;
}
