import type { DatabaseType } from "../types/database";

export interface SqlCompletionSet {
  keywords: string[];
  functions: string[];
  operators: string[];
}

// SQL aggregate and scalar functions organized by category
const COMMON_FUNCTIONS: Record<string, string[]> = {
  // Aggregate
  aggregate: ["COUNT", "SUM", "AVG", "MIN", "MAX", "COUNT(*)", "ARRAY_AGG", "STRING_AGG", "LISTAGG", "GROUP_CONCAT", "GROUPING", "ANY", "SOME", "EVERY"],
  // Numeric
  numeric: ["ABS", "ROUND", "FLOOR", "CEIL", "CEILING", "MOD", "POWER", "SQRT", "LN", "LOG", "LOG10", "LOG2", "EXP", "SIGN", "TRUNC", "RANDOM", "RAND"],
  // String
  string: ["CONCAT", "CONCAT_WS", "SUBSTRING", "SUBSTR", "LENGTH", "LEN", "CHAR_LENGTH", "UPPER", "LOWER", "TRIM", "LTRIM", "RTRIM", "LPAD", "RPAD", "REPLACE", "REVERSE", "LEFT", "RIGHT", "POSITION", "STRPOS", "INSTR", "REGEXP_REPLACE", "SPLIT_PART", "REGEXP_SUBSTR", "TRANSLATE", "INITCAP", "ASCII", "CHAR", "SOUNDEX", "DIFFERENCE", "QUOTE_IDENT", "QUOTE_LITERAL"],
  // Date/Time
  datetime: ["NOW", "CURRENT_TIMESTAMP", "CURRENT_DATE", "CURRENT_TIME", "DATE", "TIME", "DATETIME", "TIMESTAMP", "DATEDIFF", "DATE_DIFF", "DATEADD", "DATE_ADD", "DATE_SUB", "DATE_SUBTRACT", "DATE_TRUNC", "EXTRACT", "DATE_PART", "TO_CHAR", "TO_DATE", "TO_TIMESTAMP", "TIMESTAMPDIFF", "AGE", "OVERLAPS", "ISFINITE", "TO_SECONDS"],
  // Null handling
  nullHandling: ["COALESCE", "NULLIF", "NVL", "NVL2", "IFNULL", "IF", "ISNULL", "DECODE", "IFNULL"],
  // Conditional
  conditional: ["CASE", "WHEN", "THEN", "ELSE", "END", "IIF"],
  // Type conversion
  conversion: ["CAST", "CONVERT", "TRY_CAST", "TRY_CONVERT", "TYPEOF", "pg_typeof"],
  // Boolean / comparison
  boolean: ["TRUE", "FALSE", "NULL", "IS", "IS NOT", "IS NULL", "IS NOT NULL", "BETWEEN", "LIKE", "ILIKE", "NOT LIKE", "NOT ILIKE", "IN", "NOT IN", "EXISTS", "NOT EXISTS"],
  // Window functions
  window: ["ROW_NUMBER", "RANK", "DENSE_RANK", "PERCENT_RANK", "NTILE", "LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE", "CUME_DIST", "OVER", "PARTITION BY"],
  // JSON / document
  json: ["JSON_EXTRACT", "JSON_VALUE", "JSON_OBJECT", "JSON_ARRAY", "JSON_ARRAYAGG", "JSON_OBJECTAGG", "JSON_KEYS", "JSON_LENGTH", "JSON_VALID", "JSON_TYPE", "JSON_QUOTE", "TO_JSON", "TO_JSONB", "JSONB_SET", "JSONB_INSERT", "JSONB_PATH_EXISTS", "JSON_STRIP_NULLS", "JSONB_STRIP_NULLS", "JSON_BUILD_OBJECT", "JSONB_BUILD_OBJECT", "JSON_BUILD_ARRAY", "JSONB_BUILD_ARRAY", "ROW_TO_JSON", "JSON_EACH", "JSONB_EACH", "json_each_text", "jsonb_each_text", "jsonb_pretty"],
  // Array
  array: ["ARRAY", "ARRAY_LENGTH", "CARDINALITY", "ARRAY_UPPER", "ARRAY_LOWER", "ARRAY_CAT", "ARRAY_APPEND", "ARRAY_PREPEND", "ARRAY_REMOVE", "ARRAY_REPLACE", "UNNEST", "UNNEST_ORDINALITY", "GENERATE_SERIES", "ARRAY_POSITION", "ARRAY_CONTAINS", "ARRAY_SLICE"],
  // Bitwise
  bitwise: ["BIT_AND", "BIT_OR", "BIT_XOR", "BIT_COUNT", "GET_BIT", "SET_BIT", "<<", ">>", "&", "|", "^", "~"],
  // Formatting
  formatting: ["FORMAT", "LPAD", "RPAD", "SPACE", "REPEAT"],
  // XML
  xml: ["XMLCOMMENT", "XMLCONCAT", "XMLELEMENT", "XMLFOREST", "XMLAGG", "XMLPARSE", "XMLSERIALIZE", "XMLPI", "XMLROOT", "XPATH"],
  // Network
  network: ["INET_ATON", "INET_NTOA", "INET_SAME_FAMILY", "INET_MERGE"],
  // UUID
  uuid: ["GEN_RANDOM_UUID", "UUID_GENERATE_V4", "UUID", "UUID_NS_DNS", "UUID_NS_URL", "UUID_NS_OID", "UUID_NS_X500", "uuid_generate_v1mc", "uuid_generate_v1"],
  // Crypto
  crypto: ["MD5", "SHA1", "SHA224", "SHA256", "SHA384", "SHA512", "DIGEST", "HMAC", "ENCRYPT", "DECRYPT", "GEN_SALT", "CRYPTO"],
  // Other
  other: ["DISTINCT", "ALL", "AS", "ASC", "DESC", "LIMIT", "OFFSET", "UNION", "UNION ALL", "INTERSECT", "EXCEPT", "CROSS JOIN", "NATURAL", "USING", "LATERAL", "WITH", "RECURSIVE", "CTE", "ANALYZE", "EXPLAIN", "VACUUM", "REINDEX", "CLUSTER", "PRECISION", "SCOPE", "GLOBAL", "SESSION", "TEMPORARY", "TEMP", "UNIQUE", "PRIMARY KEY", "FOREIGN KEY", "REFERENCES", "CONSTRAINT", "INDEX", "VIEW", "MATERIALIZED VIEW", "SEQUENCE", "TRIGGER", "PROCEDURE", "FUNCTION", "LANGUAGE", "RETURNS", "RETURNING", "INOUT", "VARIADIC", "OUT", "THROWS", "RAISE", "NOTICE", "NOTICE"],
};

// SQL keywords (DDL, DML, permissions, etc.)
const BASE_KEYWORDS = [
  // DQL
  "SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "AS", "DISTINCT",
  "ORDER BY", "ASC", "DESC", "NULLS FIRST", "NULLS LAST",
  "GROUP BY", "HAVING", "LIMIT", "OFFSET", "FETCH FIRST", "ROWS ONLY",
  // Joins
  "JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "OUTER JOIN",
  "CROSS JOIN", "FULL JOIN", "FULL OUTER JOIN", "LEFT OUTER JOIN",
  "NATURAL JOIN", "NATURAL LEFT JOIN", "NATURAL INNER JOIN",
  "USING", "ON",
  // Subqueries
  "EXISTS", "NOT EXISTS", "IN", "NOT IN", "ANY", "SOME", "ALL",
  "BETWEEN", "NOT BETWEEN", "LIKE", "NOT LIKE", "ILIKE", "NOT ILIKE",
  // DML
  "INSERT INTO", "VALUES", "SET", "UPDATE", "DELETE FROM", "RETURNING",
  // DDL
  "CREATE TABLE", "CREATE TEMPORARY TABLE", "CREATE TABLE IF NOT EXISTS",
  "CREATE OR REPLACE TABLE", "CREATE VIEW", "CREATE MATERIALIZED VIEW",
  "CREATE INDEX", "CREATE UNIQUE INDEX", "CREATE INDEX CONCURRENTLY",
  "CREATE SEQUENCE", "CREATE FUNCTION", "CREATE PROCEDURE",
  "CREATE TRIGGER", "CREATE TYPE", "CREATE SCHEMA", "CREATE DATABASE",
  "CREATE ROLE", "CREATE USER", "CREATE GROUP",
  "ALTER TABLE", "ALTER VIEW", "ALTER INDEX", "ALTER SEQUENCE", "ALTER FUNCTION",
  "ALTER COLUMN", "ADD COLUMN", "DROP COLUMN", "RENAME COLUMN", "DROP TABLE",
  "DROP TABLE IF EXISTS", "DROP VIEW", "DROP INDEX", "DROP SEQUENCE", "DROP FUNCTION",
  "DROP TRIGGER", "DROP TYPE", "DROP SCHEMA", "DROP DATABASE", "DROP ROLE",
  "TRUNCATE", "TRUNCATE TABLE", "RENAME TO", "RENAME", "COMMENT ON",
  // Constraints
  "PRIMARY KEY", "FOREIGN KEY", "REFERENCES", "UNIQUE", "CHECK", "NOT NULL", "NULL",
  "DEFAULT", "AUTO_INCREMENT", "SERIAL", "BIGSERIAL", "IDENTITY", "GENERATED",
  "CONSTRAINT", "CASCADE", "RESTRICT", "NO ACTION", "SET NULL", "SET DEFAULT",
  "DEFERRABLE", "INITIALLY DEFERRED", "INITIALLY IMMEDIATE",
  // Permissions
  "GRANT", "REVOKE", "WITH GRANT OPTION", "WITH ROLE", "WITH ADMIN",
  // Common table expressions
  "WITH", "WITH RECURSIVE", "AS",
  // Window
  "OVER", "PARTITION BY", "ROWS BETWEEN", "RANGE BETWEEN",
  "UNBOUNDED PRECEDING", "UNBOUNDED FOLLOWING", "CURRENT ROW",
  // Table
  "TABLE", "TABLES", "INTO", "FROM", "TO", "IN", "OUT",
  // Transaction
  "BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT", "RELEASE SAVEPOINT",
  "START TRANSACTION", "START TRANSACTION READ ONLY",
  // Other
  "CASE", "WHEN", "THEN", "ELSE", "END", "CAST", "COLLATE",
  "COLLATION", "CONVERT", "MATCH", "FULLTEXT", "SPATIAL",
  "LOCK", "UNLOCK", "ANALYZE", "ANALYZE TABLE", "EXPLAIN", "EXPLAIN ANALYZE",
  "VACUUM", "REINDEX", "CLUSTER", "COPY", "RESET", "SET", "SHOW", "DESCRIBE",
  "DESC", "USE", "ATTACH", "DETACH", "DATABASE", "SCHEMA", "DOMAIN",
  "GENERATED ALWAYS AS IDENTITY", "OVERRIDING SYSTEM VALUE",
];

const OPERATORS = [
  "=", "!=", "<>", "<", ">", "<=", ">=", "+", "-", "*", "/", "%",
  "||", "&&", "!", "~", "!~", "~*", "!~*",
  "::", "->", "->>", "#>", "#>>", "?&", "?|", "@>", "<@",
];

// Database-specific keywords (extending base keywords)
const DB_SPECIFIC_KEYWORDS: Partial<Record<DatabaseType, string[]>> = {
  postgresql: [
    "RETURNING", "ON CONFLICT", "DO UPDATE", "DO NOTHING",
    "INSTEAD OF", "LATERAL", "RETURNING", "WITH ORDINALITY",
    "NOTICE", "RAISE NOTICE", "RAISE EXCEPTION",
    "FETCH FIRST", "WITH TIES", "ONLY",
    "COALESCE", "NULLIF", "GREATEST", "LEAST",
    "TRUE", "FALSE", "UNKNOWN", "BOOLEAN",
    "SERIAL", "BIGSERIAL", "SMALLSERIAL", "UUID", "JSON", "JSONB",
    "XML", "TSVECTOR", "TSQUERY", "INET", "CIDR", "MACADDR",
    "MONEY", "INTERVAL", "ARRAY", "RANGE", "MULTIRANGE",
    "HSTORE", "LTREE", "EXTENSION", "IF EXISTS", "IF NOT EXISTS",
    "UNLOGGED", "TEMP", "TEMPORARY", "UNIQUE INDEX", "EXCLUDE", "USING GIN", "USING BTREE",
    "TABLESPACE", "WITH (", "FILLFACTOR", "GENERATED", "ALWAYS",
    "PARTITION BY", "PARTITION OF", "ATTACH", "DETACH",
    "FOR UPDATE", "FOR SHARE", "NOWAIT", "SKIP LOCKED",
    "SERIALIZABLE", "REPEATABLE READ", "READ COMMITTED", "READ UNCOMMITTED",
    "ISOLATION LEVEL", "DEFERRABLE", "NOT DEFERRABLE",
  ],
  mysql: [
    "LOW_PRIORITY", "HIGH_PRIORITY", "DELAYED",
    "IGNORE", "FOR UPDATE", "LOCK IN SHARE MODE",
    "ON DUPLICATE KEY UPDATE", "INSERT IGNORE", "REPLACE INTO",
    "DISTINCTROW", "STRAIGHT_JOIN", "SQL_BIG_RESULT", "SQL_SMALL_RESULT",
    "SQL_BUFFER_RESULT", "SQL_CACHE", "SQL_NO_CACHE", "SQL_CALC_FOUND_ROWS",
    "PARTITION BY", "PARTITION", "SUBPARTITION",
    "ENGINE", "CHARSET", "COLLATE", "COLLATION",
    "AUTO_INCREMENT", "KEY", "UNIQUE KEY", "FULLTEXT", "SPATIAL",
    "ENUM", "SET", "JSON", "LONGTEXT", "MEDIUMTEXT", "TINYTEXT",
    "VARBINARY", "LONGBLOB", "MEDIUMBLOB", "TINYBLOB", "BLOB",
    "ZEROFILL", "UNSIGNED", "SIGNED", "ON UPDATE", "ON DELETE",
    "MATCH AGAINST", "SOUNDS LIKE",
  ],
  sqlite: [
    "IF NOT EXISTS", "IF EXISTS", "OR ABORT", "OR FAIL", "OR IGNORE", "OR REPLACE", "OR ROLLBACK",
    "AUTOINCREMENT", "GENERATED ALWAYS", "VIRTUAL", "USING", "WITHOUT ROWID",
    "STRICT", "DELETE FROM", "ATTACH DATABASE", "DETACH DATABASE",
    "REINDEX", "ANALYZE", "PRAGMA", "VACUUM INTO",
    "ON CONFLICT", "CONFLICT", "REPLACE", "IGNORE", "ABORT", "FAIL", "ROLLBACK",
    "NULLS FIRST", "NULLS LAST", "NULLS", "COVERING", "INDEXED BY",
  ],
  mssql: [
    "TOP", "WITH TIES", "PERCENT", "NOLOCK", "ROWLOCK",
    "UPDLOCK", "XLOCK", "PAGLOCK", "HOLDLOCK", "READUNCOMMITTED", "READCOMMITTED",
    "REPEATABLEREAD", "SERIALIZABLE", "READ PAST", "READ COMMITTED SNAPSHOT",
    "OUTPUT", "INTO", "MERGE", "WHEN MATCHED", "WHEN NOT MATCHED",
    "WAITFOR", "DELAY", "RETRY", "GO", "SEQUENCE", "NEXT VALUE FOR",
    "IDENTITY", "SCOPE_IDENTITY", "OBJECT_ID", "SCHEMA_NAME", "TYPE_NAME",
    "NTILE", "OVER (", "PIVOT", "UNPIVOT", "CROSS APPLY", "OUTER APPLY",
    "OPTION", "FORCE ORDER", "LOOP JOIN", "HASH JOIN", "MERGE JOIN",
    "SET XACT_ABORT", "SET IMPLICIT_TRANSACTIONS",
  ],
  clickhouse: [
    "FINAL", "SAMPLE", "SAMPLE BY", "PREWHERE", "SETTINGS",
    "ARRAY JOIN", "GLOBAL", "ANY", "ALL", "ANY LEFT JOIN", "ANY INNER JOIN",
    "ASOF", "ARRAY", "TUPLE", "MAP", "FIXEDSTRING", "ENUM", "ENUM8", "ENUM16",
    "NESTED", "MATERIALIZED", "ALIAS", "EPHEMERAL", "DEFAULT", "CODEC",
    "COMPRESSION", "TTL", "DEDUPLICATE", "CLUSTER BY", "DATABASE",
    "ENGINE", "ORDER BY", "PRIMARY KEY", "SAMPLE BY",
    "PARTITION BY", "LIMIT BY", "LIMIT", "OFFSET", "FORMAT",
    "SELECT", "INSERT", "CREATE", "DROP", "ALTER", "TRUNCATE", "OPTIMIZE",
    "ATTACH", "DETACH", "EXISTS", "RENAME", "SHOW", "DESCRIBE", "CHECK",
    "EXPLAIN", "KILL", "SYSTEM", "GRANT", "REVOKE", "ROLE", "QUOTA",
    "USING", "WITH TOTALS", "TOTALS", "HAVING", "SUBSTRING", "SUBSTR",
  ],
  mariadb: [
    "LOW_PRIORITY", "HIGH_PRIORITY", "DELAYED", "IGNORE",
    "ON DUPLICATE KEY UPDATE", "INSERT IGNORE", "REPLACE INTO",
    "DISTINCTROW", "STRAIGHT_JOIN", "FOR UPDATE", "LOCK IN SHARE MODE",
    "PARTITION BY", "PARTITION", "SUBPARTITION",
    "ENGINE", "CHARSET", "COLLATE", "AUTO_INCREMENT",
    "ENUM", "SET", "JSON", "LONGTEXT", "MEDIUMTEXT", "TINYTEXT",
    "ZEROFILL", "UNSIGNED", "SIGNED",
    "MATCH AGAINST", "SEQUENCE", "NEXT VALUE",
    "OVER", "PARTITION BY", "LAG", "LEAD", "ROW_NUMBER", "RANK", "DENSE_RANK",
    "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE",
  ],
  duckdb: [
    "FROM", "SELECT", "WHERE", "ORDER BY", "LIMIT", "OFFSET", "FETCH",
    "GROUP BY", "HAVING", "WINDOW", "QUALIFY", "PARTITION BY",
    "JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "OUTER JOIN", "CROSS JOIN", "NATURAL JOIN", "ASOF JOIN",
    "INSERT INTO", "VALUES", "UPDATE", "DELETE FROM",
    "CREATE TABLE", "CREATE TABLE IF NOT EXISTS", "CREATE VIEW", "CREATE SCHEMA",
    "CREATE INDEX", "CREATE SEQUENCE", "CREATE MACRO", "CREATE FUNCTION",
    "DROP TABLE", "DROP VIEW", "DROP INDEX", "DROP SEQUENCE", "DROP SCHEMA",
    "ALTER TABLE", "ALTER VIEW",
    "USING", "PIVOT", "UNPIVOT", "SAMPLE", "USING SAMPLE",
    "TABLESAMPLE", "BERNOULLI", "SYSTEM", "RESERVOIR",
    "COPY", "EXPORT", "IMPORT", "LOAD",
    "PRAGMA", "VACUUM", "ANALYZE", "EXPLAIN", "PROFILE",
    "STRUCT", "MAP", "LIST", "UNION", "INTERSECT", "EXCEPT",
    "ILIKE", "REGEXP_MATCHES", "REGEXP_REPLACE", "REGEXP_SPLIT_TO_ARRAY",
    "TRY_CAST", "TRY", "COALESCE", "NULLIF", "IFNULL",
    "GENERATED", "AS", "BY", "IF", "CASE", "WHEN", "THEN", "ELSE", "END",
  ],
  cassandra: [
    "INSERT INTO", "UPDATE", "DELETE FROM", "SELECT",
    "USING TIMESTAMP", "USING TTL", "IF EXISTS", "IF NOT EXISTS",
    "AND", "SET", "WHERE", "PRIMARY KEY", "WITH", "AND",
    "CREATE KEYSPACE", "CREATE TABLE", "CREATE INDEX", "CREATE MATERIALIZED VIEW",
    "ALLOW FILTERING", "TOKEN", "WRITETIME", "TTL",
    "COUNTER", "STATIC", "FROZEN", "TYPE", "DROP KEYSPACE", "DROP TABLE",
    "ALTER TABLE", "ADD", "DROP", "RENAME",
  ],
  snowflake: [
    "SELECT", "FROM", "WHERE", "ORDER BY", "LIMIT", "OFFSET",
    "GROUP BY", "HAVING", "QUALIFY", "PARTITION BY", "ORDER BY",
    "JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN", "CROSS JOIN",
    "INSERT INTO", "VALUES", "UPDATE", "DELETE FROM", "MERGE INTO",
    "CREATE TABLE", "CREATE VIEW", "CREATE OR REPLACE", "CREATE SEQUENCE",
    "ALTER TABLE", "ALTER VIEW",
    "USING", "USING (", "ON", "WHEN", "THEN", "ELSE", "END",
    "WITH", "RECURSIVE", "AS",
    "EXISTS", "IN", "BETWEEN", "LIKE", "ILIKE", "NOT",
    "TRUE", "FALSE", "NULL",
    "QUALIFY", "WINDOW", "CLUSTER BY", "MACRO", "STAGE", "FILE FORMAT",
    "COPY INTO", "PUT", "GET", "LIST", "REMOVE",
    "GRANT", "REVOKE", "ROLE", "USER", "PRIVILEGE", "SHARE",
    "WAREHOUSE", "DATABASE", "SCHEMA", "TABLE", "VIEW", "SEQUENCE", "FUNCTION", "PROCEDURE",
    "COMMENT", "TAG", "ROW ACCESS POLICY", "MASKING POLICY",
    "HYBRID TABLE", "ICEBERG TABLE", "DYNAMIC TABLE",
    "USING TIMESTAMP", "AT", "BEFORE", "CHANGES", "CONNECT_BY_ISCYCLE", "CONNECT_BY_ISLEAF",
  ],
  mongodb: [
    "INSERT", "UPDATE", "DELETE", "FIND", "FINDONE", "COUNT",
    "DISTINCT", "AGGREGATE", "MAPREDUCE", "GROUP", "GEONEAR", "GEOSEARCH",
    "CREATE", "CREATEINDEX", "DROP", "DROPINDEX",
    "COLLATION", "ARRAY", "ELEMENT", "EVALUATION", "COMMENT",
    "PROJECTION", "MATCH", "GROUP", "SORT", "LIMIT", "SKIP", "SAMPLE",
    "LOOKUP", "UNWIND", "FACET", "BUCKET", "BUCKETAUTO", "SORTBYCOUNT",
    "MAX", "MIN", "AVG", "SUM", "STDDEV_POP", "STDDEV_SAMP",
    "FIRST", "LAST", "PUSH", "ADDTOSET", "EXPRESSION",
    "$expr", "$jsonSchema", "$text", "$where", "$meta", "$mod", "$regex",
    "$type", "$exists", "$all", "$size", "$elemMatch", "$bitsAllClear", "$bitsAllSet",
  ],
  redis: [
    "SELECT", "FLUSHDB", "FLUSHALL", "DBSIZE", "BGSAVE", "LASTSAVE", "KEYS", "SCAN",
    "TYPE", "EXISTS", "OBJECT", "RANDOMKEY", "RENAME", "RENAMENX", "TOUCH",
    "DEL", "UNLINK", "EXPIRE", "EXPIREAT", "PEXPIRE", "PEXPIREAT", "TTL", "PTTL", "PERSIST",
    "GET", "SET", "SETNX", "SETEX", "SETRANGE", "GETSET", "MGET", "MSET", "MSETNX",
    "APPEND", "BITCOUNT", "BITOP", "BITPOS", "BITFIELD", "GETRANGE", "SETRANGE",
    "INCR", "INCRBY", "INCRBYFLOAT", "DECR", "DECRBY", "GETBIT",
    "HSET", "HGET", "HGETALL", "HMGET", "HMSET", "HSETNX", "HLEN", "HSTRLEN",
    "HDEL", "HEXISTS", "HKEYS", "HVALS", "HINCRBY", "HINCRBYFLOAT",
    "HSCAN", "HGET", "HRANDFIELD", "HRANDFIELD", "HSUBSTR",
    "LPUSH", "RPUSH", "LPOP", "RPOP", "LINSERT", "LLEN", "LINDEX", "LRANGE", "LREM", "LSET", "LTRIM", "LMOVE", "BLMOVE",
    "SADD", "SREM", "SPOP", "SMEMBERS", "SISMEMBER", "SCARD", "SRANDMEMBER", "SMISMEMBER",
    "SINTER", "SUNION", "SDIFF", "SINTERSTORE", "SUNIONSTORE", "SDIFFSTORE",
    "SSCAN", "SMEMBERS",
    "ZADD", "ZREM", "ZINCRBY", "ZRANGE", "ZREVRANGE", "ZRANGEBYSCORE", "ZREVRANGEBYSCORE",
    "ZRANK", "ZREVRANK", "ZCARD", "ZSCORE", "ZCOUNT", "ZRANGEBYLEX", "ZREVRANGEBYLEX",
    "ZLEXCOUNT", "ZREMRANGEBYLEX", "ZREMRANGEBYRANK", "ZREMRANGEBYSCORE",
    "ZSCAN", "ZPOPMIN", "ZPOPMAX", "BZPOPMIN", "BZPOPMAX",
    "ZINTER", "ZUNION", "ZINTERSTORE", "ZUNIONSTORE", "ZDIFF", "ZDIFFSTORE",
    "ZINTERCARD", "ZMAX", "ZMIN", "ZRANDBYSCORE",
    "PFADD", "PFCOUNT", "PFMERGE",
    "GEOADD", "GEOPOS", "GEODIST", "GEORADIUS", "GEORADIUSBYMEMBER", "GEOHASH", "GEOSEARCH", "GEOSEARCHSTORE",
    "STREAM", "XADD", "XTRIM", "XDEL", "XLEN", "XRANGE", "XREVRANGE", "XREAD", "XREADGROUP",
    "XGROUP", "XACK", "XCLAIM", "XINFO", "XSETID",
    "WAIT", "WAITAOF", "CLUSTER ADDSLOTS", "CLUSTER DELSLOTS", "CLUSTER INFO",
    "CLUSTER MEET", "CLUSTER FORGET", "CLUSTER REPLICATE", "CLUSTER SLAVES",
    "SCRIPT EXISTS", "SCRIPT LOAD", "SCRIPT DEBUG", "SCRIPT KILL", "EVALSHA", "EVAL",
    "MULTI", "EXEC", "DISCARD", "WATCH", "UNWATCH",
    "COPY", "MOVE", "RESTORE", "DUMP", "MIGRATE", "ROLE", "SAVE", "SHUTDOWN",
    "ACL", "BF.ADD", "BF.EXISTS", "BF.INFO", "CMS.INCRBY", "CMS.QUERY",
    "TOPK.ADD", "TOPK.QUERY", "TOPK.INFO", "TDIGEST.ADD", "TDIGEST.BYRANK",
  ],
  bigquery: [
    "SELECT", "FROM", "WHERE", "ORDER BY", "LIMIT", "OFFSET",
    "GROUP BY", "HAVING", "QUALIFY", "PARTITION BY", "ORDER BY",
    "JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN", "CROSS JOIN",
    "INSERT INTO", "VALUES", "UPDATE", "DELETE FROM", "MERGE INTO",
    "CREATE TABLE", "CREATE TABLE IF NOT EXISTS", "CREATE VIEW", "CREATE OR REPLACE VIEW",
    "CREATE FUNCTION", "CREATE TEMP FUNCTION", "CREATE TABLE FUNCTION",
    "ALTER TABLE", "ALTER VIEW",
    "CREATE SCHEMA", "CREATE ROW ACCESS POLICY",
    "EXPORT DATA", "IMPORT DATA",
    "WITH", "AS",
    "STRUCT", "ARRAY", "MAP", "UNNEST", "FLATTEN",
    "EXISTS", "IN", "BETWEEN", "LIKE", "NOT",
    "TRUE", "FALSE", "NULL",
    "QUALIFY", "WINDOW", "ROWS BETWEEN", "RANGE BETWEEN",
    "OVER", "UNBOUNDED PRECEDING", "UNBOUNDED FOLLOWING", "CURRENT ROW",
    "PIVOT", "UNPIVOT",
    "SAFE.ORDINAL", "SAFE.CAST", "SAFE_OFFSET", "SAFE.LOWER",
    "FORMAT", "PARSE", "GENERATE_ARRAY", "GENERATE_DATE_ARRAY",
    "CURRENT_DATE", "CURRENT_DATETIME", "CURRENT_TIMESTAMP", "CURRENT_TIME",
    "DATE_ADD", "DATE_SUB", "DATE_DIFF", "DATE_TRUNC", "FORMAT_DATE",
    "TIMESTAMP_ADD", "TIMESTAMP_DIFF", "TIMESTAMP_TRUNC", "TIMESTAMP_MICROS",
    "EXTRACT", "DATE_FROM_UNIX_DATE", "UNIX_DATE", "UNIX_TIMESTAMP",
    "REGEXP_EXTRACT", "REGEXP_CONTAINS", "REGEXP_REPLACE",
    "CONCAT", "FORMAT_JSON", "TO_JSON_STRING", "PARSE_JSON",
    "BIGNUMERIC", "NUMERIC", "INT64", "FLOAT64", "BOOL", "STRING", "BYTES",
    "ARRAY_LENGTH", "ARRAY_VALUE", "ARRAY_TO_STRING", "GENERATE_ARRAY",
    "ANY_VALUE", "ARRAY_AGG", "AVG", "COUNT", "COUNTIF", "MAX", "MIN", "STRING_AGG", "SUM",
    "COALESCE", "IFNULL", "IF", "CASE", "WHEN", "THEN", "ELSE", "END",
    "LOGICAL_AND", "LOGICAL_OR",
  ],
  libsql: [
    "IF NOT EXISTS", "IF EXISTS", "OR ABORT", "OR FAIL", "OR IGNORE", "OR REPLACE", "OR ROLLBACK",
    "AUTOINCREMENT", "GENERATED ALWAYS", "VIRTUAL", "USING",
    "STRICT", "DELETE FROM", "ATTACH DATABASE", "DETACH DATABASE",
    "ON CONFLICT", "REPLACE", "IGNORE", "ABORT", "FAIL",
    "NULLS FIRST", "NULLS LAST",
    "RETURNING", "WITH", "RECURSIVE",
    "FILTER", "OVER", "PARTITION BY",
    "BEFORE", "AFTER", "INSTEAD OF", "EACH", "REFERENCES",
    "RESTRICT", "CASCADE", "SET NULL", "SET DEFAULT", "NO ACTION",
  ],
  cloudflare_d1: [
    "IF NOT EXISTS", "IF EXISTS",
    "RETURNING", "WITH", "RECURSIVE",
    "ATTACH DATABASE", "DETACH DATABASE",
    "DELETE FROM", "UPDATE",
    "ON CONFLICT", "REPLACE", "IGNORE", "ABORT", "FAIL", "ROLLBACK",
    "NULLS FIRST", "NULLS LAST",
    "FILTER", "OVER", "PARTITION BY",
  ],
};

// Database-specific functions
const DB_SPECIFIC_FUNCTIONS: Partial<Record<DatabaseType, string[]>> = {
  postgresql: [
    "gen_random_uuid", "uuid_generate_v4", "uuid_generate_v1", "uuid_generate_v1mc",
    "now", "transaction_timestamp", "statement_timestamp", "clock_timestamp",
    "to_regclass", "to_regnamespace", "to_regrole", "to_regtype",
    "col_description", "obj_description", "shobj_description",
    "pg_column_size", "pg_total_relation_size", "pg_indexes_size", "pg_relation_size",
    "pg_size_pretty", "pg_database_size", "pg_tablespace_size",
    "pg_stat_file", "pg_ls_dir", "pg_read_file", "pg_write_file",
    "current_catalog", "current_schema", "current_schemas", "current_setting",
    "set_config", "reset", "pg_cancel_backend", "pg_terminate_backend",
    "version", "pg_extensions", "pg_available_extensions",
    "inet_server_addr", "inet_server_port", "inet_client_addr", "inet_client_port",
    "pg_blocking_pids", "pg_stat_activity", "pg_stat_get_activity",
    "format", "format_type", "pg_typeof", "pg_get_functiondef",
    "pg_get_constraintdef", "pg_get_indexdef", "pg_get_ruledef", "pg_get_triggerdef",
    "pg_get_expr", "pg_get_serial_sequence", "pg_get_userbyid",
    "make_date", "make_interval", "make_time", "make_timestamp", "make_timestamptz",
    "to_timestamp", "to_char", "to_date", "to_number",
    "jsonb_pretty", "jsonb_set", "jsonb_insert", "jsonb_path_exists",
    "jsonb_path_query", "jsonb_path_query_first", "jsonb_extract_path",
    "jsonb_object_agg", "jsonb_array_elements", "jsonb_array_elements_text",
    "jsonb_each", "jsonb_each_text", "jsonb_delete", "jsonb_delete_path",
    "jsonb_populate_record", "jsonb_to_record", "jsonb_to_recordset",
    "json_object_agg", "json_array_elements", "json_array_elements_text",
    "json_each", "json_each_text", "json_object_keys", "json_typeof",
    "jsonb_typeof", "json_strip_nulls", "jsonb_strip_nulls",
    "json_build_object", "jsonb_build_object", "json_build_array", "jsonb_build_array",
    "row_to_json", "array_to_json", "json_agg", "jsonb_agg",
    "tsvector_init", "tsvector_update_trigger", "tsvector_to_array",
    "to_tsvector", "to_tsquery", "phraseto_tsquery", "websearch_to_tsquery",
    "ts_rank", "ts_rank_cd", "ts_headline", "ts_debug",
    "ts_match", "ts_match_q", "ts_match_vq",
    "xmlagg", "xmlcomment", "xmlconcat", "xmlelement", "xmlforest", "xmlpi",
    "xmlroot", "xmlserialize", "xpath", "xpath_exists",
    "text2ltree", "ltree2text", "subltree", "subpath", "nlevel", "index",
    "text2array", "array2text", "array_cat", "array_upper", "array_lower",
    "array_position", "array_positions", "array_remove", "array_replace",
    "array_prepend", "array_append", "array_ndims", "array_dims",
    "unnest", "generate_series", "generate_subscripts",
    "dense_rank", "percent_rank", "cume_dist", "ntile",
    "lag", "lead", "first_value", "last_value", "nth_value",
    "row_security_active", "has_table_privilege", "has_column_privilege",
    "has_any_column_privilege", "has_function_privilege", "has_schema_privilege",
    "has_database_privilege", "has_server_privilege", "has_sequence_privilege",
    "has_type_privilege", "has_language_privilege",
    "pg_has_role", "pg_function_is_visible", "pg_table_is_visible", "pg_type_is_visible",
    "aclexplode", "aclcontains", "makeaclitem", "session_user", "current_user",
    "inet_aton", "inet_ntoa", "inet_same_family", "inet_merge",
    "network", "broadcast", "host", "netmask", "network_size",
    "macaddr8_set7bit",
  ],
  mysql: [
    "IFNULL", "NULLIF", "ISNULL", "COALESCE", "IF", "IIF",
    "CAST", "CONVERT", "BIN", "HEX", "UNHEX", "CHARSET", "COLLATION",
    "DATE", "DATEDIFF", "DATE_ADD", "DATE_SUB", "DATE_FORMAT", "DATE_FORMAT",
    "DATE_ADD", "ADDDATE", "SUBDATE", "ADDTIME", "SUBTIME", "TIMEDIFF",
    "TIMESTAMP", "TIMESTAMPADD", "TIMESTAMPDIFF", "FROM_DAYS", "TO_DAYS",
    "FROM_UNIXTIME", "UNIX_TIMESTAMP", "SEC_TO_TIME", "TIME_TO_SEC",
    "GET_FORMAT", "STR_TO_DATE", "MAKEDATE", "MAKETIME", "PERIOD_ADD", "PERIOD_DIFF",
    "WEEKDAY", "DAYOFMONTH", "DAYOFWEEK", "DAYOFYEAR", "MONTH", "QUARTER", "YEAR",
    "DAY", "HOUR", "MINUTE", "SECOND", "MICROSECOND", "LAST_DAY",
    "NOW", "SYSDATE", "CURDATE", "CURTIME", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP",
    "CONCAT", "CONCAT_WS", "SUBSTRING", "SUBSTRING_INDEX", "LEFT", "RIGHT",
    "LENGTH", "CHAR_LENGTH", "CHARACTER_LENGTH", "INSTR", "LOCATE", "POSITION",
    "LPAD", "RPAD", "LTRIM", "RTRIM", "TRIM", "REPLACE", "REVERSE", "REPEAT",
    "SPACE", "STRCMP", "FIND_IN_SET", "FORMAT", "UPPER", "LOWER", "ELT", "EXPORT_SET",
    "MD5", "SHA1", "SHA2", "SHA", "PASSWORD", "ENCRYPT", "DECODE", "COMPRESS", "UNCOMPRESS",
    "AES_ENCRYPT", "AES_DECRYPT", "DES_DECRYPT", "DES_ENCRYPT",
    "GROUP_CONCAT", "JSON_ARRAY", "JSON_OBJECT", "JSON_QUERY", "JSON_VALUE",
    "JSON_EXTRACT", "JSON_UNQUOTE", "JSON_SET", "JSON_INSERT", "JSON_REPLACE", "JSON_REMOVE",
    "JSON_MERGE", "JSON_MERGE_PATCH", "JSON_MERGE_PRESERVE", "JSON_KEYS", "JSON_LENGTH",
    "JSON_CONTAINS", "JSON_CONTAINS_PATH", "JSON_DEPTH", "JSON_TYPE", "JSON_VALID", "JSON_ARRAY_APPEND",
    "JSON_ARRAY_INSERT", "JSON_SEARCH", "JSON_OVERLAPS", "JSON_EQUALS",
    "ROW_COUNT", "LAST_INSERT_ID", "FOUND_ROWS", "ROW_NUMBER", "RANK", "DENSE_RANK",
    "PERCENT_RANK", "CUME_DIST", "NTILE", "LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE",
    "COALESCE", "GREATEST", "LEAST", "INTERVAL", "MOD", "POW", "POWER", "SQRT", "ABS",
    "CEIL", "CEILING", "FLOOR", "ROUND", "TRUNCATE", "LOG", "LOG10", "LOG2", "LN", "EXP",
    "SIGN", "RAND", "RANDOM", "ACOS", "ASIN", "ATAN", "ATAN2", "COS", "COT", "SIN", "TAN",
    "PI", "RADIANS", "DEGREES", "CRC32", "POW", "WEEK", "YEARWEEK",
    "EXISTS", "IN", "BETWEEN", "IS", "ISNULL", "LIKE", "NOT", "OR", "AND", "XOR",
    "BINARY", "ASCII", "CHAR", "CHAR_LENGTH", "SOUNDEX", "DIFFERENCE",
    "WEIGHT_STRING", "INET_ATON", "INET_NTOA", "INET6_ATON", "INET6_NTOA",
    "IS_IPV4", "IS_IPV4_COMPAT", "IS_IPV4_MAPPED", "IS_IPV6", "IS_IPV4_MAPPED",
    "UUID", "UUID_SHORT", "GET_LOCK", "RELEASE_LOCK", "IS_FREE_LOCK", "IS_USED_LOCK",
    "BENCHMARK", "SLEEP", "GEOMFROMWKB", "GEOMFROMWKT", "ST_GEOMFROMWKB", "ST_GEOMFROMWKT",
    "ST_AsText", "ST_AsWKB", "ST_AsWKT", "ST_AsGeoJSON",
    "ST_Distance", "ST_Distance_Sphere", "ST_Contains", "ST_Within",
    "ST_Intersects", "ST_Crosses", "ST_Disjoint", "ST_Overlaps", "ST_Touches",
    "ST_Centroid", "ST_Envelope", "ST_StartPoint", "ST_EndPoint", "ST_PointN",
    "ST_Length", "ST_Area", "ST_ExteriorRing", "ST_InteriorRings",
  ],
  clickhouse: [
    "now", "now64", "today", "yesterday", "tomorrow",
    "toDate", "toDateTime", "toDateTime64", "toTime", "toYear", "toMonth",
    "toDayOfMonth", "toDayOfWeek", "toQuarter", "toHour", "toMinute", "toSecond", "toMillisecond",
    "toUnixTimestamp", "fromUnixTimestamp", "toStartOfDay", "toStartOfMonth", "toStartOfYear",
    "toStartOfWeek", "toStartOfQuarter", "toIntervalSecond", "toIntervalMinute",
    "toIntervalHour", "toIntervalDay", "toIntervalWeek", "toIntervalMonth", "toIntervalQuarter", "toIntervalYear",
    "dateDiff", "dateDiff64", "dateAdd", "dateSub", "dateTrunc", "timestampAdd", "timestampDiff",
    "subtractDays", "subtractMonths", "subtractYears", "subtractHours", "subtractMinutes", "subtractSeconds",
    "addDays", "addMonths", "addYears", "addHours", "addMinutes", "addSeconds",
    "formatDateTime", "parseDateTime", "parseDateTime64BestEffort", "toString",
    "toFixedString", "toStringCutToZero", "toUUID", "toIPv4", "toIPv6",
    "toFloat32", "toFloat64", "toInt8", "toInt16", "toInt32", "toInt64",
    "toUInt8", "toUInt16", "toUInt32", "toUInt64", "toDecimal", "toDecimal32", "toDecimal64", "toDecimal128",
    "toJSONString", "toJSONStringEachRow", "toJSONStringEachRowWithNamesAndTypes",
    "fromJSONString", "fromJSONStringEachRow", "fromJSONStringEachRowRaw",
    "JSONExtract", "JSONExtractString", "JSONExtractInt", "JSONExtractFloat", "JSONExtractBool",
    "JSONLength", "JSONType", "JSONKey", "JSONHas", "JSONDelete", "JSONSet", "JSONInsert", "JSONMerge",
    "array", "arrayElement", "arrayElement", "has", "hasAll", "hasAny", "hasSubstr",
    "arrayCount", "arraySum", "arrayAvg", "arrayMin", "arrayMax", "arrayFirst", "arrayLast",
    "arrayFilter", "arrayMap", "arrayFlatMap", "arraySort", "arrayReverseSort", "arrayDistinct",
    "arrayEnumerate", "arrayEnumerateDense", "arrayEnumerateUniq",
    "arrayZip", "arrayIntercalate", "arrayConcat", "arrayPushBack", "arrayPushFront",
    "arrayPopBack", "arrayPopFront", "arrayResize", "arrayFill", "arrayDifference", "arrayCumulativeSum",
    "tuple", "tupleElement", "tupleToNameValuePairs", "untuple",
    "map", "mapKeys", "mapValues", "mapContains", "mapAdd", "mapSubtract", "mapPopulateSeries",
    "bitmapAnd", "bitmapOr", "bitmapXor", "bitmapAndNot", "bitmapBuild", "bitmapToArray",
    "bitmapHasAll", "bitmapHasAny", "bitmapCardinality", "bitmapAndCardinality",
    "groupArray", "groupUniqArray", "groupBitmap", "groupBitmapAnd", "groupBitmapOr", "groupBitmapXor",
    "quantile", "quantileExact", "quantileTiming", "quantileDeterministic", "quantileTDigest", "quantileBFloat16",
    "quantiles", "quantilesExact", "quantilesTiming", "quantilesDeterministic", "quantilesTDigest", "quantilesBFloat16",
    "median", "mean", "skewPop", "skewSamp", "kurtPop", "kurtSamp",
    "corr", "covarPop", "covarSamp", "corr", "spearmansRho", "pearsonsRho",
    "entropy", "sumMap", "topK", "topKWeighted", "histogram", "arrayHistogram",
    "runningAccumulate", "runningDifference", "runningDifferenceStartingWithFirstValue",
    "windowFunnel", "retention", "sequenceCount", "sequenceMatch", "sequenceDetect",
    "ICalToUnixTimestamp", "UnixTimestampToICal",
    "timezoneOf", "timezoneName", "timezoneOffset", "toTimeZone", "timeSlots",
    "toYYYYMM", "toYYYYMMDD", "toYYYYMMDDhhmmss", "formatRow",
    "visitParamExtractString", "visitParamExtractInt", "visitParamExtractFloat", "visitParamHas",
    "JSONHas", "JSONExtractString", "JSONExtractInt", "JSONExtractFloat", "JSONExtractBool",
    "normalizeQuery", "defaultValueOfArgumentType", "resetProfileDescription",
  ],
  snowflake: [
    "CURRENT_DATE", "CURRENT_TIMESTAMP", "CURRENT_TIME", "CURRENT_VERSION", "CURRENT_ACCOUNT", "CURRENT_USER",
    "CURRENT_ROLE", "CURRENT_WAREHOUSE", "CURRENT_DATABASE", "CURRENT_SCHEMA", "SESSION_USER",
    "TO_DATE", "TO_TIME", "TO_TIMESTAMP", "TO_TIMESTAMP_NTZ", "TO_TIMESTAMP_LTZ", "TO_TIMESTAMP_TZ",
    "TO_CHAR", "TO_NUMBER", "TO_VARCHAR", "TO_BINARY", "TO_VARIANT",
    "PARSE_IP", "PARSE_URL", "PARSE_JSON", "PARSE_XML", "STRIP_NULL_VALUE",
    "DATE_FROM_PARTS", "TIME_FROM_PARTS", "TIMESTAMP_FROM_PARTS", "TIMESTAMP_NTZ_FROM_PARTS", "TIMESTAMP_LTZ_FROM_PARTS",
    "DATE_TRUNC", "TIME_TRUNC", "TIMESTAMP_TRUNC", "YEAROFWEEK", "YEAROFWEEKISO", "YEAROFYEAR",
    "MONTHNAME", "DAYNAME", "DAYOFMONTH", "DAYOFWEEK", "DAYOFWEEKISO", "DAYOFYEAR", "WEEKOFYEAR", "WEEKISO", "WEEK", "QUARTER",
    "ADD_MONTHS", "MONTHS_BETWEEN", "NEXT_DAY", "PREV_DAY", "DATEADD", "DATE_DIFF",
    "DATE_ADD", "DATE_SUB", "DATEDIFF", "TIMESTAMPADD", "TIMESTAMPDIFF",
    "LAST_DAY", "CONVERT_TIMEZONE", "CONVERT_TIMEZONE",
    "DATE_PART", "DATE_TRUNC", "EXTRACT", "DATE_TRUNC",
    "ARRAY_AGG", "ARRAY_APPEND", "ARRAY_CAT", "ARRAY_CONSTRUCT", "ARRAY_CONSTRUCT_COMPACT",
    "ARRAY_CONTAINS", "ARRAY_INSERT", "ARRAY_INTERSECTION", "ARRAY_LENGTH", "ARRAY_POSITION",
    "ARRAY_PREPEND", "ARRAY_REMOVE", "ARRAY_REPEAT", "ARRAY_SLICE", "ARRAY_SORT", "ARRAY_TO_LIST",
    "ARRAY_UNIQUE_AGG", "FLATTEN", "GET", "OBJECT_CONSTRUCT", "OBJECT_CONSTRUCT_KEEP_NULL",
    "OBJECT_DELETE", "OBJECT_INSERT", "OBJECT_KEYS", "OBJECT_PICK", "OBJECT_VALUES", "STRIP_NULL_VALUE",
    "JSON_EXTRACT_PATH_TEXT", "JSON_EXTRACT_PATH", "JSON_ARRAY_ELEMENTS", "ARRAY_SIZE", "CARDINALITY",
    "CHECK_JSON", "PARSE_JSON", "STRIP_NULL_VALUE", "TRY_CAST", "TRY_TO_*", "TO_JSON", "ARRAY_CONSTRUCT",
    "IFF", "IFFN", "COALESCE", "NULLIF", "NVL", "NVL2", "GREATEST", "LEAST", "DECODE", "WHEN", "THEN", "ELSE",
    "SPLIT", "SPLIT_PART", "SPLIT_TO_TABLE", "STRTOK", "STRTOK_SPLIT_TO_TABLE",
    "REGEXP", "REGEXP_COUNT", "REGEXP_EXTRACT", "REGEXP_EXTRACT_ALL", "REGEXP_INSTR", "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_SUBSTR",
    "CONCAT", "CONCAT_WS", "LEFT", "RIGHT", "LPAD", "RPAD", "LTRIM", "RTRIM", "TRIM", "REPLACE", "TRANSLATE",
    "UPPER", "LOWER", "INITCAP", "LENGTH", "LEN", "CHAR_LENGTH", "CHARACTER_LENGTH",
    "SUBSTR", "SUBSTRING", "POSITION", "CHARINDEX", "STRCMP", "SOUNDEX", "DIFFERENCE",
    "MD5", "MD5_HEX", "SHA1", "SHA1_HEX", "SHA2", "SHA2_HEX", "ENCRYPT", "DECRYPT", "ENCRYPT_RAW", "DECRYPT_RAW",
    "BASE64_ENCODE", "BASE64_DECODE", "HEX_ENCODE", "HEX_DECODE",
    "TO_XML", "XMLGET", "XMLAGG",
    "BITAND", "BITOR", "BITXOR", "BITNOT", "BITCOUNT", "GETBIT", "BITMAP_BUCKET_NUMBER", "BITMAP_CONSTRUCT_AGGR", "BITMAP_OR_AGGR",
    "APPROX_COUNT_DISTINCT", "APPROX_INTEGRAL", "APPROX_PERCENTILE", "APPROX_TOP_K",
    "CORR", "COVAR_POP", "COVAR_SAMP", "REGR_AVGX", "REGR_AVGY", "REGR_COUNT", "REGR_INTERCEPT",
    "REGR_R2", "REGR_SLOPE", "REGR_SXX", "REGR_SXY", "REGR_SYY",
    "COUNT", "COUNT_IF", "GROUPING", "GROUPING_ID", "MAX", "MIN", "SUM", "AVG", "LISTAGG", "STRING_AGG",
    "HASH", "HASH_AGG", "HASH_AGG", "MURMUR3", "MURMUR3_128",
    "QUALIFY", "QUALIFY", "ROW_NUMBER", "RANK", "DENSE_RANK", "PERCENT_RANK", "CUME_DIST", "NTILE",
    "LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE",
    "ANY_VALUE", "ARRAY_AGG", "AVG", "COUNT", "LISTAGG", "MAX", "MIN", "STDDEV", "STDDEV_POP", "STDDEV_SAMP", "SUM", "VARIANCE", "VARIANCE_POP", "VARIANCE_SAMP",
    "OBJECT_CONSTRUCT", "ARRAY_CONSTRUCT", "TO_ARRAY", "TO_OBJECT", "TO_VARIANT",
    "ARRAY_SIZE", "ARRAY_DISTANCE", "ARRAY_INTERSECTION",
    "ARRAY_SORT", "ARRAY_FLATTEN", "ARRAY_COMPACT",
  ],
  bigquery: [
    "ARRAY_AGG", "ARRAY_CONCAT", "ARRAY_LENGTH", "ARRAY_TO_STRING", "ARRAY_VALUE",
    "GENERATE_ARRAY", "GENERATE_DATE_ARRAY", "GENERATE_TIMESTAMP_ARRAY",
    "UNNEST", "FLATTEN",
    "CURRENT_DATE", "CURRENT_DATETIME", "CURRENT_TIMESTAMP", "CURRENT_TIME", "CURRENT_VERSION", "CURRENT_RESOURCE",
    "DATE", "DATETIME", "TIMESTAMP", "TIME",
    "DATE_ADD", "DATE_SUB", "DATE_DIFF", "DATE_TRUNC", "DATE_FROM_UNIX_DATE", "DATE_IN", "DATE_DIFF",
    "DATETIME_ADD", "DATETIME_SUB", "DATETIME_DIFF", "DATETIME_TRUNC",
    "TIMESTAMP_ADD", "TIMESTAMP_SUB", "TIMESTAMP_DIFF", "TIMESTAMP_TRUNC",
    "EXTRACT", "FORMAT_DATE", "FORMAT_DATETIME", "FORMAT_TIME", "FORMAT_TIMESTAMP",
    "PARSE_DATE", "PARSE_DATETIME", "PARSE_TIME", "PARSE_TIMESTAMP",
    "TIMESTAMP", "TIMESTAMP_MICROS", "TIMESTAMP_MILLIS", "TIMESTAMP_SECONDS", "TIMESTAMP_FROM_UNIX_HOURS",
    "TIMESTAMP_FROM_UNIX_MILLIS", "TIMESTAMP_FROM_UNIX_MICROS", "TIMESTAMP_FROM_UNIX_SECONDS",
    "UNIX_MICROS", "UNIX_MILLIS", "UNIX_SECONDS", "UNIX_DATE",
    "FORMAT", "PARSE", "SAFE_CAST", "CAST", "CONVERT",
    "STRING", "INT64", "INT32", "UINT64", "UINT32", "UINT16", "UINT8", "INT16", "INT8",
    "FLOAT64", "FLOAT32", "NUMERIC", "BIGNUMERIC", "BOOL", "BYTES", "DATE", "DATETIME", "TIME", "TIMESTAMP", "INTERVAL",
    "STRUCT", "ARRAY", "MAP",
    "CONCAT", "CONCAT_WS", "LENGTH", "LOWER", "LPAD", "LTRIM", "REGEXP_CONTAINS", "REGEXP_EXTRACT", "REGEXP_EXTRACT_ALL", "REGEXP_REPLACE",
    "REPLACE", "REPEAT", "REVERSE", "RIGHT", "RPAD", "RTRIM", "SPLIT", "STARTS_WITH", "STRPOS", "SUBSTR", "SUBSTRING",
    "TRIM", "UNICODE", "UPPER", "FORMAT", "PARSE", "SOUNDEX",
    "IFNULL", "COALESCE", "IF", "CASE", "WHEN", "THEN", "ELSE", "END",
    "MAX", "MIN", "AVG", "COUNT", "COUNTIF", "SUM", "ANY_VALUE", "ARRAY_AGG", "STRING_AGG", "GROUP_CONCAT",
    "LOGICAL_AND", "LOGICAL_OR",
    "CORR", "COVAR_POP", "COVAR_SAMP", "STDDEV", "STDDEV_POP", "STDDEV_SAMP", "STDDEV_POP", "STDDEV_SAMP",
    "VARIANCE", "VARIANCE_POP", "VENSION_SAMP",
    "ABS", "ABS_MOD", "ACOS", "ACOSH", "ASIN", "ASINH", "ATAN", "ATAN2", "ATANH", "CBRT", "CEIL", "CEILING",
    "COS", "COSH", "DEGREES", "DIV", "EXP", "FLOOR", "GREATEST", "IEEE_DIVIDE", "IS_INF", "IS_NAN", "LEAST", "LN", "LOG", "LOG10",
    "MOD", "NEXT_AFTER", "PARITY", "PI", "POW", "POWER", "RAND", "RANGE_BUCKET", "ROUND", "SIGN", "SIN", "SINH",
    "SQRT", "TAN", "TANH", "TRUNC", "TRUNCATE",
    "MD5", "SHA1", "SHA256", "SHA512", "HMAC_SHA256", "HMAC_SHA512",
    "TO_JSON_STRING", "PARSE_JSON", "SAFE.JSON_TYPE",
    "ST_GEOCODE", "ST_BREAKLINE", "ST_BOUNDARY", "ST_CENTROID", "ST_CLOSESTPOINT", "ST_CLOSESTPOINTS",
    "ST_CONTAINS", "ST_DIFFERENCE", "ST_DIMENSION", "ST_DISJOINT", "ST_DISTANCE", "ST_DUMP", "ST_DWITHIN",
    "ST_ENDPOINT", "ST_ENVELOPE", "ST_EQUALS", "ST_GEOGFROM", "ST_GEOGFROMGEOJSON", "ST_GEOG_FROM_TEXT",
    "ST_GEOG_POINT", "ST_GEOG_POLYGON", "ST_GEOMFROM", "ST_GEOMFROMGEOJSON", "ST_GEOM_FROM_TEXT",
    "ST_INTERSECTION", "ST_INTERSECTS", "ST_INTERSECTSBOX", "ST_ISCLOSED", "ST_ISCOLLECTION",
    "ST_ISEMPTY", "ST_ISRING", "ST_ISSIMPLE", "ST_LENGTH", "ST_MAXDISTANCE", "ST_NPOINTS",
    "ST_NUMPOINTS", "ST_PERIMETER", "ST_POINTN", "ST_POINTS", "ST_SIMPLIFY", "ST_STARTPOINT",
    "ST_TOUCHES", "ST_UNION", "ST_WITHIN", "ST_X", "ST_Y",
    "ROW_NUMBER", "RANK", "DENSE_RANK", "PERCENT_RANK", "CUME_DIST", "NTILE",
    "LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE",
    "BIT_AND", "BIT_OR", "BIT_XOR", "BIT_COUNT", "LOGICAL_AND", "LOGICAL_OR",
    "ANNOTATE", "CLUSTER", "DETECT_ANOMALIES", "ML_", "SEARCH", "AUTO_CLASSIFIER",
  ],
  duckdb: [
    "now", "current_date", "current_timestamp", "current_time",
    "to_timestamp", "to_date", "to_char", "strftime", "strptime",
    "date_part", "date_trunc", "dateadd", "datediff", "date_sub",
    "make_date", "make_timestamp", "make_interval",
    "age", "isodow", "isoyear", "week", "weekday", "year", "quarter", "month", "day", "hour", "minute", "second", "epoch",
    "array_agg", "list_agg", "array_concat", "array_length", "array_slice", "array_extract",
    "list", "len", "length", "upper", "lower", "trim", "ltrim", "rtrim", "lpad", "rpad",
    "replace", "regexp_replace", "regexp_extract", "regexp_extract_all", "regexp_like",
    "split_part", "string_split", "string_agg", "string_split_regex",
    "concat", "concat_ws", "format", "printf",
    "md5", "sha1", "sha256", "sha384", "sha512", "xxhash64", "ripemd160",
    "uuid", "gen_random_uuid", "to_hex", "from_hex",
    "typeof", "pg_typeof", "print_ddl", "sql_dialect", "default_dialect",
    "struct_insert", "struct_extract", "struct_pack", "map", "map_extract", "map_keys", "map_values", "map_entries", "map_from_entries",
    "range", "generate_series", "unnest", "unpivot",
    "cosh", "sinh", "tanh", "asinh", "acosh", "atanh", "sign", "signbit", "isfinite", "isinf", "isnan",
    "pow", "power", "exp", "exp2", "log", "log2", "log10", "ln", "sqrt", "cbrt",
    "ceil", "ceiling", "floor", "round", "trunc", "round_even", "round_even_10th", "round_even_100th", "round_even_1000th",
    "abs", "mod", "div", "gcd", "lcm",
    "bit_count", "bit_position", "bitwise_and", "bitwise_or", "bitwise_xor", "bitwise_not", "bitwise_shift_left", "bitwise_shift_right",
    "arrow", "from_arrow", "to_arrow", "read_parquet", "write_parquet",
    "read_csv", "read_csv_auto", "read_json", "read_json_auto", "read_ndjson", "write_csv", "write_ndjson",
    "read_database", "sql_external_images",
    "approx_count_distinct", "approx_quantile", "approx_selectivity", "sketch", "median", "mode",
    "stddev", "stddev_pop", "stddev_samp", "variance", "variance_pop", "variance_samp",
    "corr", "covar_pop", "covar_samp", "kurtosis", "skewness", "entropy",
    "percentile_cont", "percentile_disc", "quantile", "quantile_cont", "quantile_disc",
    "cum_sum", "cum_mean", "cum_min", "cum_max", "cum_prod", "cumulative_sum", "cumulative_max",
    "cumulative_min", "cumulative_mean", "cumulative_prod", "cumulative_max",
    "row_number", "rank", "dense_rank", "percent_rank", "cume_dist", "ntile",
    "lag", "lead", "first_value", "last_value", "nth_value",
    "coalesce", "ifnull", "if", "nullif", "greatest", "least", "nvl", "nvl2",
    "CASE", "WHEN", "THEN", "ELSE", "END",
    "try_cast", "cast", "convert", "try",
    "alias", "qualify", "qualify", "win", "win0",
    "pivot", "unpivot",
    "unnest", "explode", "lateral", "cross_apply",
    "table", "describe", "explain", "show",
    "create_schema", "create_table", "create_or_replace_table", "create_sequence",
    "create_view", "create_materialized_view", "create_function", "create_macro",
    "export_database", "import_database",
  ],
};

/**
 * Builds the SQL completions map for all supported database types.
 */
function buildSqlCompletions(): Record<DatabaseType, SqlCompletionSet> {
  const types: DatabaseType[] = [
    "mysql", "mariadb", "sqlite", "duckdb", "cassandra", "cockroachdb",
    "snowflake", "postgresql", "greenplum", "redshift", "mssql", "redis",
    "mongodb", "vertica", "clickhouse", "bigquery", "libsql", "cloudflare_d1",
  ];

  const result = {} as Record<DatabaseType, SqlCompletionSet>;

  for (const dbType of types) {
    const dbKeywords = DB_SPECIFIC_KEYWORDS[dbType] || [];
    const dbFunctions = DB_SPECIFIC_FUNCTIONS[dbType] || [];

    // Build functions list by category
    const allFunctions = new Set<string>();
    // Add common functions
    for (const category of Object.values(COMMON_FUNCTIONS)) {
      category.forEach((f) => allFunctions.add(f));
    }
    // Add DB-specific functions
    dbFunctions.forEach((f) => allFunctions.add(f));

    result[dbType] = {
      keywords: [...new Set([...BASE_KEYWORDS, ...dbKeywords])],
      functions: [...allFunctions],
      operators: OPERATORS,
    };
  }

  return result;
}

export const SQL_COMPLETIONS: Record<DatabaseType, SqlCompletionSet> = buildSqlCompletions();

/**
 * Returns the completion set for a given database type.
 * Falls back to postgresql if the type is unknown.
 */
export function getCompletionSet(dbType: DatabaseType | undefined): SqlCompletionSet {
  if (dbType && SQL_COMPLETIONS[dbType]) {
    return SQL_COMPLETIONS[dbType];
  }
  return SQL_COMPLETIONS.postgresql;
}
