import type { BundleCopy } from "./types";

export const TR_BUNDLE_COPY: BundleCopy = {
  common: {
    done: "Bitti",
    cancel: "İptal",
  },
  modes: {
    connections: "Yalnızca bağlantılar",
    bundle: "Tam çalışma alanı paketi",
  },
  connectionsExport: {
    title: "Bağlantıları Dışa Aktar",
    subtitle: "Bağlantıları şifreli, sürümlü bir dışa aktarım olarak kaydet",
    selectLabel: (selected, total) => `Seç (${selected}/${total})`,
    selectAll: "Tümünü Seç",
    deselectAll: "Tümünü Kaldır",
    empty: "Dışa aktarılacak kayıtlı bağlantı yok.",
    encryptionNote:
      "Bağlantılar AES-256-GCM ile şifrelenecek. Parolalar dışa aktarılmaz — içe aktarırken yeniden girmeniz gerekir.",
    passwordLabel: "Şifreleme Parolası",
    passwordPlaceholder: "En az 10 karakter",
    confirmLabel: "Parolayı Onayla",
    confirmPlaceholder: "Parolayı tekrar girin",
    errorPasswordShort: "Parola en az 10 karakter olmalıdır.",
    errorPasswordMismatch: "Parolalar eşleşmiyor.",
    errorNoSelection: "Lütfen en az bir bağlantı seçin.",
    button: (count) => `${count} Bağlantıyı Dışa Aktar`,
    working: "Dışa aktarılıyor...",
    done: (count, path) => `${count} bağlantı ${path} konumuna aktarıldı`,
  },
  export: {
    title: "Çalışma Alanı Paketini Dışa Aktar",
    subtitle: "Tüm çalışma alanı kurulumunu tek dosyada paylaş",
    info: "Paket, ekip paylaşımı için düz bir JSON dosyasıdır. Parolalar, SSH anahtarları ve AI API anahtarları bu makinenin güvenli deposunda kalır — yalnızca hangi kimlik bilgilerinin yeniden girilmesi gerektiğini gösteren bir işaret dışa aktarılır.",
    includes: "İçerik:",
    connections: "Kayıtlı bağlantılar (parolalar hariç)",
    favorites: "SQL favorileri",
    schedules: "Kayıtlı zamanlamalar",
    aiProviders: "AI sağlayıcı ayarları (API anahtarları hariç)",
    uiPrefs: "UI tercihleri (tema, düzenler, kısayollar)",
    button: "Paketi Dışa Aktar",
    working: "Dışa aktarılıyor...",
    done: "Çalışma alanı paketi şuraya aktarıldı:",
  },
  import: {
    dropzoneHint: "TableR Dışa Aktarımı (*.tabler-connections, *.tabler-bundle)",
    title: "Çalışma Alanı Paketini İçe Aktar",
    subtitle: "Paket içeriğini inceleyin ve içe aktarılacakları seçin",
    sections: {
      connections: "Bağlantılar",
      sqlFavorites: "SQL Favorileri",
      schedules: "Zamanlamalar",
      aiProviders: "AI Sağlayıcıları",
      uiPrefs: "UI Tercihleri",
    },
    exists: "zaten var",
    needsPassword: "parola yeniden gerekli",
    uiPrefsMeta: "{total} anahtar · {existing} zaten mevcut",
    uiPrefsWritten: "UI tercih anahtarı",
    uiPrefsRestart: "uygulamak için uygulamayı yeniden başlatın",
    button: "Seçilenleri İçe Aktar",
    working: "İçe aktarılıyor...",
    done: "İçe aktarıldı",
    empty: "Bu pakette öğe yok.",
    external: {
      button: "DBeaver / DataGrip'ten İçe Aktar",
      passwordNote:
        "Parolalar asla içe aktarılmaz — DBeaver ve DataGrip bunları şifreli saklar. İçe aktarmak istediğiniz her bağlantı için veritabanı parolasını girin.",
      skipped: "{count} öğe atlandı (desteklenmeyen motor veya hatalı biçim)",
    },
    connectionsTitle: "Bağlantıları İçe Aktar",
    connectionsSubtitle: "Şifreli bir TableR dosyasından bağlantı yükle",
    sourceFile: "Kaynak dosya",
    dropzonePick: ".tabler-connections veya .tabler-bundle dosyası seçmek için tıklayın",
    externalWorking: "Dosya okunuyor...",
    decryptLabel: "Şifre Çözme Parolası",
    decryptPlaceholder: "Dışa aktarım parolasını girin",
    decryptButton: "Dosyayı Aç",
    decryptWorking: "Şifre çözülüyor...",
    importButton: (count) => `${count} Bağlantıyı İçe Aktar`,
    importWorking: "İçe aktarılıyor...",
    importedMessage: (count) => `${count} bağlantı başarıyla içe aktarıldı`,
    passwordNote:
      "Parolalar dışa aktarılmadı. İçe aktarmak istediğiniz her bağlantı için veritabanı parolasını girin.",
    passwordPlaceholder: "Veritabanı parolası (isteğe bağlı)",
    errorIncorrectPassword: "Parola yanlış. Lütfen tekrar deneyin.",
    errorOpenDialog: (detail) => `Dosya iletişim kutusu açılamadı: ${detail}`,
    errorImportFailed: (detail) => `İçe aktarma başarısız: ${detail}`,
  },
};
