import type { BundleCopy } from "./types";

export const ZH_BUNDLE_COPY: BundleCopy = {
  common: {
    done: "完成",
    cancel: "取消",
  },
  modes: {
    connections: "仅连接",
    bundle: "完整工作区包",
  },
  connectionsExport: {
    title: "导出连接",
    subtitle: "将连接保存为加密的版本化导出文件",
    selectLabel: (selected, total) => `选择（${selected}/${total}）`,
    selectAll: "全选",
    deselectAll: "取消全选",
    empty: "没有可导出的已保存连接。",
    encryptionNote: "连接将使用 AES-256-GCM 加密。密码不会被导出——导入时需要重新输入。",
    passwordLabel: "加密密码",
    passwordPlaceholder: "至少 10 个字符",
    confirmLabel: "确认密码",
    confirmPlaceholder: "再次输入密码",
    errorPasswordShort: "密码至少需要 10 个字符。",
    errorPasswordMismatch: "两次输入的密码不一致。",
    errorNoSelection: "请至少选择一个连接。",
    button: (count) => `导出 ${count} 个连接`,
    working: "正在导出...",
    done: (count, path) => `已将 ${count} 个连接导出到 ${path}`,
  },
  export: {
    title: "导出工作区包",
    subtitle: "将整个工作区配置分享为单个文件",
    info: "该包是用于团队共享的纯 JSON 文件。密码、SSH 密钥和 AI API 密钥保留在本机的安全存储中——仅导出一个标记，以便团队成员知道需要重新输入哪些凭据。",
    includes: "包含：",
    connections: "已保存的连接（不含密码）",
    favorites: "SQL 收藏",
    schedules: "已保存的计划",
    aiProviders: "AI 提供方设置（不含 API 密钥）",
    uiPrefs: "界面偏好（主题、布局、快捷键）",
    button: "导出包",
    working: "正在导出...",
    done: "工作区包已导出到",
  },
  import: {
    dropzoneHint: "TableR 导出文件 (*.tabler-connections, *.tabler-bundle)",
    title: "导入工作区包",
    subtitle: "查看包内容并选择要导入的项目",
    sections: {
      connections: "连接",
      sqlFavorites: "SQL 收藏",
      schedules: "计划",
      aiProviders: "AI 提供方",
      uiPrefs: "界面偏好",
    },
    exists: "已存在",
    needsPassword: "需重新输入密码",
    uiPrefsMeta: "{total} 个键 · {existing} 个已存在",
    uiPrefsWritten: "个界面偏好键",
    uiPrefsRestart: "重启应用后生效",
    button: "导入所选",
    working: "正在导入...",
    done: "已导入",
    empty: "此包中没有内容。",
    external: {
      button: "从 DBeaver / DataGrip 导入",
      passwordNote:
        "密码不会被导入 — DBeaver 和 DataGrip 以加密方式存储密码。请为要导入的每个连接输入数据库密码。",
      skipped: "已跳过 {count} 项（不支持的引擎或格式错误）",
    },
    connectionsTitle: "导入连接",
    connectionsSubtitle: "从加密的 TableR 文件加载连接",
    sourceFile: "源文件",
    dropzonePick: "点击选择 .tabler-connections 或 .tabler-bundle 文件",
    externalWorking: "正在读取文件...",
    decryptLabel: "解密密码",
    decryptPlaceholder: "输入导出密码",
    decryptButton: "打开文件",
    decryptWorking: "正在解密...",
    importButton: (count) => `导入 ${count} 个连接`,
    importWorking: "正在导入...",
    importedMessage: (count) => `已成功导入 ${count} 个连接`,
    passwordNote: "密码未被导出。请为要导入的每个连接输入数据库密码。",
    passwordPlaceholder: "数据库密码（可选）",
    errorIncorrectPassword: "密码不正确，请重试。",
    errorOpenDialog: (detail) => `无法打开文件对话框：${detail}`,
    errorImportFailed: (detail) => `导入失败：${detail}`,
  },
};
