import type { PluginManagerCopy } from "./types";

export const EN_COPY: PluginManagerCopy = {
  kicker: "Plugins",
  title: "Plugin Manager",
  description:
    "Manage core modules, database adapters, and local `.tableplugin` bundles in the current build.",
  bundled: "Bundled",
  adapterCount: "DB adapters",
  coreModules: "Core modules",
  engineAdapters: "Database adapters",
  planned: "External plugin roadmap",
  installed: "Installed local bundles",
  builtin: "Built-in",
  ready: "Ready",
  roadmap: "Roadmap",
  enabled: "Enabled",
  disabled: "Disabled",
  install: "Install plugin",
  reload: "Reload",
  remove: "Remove",
  enable: "Enable plugin",
  disable: "Disable plugin",
  kind: "Kind",
  capabilities: "Capabilities",
  permissions: "Permissions",
  verified: "Verified",
  unverified: "Unsafe",
  rollback: "Roll back",
  rollbackSuccess: "Plugin rolled back",
  registry: "Official registry",
  browseRegistry: "Browse registry",
  storeCta: "Get more plugins",
  storeHint: "Browse the full plugin store on the web and download bundles.",
  registryEmpty:
    'No compatible packages are published for this platform yet. Engine drivers ship as .tableplugin bundles — install one from a local file with "Install from file" when the registry is unreachable.',
  updateAvailable: "Update available",
  installFromRegistry: "Install",
  updateFromRegistry: "Update",
  registryInstalled: "Installed from registry",
  noPlugins:
    "No local plugin bundles installed yet. Engine drivers (DuckDB, Cassandra, Redis, libSQL, Snowflake, ClickHouse, BigQuery, D1, OpenSearch) ship as .tableplugin bundles — fetch them from the registry or install a downloaded bundle from a local file.",
  note: "Format plugins and the read-only OpenSearch driver run through declarative runtimes without native code execution. Other WASM drivers remain experimental and disabled.",
  close: "Close",
  installSuccess: "Plugin installed",
  pluginUpdated: "Plugin state updated",
  pluginRemoved: "Plugin removed",
  overview: "Overview",
  registryUrlLabel: "Registry URL",
  registryUrlHint:
    "HTTPS JSON catalog the marketplace browses. Leave empty to use the built-in default.",
  engine: "Engine",
  installedBadge: "Installed",
  confirmRemove: (name) => `Remove plugin "${name}"?`,
  confirmRollback: (name, previousVersion) => `Roll "${name}" back to ${previousVersion}?`,
  previousVersionFallback: "the previous version",
};
