import type { PluginManagerCopy } from "./types";

export const KO_COPY: PluginManagerCopy = {
  kicker: "플러그인",
  title: "플러그인 관리자",
  description: "현재 빌드의 코어 모듈, 데이터베이스 어댑터, 로컬 `.tableplugin` 번들을 관리합니다.",
  bundled: "기본 포함",
  adapterCount: "DB 어댑터",
  coreModules: "코어 모듈",
  engineAdapters: "데이터베이스 어댑터",
  planned: "외부 플러그인 로드맵",
  installed: "설치된 로컬 번들",
  builtin: "기본 제공",
  ready: "준비됨",
  roadmap: "로드맵",
  enabled: "켜짐",
  disabled: "꺼짐",
  install: "플러그인 설치",
  reload: "새로고침",
  remove: "제거",
  enable: "플러그인 켜기",
  disable: "플러그인 끄기",
  kind: "종류",
  capabilities: "기능",
  permissions: "권한",
  verified: "검증됨",
  unverified: "안전하지 않음",
  rollback: "이전 버전으로 롤백",
  rollbackSuccess: "플러그인이 롤백되었습니다",
  registry: "공식 레지스트리",
  browseRegistry: "레지스트리 열기",
  storeCta: "플러그인 더 받기",
  storeHint: "웹에서 전체 플러그인 스토어를 둘러보고 번들을 다운로드하세요.",
  registryEmpty: "이 플랫폼에 게시된 호환 패키지가 아직 없습니다.",
  updateAvailable: "업데이트 가능",
  installFromRegistry: "설치",
  updateFromRegistry: "업데이트",
  registryInstalled: "레지스트리에서 설치됨",
  noPlugins: "아직 설치된 로컬 플러그인 번들이 없습니다.",
  note: "포맷 플러그인과 읽기 전용 OpenSearch 드라이버는 네이티브 코드 실행 없이 선언적 런타임으로 동작합니다. 다른 WASM 드라이버는 실험 단계이며 비활성화되어 있습니다.",
  close: "닫기",
  installSuccess: "플러그인이 설치되었습니다",
  pluginUpdated: "플러그인 상태가 업데이트되었습니다",
  pluginRemoved: "플러그인이 제거되었습니다",
  overview: "개요",
  registryUrlLabel: "레지스트리 URL",
  registryUrlHint:
    "마켓플레이스가 탐색하는 HTTPS JSON 카탈로그입니다. 비워 두면 기본값을 사용합니다.",
  engine: "엔진",
  installedBadge: "설치됨",
  confirmRemove: (name) => `플러그인 "${name}"을(를) 제거할까요?`,
  confirmRollback: (name, previousVersion) =>
    `"${name}"을(를) ${previousVersion}(으)로 롤백할까요?`,
  previousVersionFallback: "이전 버전",
};
