import type { PluginManagerCopy } from "./types";

export const TR_COPY: PluginManagerCopy = {
  kicker: "Eklentiler",
  title: "Eklenti Yöneticisi",
  description:
    "Mevcut derlemedeki çekirdek modülleri, veritabanı adaptörlerini ve yerel `.tableplugin` paketlerini yönetin.",
  bundled: "Gömülü",
  adapterCount: "DB adaptörü",
  coreModules: "Çekirdek modüller",
  engineAdapters: "Veritabanı adaptörleri",
  planned: "Harici eklenti yol haritası",
  installed: "Kurulu yerel paketler",
  builtin: "Yerleşik",
  ready: "Hazır",
  roadmap: "Yol haritası",
  enabled: "Açık",
  disabled: "Kapalı",
  install: "Eklenti kur",
  reload: "Yenile",
  remove: "Kaldır",
  enable: "Eklentiyi aç",
  disable: "Eklentiyi kapat",
  kind: "Tür",
  capabilities: "Yetenekler",
  permissions: "İzinler",
  verified: "Doğrulandı",
  unverified: "Güvenli değil",
  rollback: "Önceki sürüme dön",
  rollbackSuccess: "Eklenti geri alındı",
  registry: "Resmi kayıt",
  browseRegistry: "Kaydı aç",
  storeCta: "Daha fazla eklenti al",
  storeHint: "Web'deki tam eklenti mağazasına göz atın ve paketleri indirin.",
  registryEmpty: "Bu platform için henüz uyumlu paket yayınlanmadı.",
  updateAvailable: "Güncelleme mevcut",
  installFromRegistry: "Kur",
  updateFromRegistry: "Güncelle",
  registryInstalled: "Kayıttan kuruldu",
  noPlugins: "Henüz kurulu yerel eklenti paketi yok.",
  note: "Biçim eklentileri ve salt-okunur OpenSearch sürücüsü, yerel kod çalıştırmadan bildirimsel çalışma zamanları üzerinden çalışır. Diğer WASM sürücüleri deneyseldir ve devre dışıdır.",
  close: "Kapat",
  installSuccess: "Eklenti kuruldu",
  pluginUpdated: "Eklenti durumu güncellendi",
  pluginRemoved: "Eklenti kaldırıldı",
  overview: "Genel bakış",
  registryUrlLabel: "Kayıt URL'si",
  registryUrlHint:
    "Marketin göz attığı HTTPS JSON kataloğu. Varsayılanı kullanmak için boş bırakın.",
  engine: "Motor",
  installedBadge: "Kurulu",
  confirmRemove: (name) => `"${name}" eklentisi kaldırılsın mı?`,
  confirmRollback: (name, previousVersion) =>
    `"${name}" ${previousVersion} sürümüne geri alınsın mı?`,
  previousVersionFallback: "önceki sürüm",
};
