import type { PluginManagerCopy } from "./types";

export const VI_COPY: PluginManagerCopy = {
  kicker: "Plugins",
  title: "Quản lý plugin",
  description:
    "Quản lý module lõi, adapter DB và plugin local theo bundle `.tableplugin` trong build hiện tại.",
  bundled: "Tích hợp sẵn",
  adapterCount: "Adapter DB",
  coreModules: "Module lõi",
  engineAdapters: "Adapter cơ sở dữ liệu",
  planned: "Lộ trình plugin ngoài",
  installed: "Plugin local đã cài",
  builtin: "Built-in",
  ready: "Sẵn sàng",
  roadmap: "Lộ trình",
  enabled: "Bật",
  disabled: "Tắt",
  install: "Cài plugin",
  reload: "Tải lại",
  remove: "Gỡ",
  enable: "Bật plugin",
  disable: "Tắt plugin",
  kind: "Loại",
  capabilities: "Khả năng",
  permissions: "Quyền truy cập",
  verified: "Đã xác minh",
  unverified: "Không an toàn",
  rollback: "Quay lại bản trước",
  rollbackSuccess: "Đã khôi phục plugin",
  registry: "Registry chính thức",
  browseRegistry: "Mở registry",
  storeCta: "Tải thêm plugin",
  storeHint: "Duyệt kho plugin đầy đủ trên web và tải bundle về.",
  registryEmpty: "Registry chưa có package tương thích cho nền tảng này.",
  updateAvailable: "Có bản cập nhật",
  installFromRegistry: "Cài đặt",
  updateFromRegistry: "Cập nhật",
  registryInstalled: "Đã cài từ registry",
  noPlugins: "Chưa có plugin local nào được cài.",
  note: "Format plugin và driver OpenSearch chỉ đọc chạy qua runtime khai báo, không thực thi mã native. Driver WASM khác vẫn ở trạng thái thử nghiệm và chưa được kích hoạt.",
  close: "Đóng",
  installSuccess: "Đã cài plugin",
  pluginUpdated: "Đã cập nhật trạng thái plugin",
  pluginRemoved: "Đã gỡ plugin",
  overview: "Tổng quan",
  registryUrlLabel: "URL registry",
  registryUrlHint:
    "Catalog JSON qua HTTPS mà marketplace duyệt. Để trống để dùng mặc định tích hợp.",
  engine: "Engine",
  installedBadge: "Đã cài",
  confirmRemove: (name) => `Gỡ plugin "${name}"?`,
  confirmRollback: (name, previousVersion) =>
    `Khôi phục "${name}" về phiên bản ${previousVersion}?`,
  previousVersionFallback: "phiên bản trước",
};
