import type { PluginManagerCopy } from "./types";

export const ZH_COPY: PluginManagerCopy = {
  kicker: "插件",
  title: "插件管理器",
  description: "管理当前构建中的核心模块、数据库适配器和本地 `.tableplugin` 包。",
  bundled: "内置",
  adapterCount: "数据库适配器",
  coreModules: "核心模块",
  engineAdapters: "数据库适配器",
  planned: "外部插件路线图",
  installed: "已安装的本地包",
  builtin: "内置",
  ready: "就绪",
  roadmap: "路线图",
  enabled: "已启用",
  disabled: "已禁用",
  install: "安装插件",
  reload: "重新加载",
  remove: "移除",
  enable: "启用插件",
  disable: "禁用插件",
  kind: "类型",
  capabilities: "能力",
  permissions: "权限",
  verified: "已验证",
  unverified: "不安全",
  rollback: "回滚",
  rollbackSuccess: "插件已回滚",
  registry: "官方注册表",
  browseRegistry: "浏览注册表",
  storeCta: "获取更多插件",
  storeHint: "在网页上浏览完整的插件商店并下载包。",
  registryEmpty: "此平台尚未发布兼容的包。",
  updateAvailable: "有可用更新",
  installFromRegistry: "安装",
  updateFromRegistry: "更新",
  registryInstalled: "已从注册表安装",
  noPlugins: "尚未安装本地插件包。",
  note: "格式插件和只读 OpenSearch 驱动通过声明式运行时运行，不执行原生代码。其他 WASM 驱动仍处于实验阶段并已禁用。",
  close: "关闭",
  installSuccess: "插件已安装",
  pluginUpdated: "插件状态已更新",
  pluginRemoved: "插件已移除",
  overview: "概览",
  registryUrlLabel: "注册表 URL",
  registryUrlHint: "市场浏览的 HTTPS JSON 目录。留空则使用内置默认值。",
  engine: "引擎",
  installedBadge: "已安装",
  previousVersionFallback: "上一个版本",
  confirmRemove: (name) => `移除插件“${name}”？`,
  confirmRollback: (name, previousVersion) => `将“${name}”回滚到 ${previousVersion}？`,
};
