import { type AIMetricsSchemaTableHint, type MetricsWidgetSeed } from "./shared";
import { getPostgresAdaptiveOverviewTemplate } from "./template-builders";

export function buildPostgresSchemaOverviewSeeds(): MetricsWidgetSeed[] {
  return [
    {
      type: "scoreboard",
      title: "Total Tables",
      query: [
        "SELECT",
        "  COUNT(*)::bigint AS total_tables,",
        "  'tables' AS label",
        "FROM information_schema.tables",
        "WHERE table_schema NOT IN ('pg_catalog', 'information_schema')",
        "  AND table_type = 'BASE TABLE';",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 0,
      gridY: 0,
    },
    {
      type: "scoreboard",
      title: "Estimated Rows",
      query: [
        "SELECT",
        "  COALESCE(SUM(n_live_tup), 0)::bigint AS estimated_rows,",
        "  'rows' AS label",
        "FROM pg_stat_user_tables",
        "WHERE schemaname NOT IN ('pg_catalog', 'information_schema');",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 3,
      gridY: 0,
    },
    {
      type: "bar",
      title: "Top Tables by Rows",
      query: [
        "SELECT",
        "  relname AS label,",
        "  COALESCE(n_live_tup, 0)::bigint AS value",
        "FROM pg_stat_user_tables",
        "WHERE schemaname NOT IN ('pg_catalog', 'information_schema')",
        "ORDER BY value DESC NULLS LAST, label ASC",
        "LIMIT 12;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 6,
      gridY: 0,
    },
    {
      type: "pie",
      title: "Row Share by Table",
      query: [
        "SELECT",
        "  relname AS label,",
        "  COALESCE(n_live_tup, 0)::bigint AS value",
        "FROM pg_stat_user_tables",
        "WHERE schemaname NOT IN ('pg_catalog', 'information_schema')",
        "ORDER BY value DESC NULLS LAST, label ASC",
        "LIMIT 8;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 10,
      gridY: 0,
    },
    {
      type: "table",
      title: "Largest Tables",
      query: [
        "SELECT",
        "  relname AS table_name,",
        "  COALESCE(n_live_tup, 0)::bigint AS estimated_rows,",
        "  pg_size_pretty(pg_total_relation_size(relid)) AS total_size",
        "FROM pg_stat_user_tables",
        "WHERE schemaname NOT IN ('pg_catalog', 'information_schema')",
        "ORDER BY estimated_rows DESC NULLS LAST, table_name ASC",
        "LIMIT 10;",
      ].join("\n"),
      colSpan: 6,
      rowSpan: 4,
      gridX: 0,
      gridY: 4,
    },
    {
      type: "bar",
      title: "Columns by Table",
      query: [
        "SELECT",
        "  table_name AS label,",
        "  COUNT(*)::bigint AS value",
        "FROM information_schema.columns",
        "WHERE table_schema NOT IN ('pg_catalog', 'information_schema')",
        "GROUP BY table_name",
        "ORDER BY value DESC, label ASC",
        "LIMIT 12;",
      ].join("\n"),
      colSpan: 6,
      rowSpan: 4,
      gridX: 6,
      gridY: 4,
    },
    {
      type: "scoreboard",
      title: "Total Columns",
      query: [
        "SELECT",
        "  COUNT(*)::bigint AS total_columns,",
        "  'columns' AS label",
        "FROM information_schema.columns",
        "WHERE table_schema NOT IN ('pg_catalog', 'information_schema');",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 0,
      gridY: 8,
    },
    {
      type: "scoreboard",
      title: "Active Schemas",
      query: [
        "SELECT",
        "  COUNT(DISTINCT table_schema)::bigint AS total_schemas,",
        "  'schemas' AS label",
        "FROM information_schema.tables",
        "WHERE table_schema NOT IN ('pg_catalog', 'information_schema')",
        "  AND table_type = 'BASE TABLE';",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 3,
      gridY: 8,
    },
    {
      type: "bar",
      title: "Table Size by Table",
      query: [
        "SELECT",
        "  relname AS label,",
        "  pg_total_relation_size(relid)::bigint AS value",
        "FROM pg_stat_user_tables",
        "WHERE schemaname NOT IN ('pg_catalog', 'information_schema')",
        "ORDER BY value DESC NULLS LAST, label ASC",
        "LIMIT 12;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 6,
      gridY: 8,
    },
    {
      type: "pie",
      title: "Column Share by Table",
      query: [
        "SELECT",
        "  table_name AS label,",
        "  COUNT(*)::bigint AS value",
        "FROM information_schema.columns",
        "WHERE table_schema NOT IN ('pg_catalog', 'information_schema')",
        "GROUP BY table_name",
        "ORDER BY value DESC, label ASC",
        "LIMIT 8;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 10,
      gridY: 8,
    },
  ];
}

export function buildPostgresOverviewSeeds(
  schemaHints?: AIMetricsSchemaTableHint[],
): MetricsWidgetSeed[] {
  const adaptiveTemplate = getPostgresAdaptiveOverviewTemplate(schemaHints);
  if (adaptiveTemplate) {
    return adaptiveTemplate.widgets;
  }
  return buildPostgresSchemaOverviewSeeds();
}

export function buildMySqlOverviewSeeds(): MetricsWidgetSeed[] {
  return [
    {
      type: "scoreboard",
      title: "Total Tables",
      query: [
        "SELECT",
        "  COUNT(*) AS total_tables,",
        "  'tables' AS label",
        "FROM information_schema.tables",
        "WHERE table_schema = DATABASE()",
        "  AND table_type = 'BASE TABLE';",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 0,
      gridY: 0,
    },
    {
      type: "scoreboard",
      title: "Estimated Rows",
      query: [
        "SELECT",
        "  COALESCE(SUM(table_rows), 0) AS estimated_rows,",
        "  'rows' AS label",
        "FROM information_schema.tables",
        "WHERE table_schema = DATABASE()",
        "  AND table_type = 'BASE TABLE';",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 3,
      gridY: 0,
    },
    {
      type: "bar",
      title: "Top Tables by Rows",
      query: [
        "SELECT",
        "  table_name AS label,",
        "  COALESCE(table_rows, 0) AS value",
        "FROM information_schema.tables",
        "WHERE table_schema = DATABASE()",
        "  AND table_type = 'BASE TABLE'",
        "ORDER BY value DESC, label ASC",
        "LIMIT 12;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 6,
      gridY: 0,
    },
    {
      type: "pie",
      title: "Row Share by Table",
      query: [
        "SELECT",
        "  table_name AS label,",
        "  COALESCE(table_rows, 0) AS value",
        "FROM information_schema.tables",
        "WHERE table_schema = DATABASE()",
        "  AND table_type = 'BASE TABLE'",
        "ORDER BY value DESC, label ASC",
        "LIMIT 8;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 10,
      gridY: 0,
    },
    {
      type: "table",
      title: "Largest Tables",
      query: [
        "SELECT",
        "  table_name,",
        "  COALESCE(table_rows, 0) AS estimated_rows,",
        "  ROUND((COALESCE(data_length, 0) + COALESCE(index_length, 0)) / 1024 / 1024, 1) AS total_mb",
        "FROM information_schema.tables",
        "WHERE table_schema = DATABASE()",
        "  AND table_type = 'BASE TABLE'",
        "ORDER BY estimated_rows DESC, table_name ASC",
        "LIMIT 10;",
      ].join("\n"),
      colSpan: 6,
      rowSpan: 4,
      gridX: 0,
      gridY: 4,
    },
    {
      type: "bar",
      title: "Columns by Table",
      query: [
        "SELECT",
        "  table_name AS label,",
        "  COUNT(*) AS value",
        "FROM information_schema.columns",
        "WHERE table_schema = DATABASE()",
        "GROUP BY table_name",
        "ORDER BY value DESC, label ASC",
        "LIMIT 12;",
      ].join("\n"),
      colSpan: 6,
      rowSpan: 4,
      gridX: 6,
      gridY: 4,
    },
  ];
}

export function buildMsSqlOverviewSeeds(): MetricsWidgetSeed[] {
  return [
    {
      type: "scoreboard",
      title: "Total Tables",
      query: [
        "SELECT",
        "  COUNT(*) AS total_tables,",
        "  'tables' AS label",
        "FROM sys.tables;",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 0,
      gridY: 0,
    },
    {
      type: "scoreboard",
      title: "Estimated Rows",
      query: [
        "SELECT",
        "  COALESCE(SUM(p.rows), 0) AS estimated_rows,",
        "  'rows' AS label",
        "FROM sys.partitions p",
        "WHERE p.index_id IN (0, 1);",
      ].join("\n"),
      colSpan: 3,
      rowSpan: 3,
      gridX: 3,
      gridY: 0,
    },
    {
      type: "bar",
      title: "Top Tables by Rows",
      query: [
        "SELECT TOP (12)",
        "  CONCAT(s.name, '.', t.name) AS label,",
        "  SUM(p.rows) AS value",
        "FROM sys.tables t",
        "JOIN sys.schemas s ON s.schema_id = t.schema_id",
        "JOIN sys.partitions p ON p.object_id = t.object_id",
        "WHERE p.index_id IN (0, 1)",
        "GROUP BY s.name, t.name",
        "ORDER BY value DESC, label ASC;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 6,
      gridY: 0,
    },
    {
      type: "pie",
      title: "Row Share by Table",
      query: [
        "SELECT TOP (8)",
        "  CONCAT(s.name, '.', t.name) AS label,",
        "  SUM(p.rows) AS value",
        "FROM sys.tables t",
        "JOIN sys.schemas s ON s.schema_id = t.schema_id",
        "JOIN sys.partitions p ON p.object_id = t.object_id",
        "WHERE p.index_id IN (0, 1)",
        "GROUP BY s.name, t.name",
        "ORDER BY value DESC, label ASC;",
      ].join("\n"),
      colSpan: 4,
      rowSpan: 4,
      gridX: 10,
      gridY: 0,
    },
    {
      type: "table",
      title: "Largest Tables",
      query: [
        "WITH row_counts AS (",
        "  SELECT",
        "    t.object_id,",
        "    SUM(p.rows) AS row_count",
        "  FROM sys.tables t",
        "  JOIN sys.partitions p ON p.object_id = t.object_id",
        "  WHERE p.index_id IN (0, 1)",
        "  GROUP BY t.object_id",
        ")",
        "SELECT TOP (10)",
        "  CONCAT(s.name, '.', t.name) AS table_name,",
        "  COALESCE(rc.row_count, 0) AS row_count,",
        "  COUNT(c.column_id) AS column_count",
        "FROM sys.tables t",
        "JOIN sys.schemas s ON s.schema_id = t.schema_id",
        "LEFT JOIN row_counts rc ON rc.object_id = t.object_id",
        "LEFT JOIN sys.columns c ON c.object_id = t.object_id",
        "GROUP BY s.name, t.name, rc.row_count",
        "ORDER BY row_count DESC, table_name ASC;",
      ].join("\n"),
      colSpan: 6,
      rowSpan: 4,
      gridX: 0,
      gridY: 4,
    },
    {
      type: "bar",
      title: "Columns by Table",
      query: [
        "SELECT TOP (12)",
        "  CONCAT(s.name, '.', t.name) AS label,",
        "  COUNT(c.column_id) AS value",
        "FROM sys.tables t",
        "JOIN sys.schemas s ON s.schema_id = t.schema_id",
        "LEFT JOIN sys.columns c ON c.object_id = t.object_id",
        "GROUP BY s.name, t.name",
        "ORDER BY value DESC, label ASC;",
      ].join("\n"),
      colSpan: 6,
      rowSpan: 4,
      gridX: 6,
      gridY: 4,
    },
  ];
}
