import { beforeEach, describe, expect, it } from "vitest";
import { generateTestRows, isAutoGeneratedColumn } from "@/utils/test-row-generator";
import { stageGeneratedRows } from "@/components/GenerateTestRows/stage-seed-rows";
import { useChangeTrackingStore } from "@/stores/change-tracking-store";
import type { ColumnDetail } from "@/types";

function col(partial: Partial<ColumnDetail> & { name: string }): ColumnDetail {
  return {
    data_type: "text",
    is_nullable: true,
    is_primary_key: false,
    ...partial,
  };
}

describe("generateTestRows", () => {
  it("produces the requested number of rows keyed by column name", () => {
    const rows = generateTestRows(
      [col({ name: "id", data_type: "int" }), col({ name: "email" })],
      25,
    );
    expect(rows).toHaveLength(25);
    for (const row of rows) {
      expect(Object.keys(row).sort()).toEqual(["email", "id"]);
    }
  });

  it("skips auto-generated columns so the database fills them", () => {
    expect(
      isAutoGeneratedColumn(col({ name: "id", data_type: "int", extra: "auto_increment" })),
    ).toBe(true);
    expect(isAutoGeneratedColumn(col({ name: "id", data_type: "bigserial" }))).toBe(true);
    expect(
      isAutoGeneratedColumn(col({ name: "id", data_type: "int", default_value: "nextval('s')" })),
    ).toBe(true);
    expect(isAutoGeneratedColumn(col({ name: "id", data_type: "int" }))).toBe(false);

    const rows = generateTestRows(
      [
        col({ name: "id", data_type: "int", extra: "auto_increment", is_primary_key: true }),
        col({ name: "name" }),
      ],
      5,
    );
    for (const row of rows) {
      expect(row).not.toHaveProperty("id");
      expect(row).toHaveProperty("name");
    }
  });

  it("keeps primary-key values unique within a batch", () => {
    const rows = generateTestRows(
      [col({ name: "id", data_type: "int", is_primary_key: true, is_nullable: false })],
      200,
    );
    const ids = new Set(rows.map((row) => row.id));
    expect(ids.size).toBe(200);
  });

  it("respects declared varchar length", () => {
    const rows = generateTestRows(
      [col({ name: "code", column_type: "varchar(8)", data_type: "varchar", is_nullable: false })],
      50,
    );
    for (const row of rows) {
      expect(String(row.code).length).toBeLessThanOrEqual(8);
    }
  });

  it("picks enum members for enum columns", () => {
    const rows = generateTestRows(
      [
        col({
          name: "status",
          column_type: "enum('new','done')",
          data_type: "enum",
          is_nullable: false,
        }),
      ],
      30,
    );
    for (const row of rows) {
      expect(["new", "done"]).toContain(row.status);
    }
  });

  it("uses Vietnamese name pools when the hint asks for VN names", () => {
    const rows = generateTestRows(
      [col({ name: "full_name", is_nullable: false })],
      20,
      "realistic VN names",
    );
    const vnLastNames = [
      "Nguyen",
      "Tran",
      "Le",
      "Pham",
      "Hoang",
      "Huynh",
      "Phan",
      "Vu",
      "Vo",
      "Dang",
      "Bui",
      "Do",
      "Ho",
      "Ngo",
      "Duong",
      "Ly",
    ];
    for (const row of rows) {
      expect(vnLastNames.some((part) => String(row.full_name).startsWith(part))).toBe(true);
    }
  });

  it("emits typed values: numbers for ints, booleans for bools, ISO-ish dates", () => {
    const [row] = generateTestRows(
      [
        col({ name: "qty", data_type: "int", is_nullable: false }),
        col({ name: "flag", data_type: "boolean", is_nullable: false }),
        col({ name: "created", data_type: "date", is_nullable: false }),
        col({
          name: "price",
          column_type: "decimal(10,2)",
          data_type: "decimal",
          is_nullable: false,
        }),
      ],
      1,
    );
    expect(typeof row.qty).toBe("number");
    expect(typeof row.flag).toBe("boolean");
    expect(String(row.created)).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(typeof row.price).toBe("number");
  });
});

describe("stageGeneratedRows", () => {
  beforeEach(() => {
    useChangeTrackingStore.setState({
      stagedChanges: [],
      history: {},
      future: {},
      isPreviewOpen: false,
      selectedChangeId: null,
      _columnNameMap: {},
      _dbTypeMap: {},
    });
  });

  it("stages rows as one undo unit with resolved column names and opens the preview", () => {
    const columns = [col({ name: "id", data_type: "int" }), col({ name: "name" })];
    const rows = generateTestRows(columns, 3);
    const staged = stageGeneratedRows({ tableName: "users", columns, rows });

    expect(staged).toBe(3);
    const state = useChangeTrackingStore.getState();
    expect(state.stagedChanges).toHaveLength(3);
    expect(state.isPreviewOpen).toBe(true);
    // One batch = one undo step under the table's scope key.
    expect(state.history["||users"]).toHaveLength(1);
    for (const change of state.stagedChanges) {
      expect(change.type).toBe("insert");
      expect(change.tableName).toBe("users");
      expect(change.sqlPreview).toMatch(/^INSERT INTO users \(/);
      expect(change.sqlPreview).toContain("id");
      expect(change.sqlPreview).toContain("name");
    }
  });

  it("reuses the grid-registered column map instead of overwriting it", () => {
    useChangeTrackingStore.getState().setColumnNameMap("users", { 0: "id", 5: "name" });
    const staged = stageGeneratedRows({
      tableName: "users",
      columns: [col({ name: "id", data_type: "int" }), col({ name: "name" })],
      rows: [{ id: 1, name: "A" }],
    });
    expect(staged).toBe(1);
    const change = useChangeTrackingStore.getState().stagedChanges[0];
    expect(change.columns).toHaveProperty("id");
    expect(change.columns).toHaveProperty("name");
    // Map untouched — still the grid's registration.
    expect(useChangeTrackingStore.getState()._columnNameMap.users).toEqual({ 0: "id", 5: "name" });
  });
});
